/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupStatus } from '@eclipse-che/common';
import { FastifyInstance } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { setup, teardown } from '@/utils/appBuilder';

jest.mock('@/routes/api/helpers/getServiceAccountToken');
jest.mock('@/routes/api/helpers/getDevWorkspaceClient');
jest.mock('@/services/kubeclient/kubeConfigProvider');

// Mock BackupApiService
const mockGetWorkspaceBackupStatus = jest.fn();
jest.mock('@/devworkspaceClient/services/backupApi', () => ({
  BackupApiService: jest.fn().mockImplementation(() => ({
    getWorkspaceBackupStatus: mockGetWorkspaceBackupStatus,
  })),
}));

// Mock RegistryApiService
const mockListBackupImages = jest.fn();
const mockValidateBackupImage = jest.fn();
const mockGetImageMetadata = jest.fn();
jest.mock('@/devworkspaceClient/services/registryApi', () => ({
  RegistryApiService: jest.fn().mockImplementation(() => ({
    listBackupImages: mockListBackupImages,
    validateBackupImage: mockValidateBackupImage,
    getImageMetadata: mockGetImageMetadata,
  })),
}));

// Mock prepareBatchV1API
const mockReadNamespacedJobStatus = jest.fn();
const mockListNamespacedJob = jest.fn();
const mockDeleteNamespacedJob = jest.fn();
jest.mock('@/devworkspaceClient/services/helpers/prepareBatchV1API', () => ({
  prepareBatchV1API: jest.fn(() => ({
    readNamespacedJobStatus: mockReadNamespacedJobStatus,
    listNamespacedJob: mockListNamespacedJob,
    deleteNamespacedJob: mockDeleteNamespacedJob,
  })),
}));

describe('Route Registration Integration Tests', () => {
  let app: FastifyInstance;
  const namespace = 'user-che';

  const setupDefaultMocks = () => {
    mockGetWorkspaceBackupStatus.mockResolvedValue({
      workspaceName: 'my-workspace',
      status: BackupStatus.SUCCESS,
    });

    mockListBackupImages.mockResolvedValue({
      items: [],
      total: 0,
    });

    mockValidateBackupImage.mockResolvedValue({
      valid: true,
    });

    mockGetImageMetadata.mockResolvedValue({
      workspaceName: 'test-workspace',
      timestamp: '2025-01-01T00:00:00Z',
    });

    mockReadNamespacedJobStatus.mockResolvedValue({
      body: {
        status: {
          succeeded: 1,
          startTime: new Date('2025-01-01T00:00:00Z'),
          completionTime: new Date('2025-01-01T00:05:00Z'),
          conditions: [],
        },
      },
    });

    mockListNamespacedJob.mockResolvedValue({
      body: { items: [] },
    });

    mockDeleteNamespacedJob.mockResolvedValue({});
  };

  beforeAll(async () => {
    setupDefaultMocks();
    app = await setup();
  });

  afterAll(() => {
    teardown(app);
  });

  afterEach(() => {
    jest.clearAllMocks();
    setupDefaultMocks();
  });

  describe('Backup Routes Registration', () => {
    it('should register backup status route and be accessible', async () => {
      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/my-workspace/backup-status`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should register list backups route and be accessible', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should register validate backup route and be accessible', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: 'quay.io/test/backup:latest' });

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should register metadata route and be accessible', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl: 'quay.io/test/backup:latest' });

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });
  });

  describe('Jobs Routes Registration', () => {
    it('should register job status route and be accessible', async () => {
      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/backup-job-123/status`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should register list jobs route and be accessible', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should register delete job route and be accessible', async () => {
      const res = await app
        .inject()
        .delete(`${baseApiPath}/namespace/${namespace}/jobs/test-job`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });
  });

  describe('Route Conflicts', () => {
    it('should not conflict with existing devworkspace routes', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/devworkspaces`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should not conflict with pods routes', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/pods`);

      expect(res.statusCode).toBeLessThan(500);
      expect(res.statusCode).not.toBe(404);
    });

    it('should properly differentiate between backup routes', async () => {
      const listRes = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      const validateRes = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: 'test-url' });

      expect(listRes.statusCode).toBeLessThan(500);
      expect(validateRes.statusCode).toBeLessThan(500);
      expect(listRes.statusCode).not.toBe(404);
      expect(validateRes.statusCode).not.toBe(404);
    });

    it('should properly differentiate between jobs routes', async () => {
      const listRes = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      const statusRes = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/test-job/status`);

      expect(listRes.statusCode).toBeLessThan(500);
      expect(statusRes.statusCode).toBeLessThan(500);
      expect(listRes.statusCode).not.toBe(404);
      expect(statusRes.statusCode).not.toBe(404);
    });
  });

  describe('Error Handling Middleware', () => {
    it('should apply error handling to backup status route', async () => {
      mockGetWorkspaceBackupStatus.mockRejectedValue(new Error('Test error'));

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/test/backup-status`);

      expect(res.statusCode).toEqual(500);
      expect(res.json()).toHaveProperty('message');
    });

    it('should apply error handling to job status route', async () => {
      mockReadNamespacedJobStatus.mockRejectedValue(new Error('Test error'));

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/test-job/status`);

      expect(res.statusCode).toEqual(500);
      expect(res.json()).toHaveProperty('message');
    });

    it('should handle validation errors in backup validate route', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: '' });

      expect(res.statusCode).toEqual(400);
      expect(res.json()).toHaveProperty('message');
    });

    it('should handle validation errors in backup metadata route', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({});

      expect(res.statusCode).toEqual(400);
      expect(res.json()).toHaveProperty('message');
    });
  });

  describe('CORS Headers', () => {
    it('should apply CORS headers to backup list route', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.headers).toBeDefined();
      expect(res.statusCode).toBeLessThan(500);
    });

    it('should apply CORS headers to job status route', async () => {
      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/test-job/status`);

      expect(res.headers).toBeDefined();
      expect(res.statusCode).toBeLessThan(500);
    });

    it('should apply CORS headers to POST backup routes', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: 'test-url' });

      expect(res.headers).toBeDefined();
      expect(res.statusCode).toBeLessThan(500);
    });
  });

  describe('Swagger Documentation', () => {
    it('should include backup routes in swagger spec', async () => {
      const res = await app.inject().get('/dashboard/api/swagger/json');

      expect(res.statusCode).toEqual(200);
      const swagger = res.json();

      expect(swagger.paths).toBeDefined();
      const backupRoutes = Object.keys(swagger.paths).filter(path => path.includes('backup'));
      expect(backupRoutes.length).toBeGreaterThan(0);
    });

    it('should include jobs routes in swagger spec', async () => {
      const res = await app.inject().get('/dashboard/api/swagger/json');

      expect(res.statusCode).toEqual(200);
      const swagger = res.json();

      expect(swagger.paths).toBeDefined();
      const jobsRoutes = Object.keys(swagger.paths).filter(path => path.includes('jobs'));
      expect(jobsRoutes.length).toBeGreaterThan(0);
    });

    it('should tag backup routes with "Backup" tag', async () => {
      const res = await app.inject().get('/dashboard/api/swagger/json');

      expect(res.statusCode).toEqual(200);
      const swagger = res.json();

      const backupRoute = Object.keys(swagger.paths).find(path => path.includes('backup-status'));
      if (backupRoute) {
        const routeSpec = swagger.paths[backupRoute];
        const method = Object.keys(routeSpec)[0];
        expect(routeSpec[method].tags).toContain('Backup');
      }
    });

    it('should tag jobs routes with "Job" tag', async () => {
      const res = await app.inject().get('/dashboard/api/swagger/json');

      expect(res.statusCode).toEqual(200);
      const swagger = res.json();

      const jobsRoute = Object.keys(swagger.paths).find(
        path => path.includes('jobs') && path.includes('status'),
      );
      if (jobsRoute) {
        const routeSpec = swagger.paths[jobsRoute];
        const method = Object.keys(routeSpec)[0];
        expect(routeSpec[method].tags).toContain('Job');
      }
    });
  });

  describe('Health Check', () => {
    it('should remain responsive after adding new routes', async () => {
      const backupRes = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      const jobsRes = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/test-job/status`);

      expect(backupRes.statusCode).toBeLessThan(500);
      expect(jobsRes.statusCode).toBeLessThan(500);
      expect(backupRes.statusCode).not.toBe(404);
      expect(jobsRes.statusCode).not.toBe(404);
    });
  });

  describe('HTTP Method Validation', () => {
    it('should reject POST to GET-only backup list route', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups`)
        .payload({});

      expect([404, 405]).toContain(res.statusCode);
    });

    it('should reject GET to POST-only backup validate route', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups/validate`);

      expect([404, 405]).toContain(res.statusCode);
    });

    it('should reject POST to GET-only job status route', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/jobs/test-job/status`)
        .payload({});

      expect([404, 405]).toContain(res.statusCode);
    });

    it('should reject GET to DELETE-only job delete route', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs/test-job`);

      expect([404, 405]).toContain(res.statusCode);
    });
  });

  describe('Route Parameter Validation', () => {
    it('should validate namespace parameter in backup routes', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace//backups`);

      expect(res.statusCode).toEqual(400);
    });

    it('should validate namespace parameter in jobs routes', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace//jobs`);

      // Empty namespace results in 400 or 404 depending on route handler
      expect([200, 400, 404]).toContain(res.statusCode);
    });

    it('should validate required workspace name in backup status route', async () => {
      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces//backup-status`);

      expect([200, 400, 404]).toContain(res.statusCode);
    });

    it('should validate required job name in job status route', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs//status`);

      expect([200, 400, 404]).toContain(res.statusCode);
    });
  });

  describe('Authentication Middleware', () => {
    it('should apply authentication to backup routes', async () => {
      mockGetWorkspaceBackupStatus.mockResolvedValue({
        workspaceName: 'test',
        status: BackupStatus.SUCCESS,
      });

      await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/test/backup-status`);

      expect(mockGetWorkspaceBackupStatus).toHaveBeenCalled();
    });

    it('should apply authentication to jobs routes', async () => {
      mockReadNamespacedJobStatus.mockResolvedValue({
        body: {
          status: {
            succeeded: 1,
            startTime: new Date('2025-01-01T00:00:00Z'),
            completionTime: new Date('2025-01-01T00:05:00Z'),
            conditions: [],
          },
        },
      });

      await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs/test-job/status`);

      expect(mockReadNamespacedJobStatus).toHaveBeenCalled();
    });
  });

  describe('Backwards Compatibility', () => {
    it('should not break existing server-config route', async () => {
      const res = await app.inject().get(`${baseApiPath}/server-config`);

      expect(res.statusCode).toBeLessThan(500);
    });

    it('should not break existing user-profile route', async () => {
      const res = await app.inject().get(`${baseApiPath}/userprofile/${namespace}`);

      expect(res.statusCode).not.toBe(404);
    });

    it('should preserve existing devworkspaces routes', async () => {
      const routes = app.printRoutes();

      expect(routes).toContain('devworkspace');
    });
  });

  describe('Route Accessibility via Print Routes', () => {
    it('should list backup-status route in routes tree', () => {
      const routes = app.printRoutes();

      expect(routes).toContain('/backup-status');
      expect(routes).toContain('backups');
    });

    it('should list jobs routes in routes tree', () => {
      const routes = app.printRoutes();

      expect(routes).toContain('jobs');
      expect(routes).toContain('/status');
    });

    it('should list validate and metadata backup routes', () => {
      const routes = app.printRoutes();

      expect(routes).toContain('validate');
      expect(routes).toContain('metadata');
    });
  });
});
