/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BACKUP_STATUS_LABELS, BackupStatus } from '@eclipse-che/common';
import { Icon, Label, LabelProps } from '@patternfly/react-core';
import {
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InfoCircleIcon,
  InProgressIcon,
} from '@patternfly/react-icons';
import React from 'react';

import styles from '@/components/BackupStatusBadge/index.module.css';
import { CheTooltip } from '@/components/CheTooltip';
import { formatDate, formatRelativeDate } from '@/services/helpers/dates';

export type BackupStatusBadgeSize = 'sm' | 'md' | 'lg';

export type Props = {
  status: BackupStatus;
  lastBackupTime?: string;
  backupImageUrl?: string;
  size?: BackupStatusBadgeSize;
};

const STATUS_COLORS: Record<BackupStatus, LabelProps['color']> = {
  [BackupStatus.SUCCESS]: 'green',
  [BackupStatus.FAILED]: 'orange',
  [BackupStatus.IN_PROGRESS]: 'blue',
  [BackupStatus.NEVER]: 'grey',
};

function getStatusIcon(status: BackupStatus): React.ReactElement {
  switch (status) {
    case BackupStatus.SUCCESS:
      return (
        <Icon status="success" isInline>
          <CheckCircleIcon />
        </Icon>
      );
    case BackupStatus.FAILED:
      return (
        <Icon status="warning" isInline>
          <ExclamationTriangleIcon />
        </Icon>
      );
    case BackupStatus.IN_PROGRESS:
      return (
        <Icon status="info" isInline>
          <InProgressIcon className={styles.rotate} />
        </Icon>
      );
    case BackupStatus.NEVER:
      return (
        <Icon status="default" isInline>
          <InfoCircleIcon />
        </Icon>
      );
  }
}

function getTooltipContent(
  status: BackupStatus,
  lastBackupTime?: string,
  backupImageUrl?: string,
): React.ReactElement {
  const lines: string[] = [`Status: ${BACKUP_STATUS_LABELS[status]}`];

  if (lastBackupTime) {
    const date = new Date(lastBackupTime);
    lines.push(`Last backup: ${formatDate(date)}`);
  }

  if (backupImageUrl) {
    lines.push(`Image: ${backupImageUrl}`);
  }

  if (status === BackupStatus.NEVER) {
    lines.push('This workspace has never been backed up.');
  }

  return (
    <div data-testid="backup-status-tooltip-content">
      {lines.map((line, index) => (
        <div key={index}>{line}</div>
      ))}
    </div>
  );
}

function getTimeLabel(status: BackupStatus, lastBackupTime?: string): string {
  if (lastBackupTime && status !== BackupStatus.NEVER) {
    const date = new Date(lastBackupTime);
    return formatRelativeDate(date);
  }
  return '';
}

export function BackupStatusBadge(props: Props): React.ReactElement {
  const { status, lastBackupTime, backupImageUrl, size = 'md' } = props;

  const color = STATUS_COLORS[status];
  const icon = getStatusIcon(status);
  const tooltipContent = getTooltipContent(status, lastBackupTime, backupImageUrl);
  const timeLabel = getTimeLabel(status, lastBackupTime);

  const sizeClassName = styles[`size-${size}`] || '';
  const className = `${styles.backupStatusBadge} ${sizeClassName}`.trim();

  const statusLabel = BACKUP_STATUS_LABELS[status];
  const labelText = timeLabel ? `${statusLabel} ${timeLabel}` : statusLabel;

  return (
    <CheTooltip content={tooltipContent}>
      <Label className={className} color={color} icon={icon} data-testid="backup-status-badge">
        {labelText}
      </Label>
    </CheTooltip>
  );
}
