/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupItem, BackupValidationResult } from '@eclipse-che/common';
import {
  Alert,
  AlertVariant,
  Button,
  ButtonVariant,
  Divider,
  FormGroup,
  HelperText,
  HelperTextItem,
  PageSection,
  PageSectionVariants,
  Radio,
  Select,
  SelectOption,
  SelectVariant,
  Spinner,
  TextInput,
  Title,
  ValidatedOptions,
} from '@patternfly/react-core';
import { CheckCircleIcon, ExclamationCircleIcon } from '@patternfly/react-icons';
import React from 'react';
import { connect, ConnectedProps } from 'react-redux';
import { NavigateFunction } from 'react-router-dom';

import Head from '@/components/Head';
import { ConfirmationModal } from '@/pages/RestoreFromBackup/ConfirmationModal';
import styles from '@/pages/RestoreFromBackup/index.module.css';
import { Debounce } from '@/services/helpers/debounce';
import { buildWorkspacesLocation } from '@/services/helpers/location';
import { AppDispatch, RootState } from '@/store';
import { fetchBackupList, validateBackupImage } from '@/store/Backups/actions';
import { selectNamespaceBackups } from '@/store/Backups/selectors';
import { selectDefaultNamespace } from '@/store/InfrastructureNamespaces/selectors';

export type RestoreMode = 'same-cluster' | 'cross-cluster';

export type ValidationState = 'idle' | 'validating' | 'valid' | 'invalid';

const WORKSPACE_NAME_PATTERN = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
const IMAGE_URL_PATTERN =
  /^[a-zA-Z0-9][a-zA-Z0-9._-]*(?::[0-9]+)?\/[a-zA-Z0-9._/-]+(?::[a-zA-Z0-9._-]+)?$/;

type MappedProps = ConnectedProps<typeof connector>;

type Props = MappedProps & {
  navigate: NavigateFunction;
  initialBackupImageUrl?: string;
};

type State = {
  restoreMode: RestoreMode;
  workspaceName: string;
  workspaceNameValidated: ValidatedOptions;
  workspaceNameError: string;
  selectedBackup: BackupItem | undefined;
  isBackupSelectOpen: boolean;
  imageUrl: string;
  imageUrlValidated: ValidatedOptions;
  imageUrlError: string;
  validationState: ValidationState;
  validationResult: BackupValidationResult | undefined;
  isConfirmModalOpen: boolean;
  isSubmitting: boolean;
  submitError: string;
};

export class RestoreFromBackupPage extends React.PureComponent<Props, State> {
  private debounce: Debounce;
  private debounceHandler: () => void;

  constructor(props: Props) {
    super(props);

    this.debounce = new Debounce();
    this.debounceHandler = () => {
      this.performValidation();
    };
    this.debounce.subscribe(this.debounceHandler);

    const hasInitialImage = !!props.initialBackupImageUrl;

    this.state = {
      restoreMode: hasInitialImage ? 'cross-cluster' : 'same-cluster',
      workspaceName: '',
      workspaceNameValidated: ValidatedOptions.default,
      workspaceNameError: '',
      selectedBackup: undefined,
      isBackupSelectOpen: false,
      imageUrl: hasInitialImage ? props.initialBackupImageUrl! : '',
      imageUrlValidated: ValidatedOptions.default,
      imageUrlError: '',
      validationState: 'idle',
      validationResult: undefined,
      isConfirmModalOpen: false,
      isSubmitting: false,
      submitError: '',
    };
  }

  public componentDidMount(): void {
    const { defaultNamespace } = this.props;
    const namespace = defaultNamespace.name;
    if (namespace) {
      this.props.fetchBackupList({ namespace });
    }

    if (this.props.initialBackupImageUrl) {
      this.setState({ validationState: 'validating' });
      this.debounce.execute();
    }
  }

  public componentWillUnmount(): void {
    this.debounceHandler && this.debounce.unsubscribe(this.debounceHandler);
  }

  private getRegistryUrl(): string {
    const { defaultNamespace } = this.props;
    const namespace = defaultNamespace.name || 'default';
    return `image-registry.openshift-image-registry.svc:5000/${namespace}`;
  }

  private getResolvedImageUrl(): string {
    const { restoreMode, workspaceName, imageUrl, selectedBackup } = this.state;

    if (restoreMode === 'cross-cluster') {
      return imageUrl;
    }

    if (selectedBackup) {
      return selectedBackup.imageUrl;
    }

    if (workspaceName) {
      return `${this.getRegistryUrl()}/${workspaceName}:latest`;
    }

    return '';
  }

  private getResolvedWorkspaceName(): string {
    const { restoreMode, workspaceName, selectedBackup, validationResult } = this.state;

    if (restoreMode === 'same-cluster') {
      return selectedBackup?.workspaceName || workspaceName;
    }

    return validationResult?.metadata?.workspaceName || '';
  }

  private sanitizeWorkspaceName(value: string): string {
    return value.toLowerCase().replace(/[^a-z0-9-]/g, '');
  }

  private sanitizeImageUrl(value: string): string {
    return value.replace(/[<>"'`;|&$]/g, '');
  }

  private validateWorkspaceName(name: string): { validated: ValidatedOptions; error: string } {
    if (!name) {
      return { validated: ValidatedOptions.default, error: '' };
    }
    if (name.length > 63) {
      return {
        validated: ValidatedOptions.error,
        error: 'Workspace name must be 63 characters or less.',
      };
    }
    if (!WORKSPACE_NAME_PATTERN.test(name)) {
      return {
        validated: ValidatedOptions.error,
        error:
          'Must contain only lowercase letters, numbers, and hyphens. Must start and end with a letter or number.',
      };
    }
    return { validated: ValidatedOptions.success, error: '' };
  }

  private validateImageUrlFormat(url: string): { validated: ValidatedOptions; error: string } {
    if (!url) {
      return { validated: ValidatedOptions.default, error: '' };
    }
    if (!IMAGE_URL_PATTERN.test(url)) {
      return {
        validated: ValidatedOptions.error,
        error: 'Invalid image URL format. Expected: registry/repository:tag',
      };
    }
    return { validated: ValidatedOptions.default, error: '' };
  }

  private handleModeChange(mode: RestoreMode): void {
    this.setState({
      restoreMode: mode,
      workspaceName: '',
      workspaceNameValidated: ValidatedOptions.default,
      workspaceNameError: '',
      selectedBackup: undefined,
      isBackupSelectOpen: false,
      imageUrl: '',
      imageUrlValidated: ValidatedOptions.default,
      imageUrlError: '',
      validationState: 'idle',
      validationResult: undefined,
    });
  }

  private handleWorkspaceNameChange(value: string): void {
    const sanitized = this.sanitizeWorkspaceName(value);
    const { validated, error } = this.validateWorkspaceName(sanitized);
    this.setState({
      workspaceName: sanitized,
      workspaceNameValidated: validated,
      workspaceNameError: error,
      selectedBackup: undefined,
    });
  }

  private handleBackupSelect(
    _event: React.MouseEvent | React.ChangeEvent,
    selection: string,
  ): void {
    const backup = this.props.backups.find(b => b.imageUrl === selection);
    if (backup) {
      this.setState({
        selectedBackup: backup,
        workspaceName: backup.workspaceName,
        workspaceNameValidated: ValidatedOptions.success,
        workspaceNameError: '',
        isBackupSelectOpen: false,
      });
    }
  }

  private handleBackupSelectToggle(isOpen: boolean): void {
    this.setState({ isBackupSelectOpen: isOpen });
  }

  private handleImageUrlChange(value: string): void {
    const sanitized = this.sanitizeImageUrl(value);
    const { validated, error } = this.validateImageUrlFormat(sanitized);

    this.setState({
      imageUrl: sanitized,
      imageUrlValidated: validated,
      imageUrlError: error,
      validationState: 'idle',
      validationResult: undefined,
    });

    if (validated !== ValidatedOptions.error && sanitized) {
      this.setState({ validationState: 'validating' });
      this.debounce.execute();
    }
  }

  private async performValidation(): Promise<void> {
    const { imageUrl } = this.state;
    const { defaultNamespace } = this.props;
    const namespace = defaultNamespace.name || 'default';

    if (!imageUrl) {
      this.setState({ validationState: 'idle' });
      return;
    }

    try {
      const result = await this.props.validateBackupImage({ namespace, imageUrl });
      const payload = result.payload as BackupValidationResult;

      if (payload.valid && payload.accessible) {
        this.setState({
          validationState: 'valid',
          validationResult: payload,
          imageUrlValidated: ValidatedOptions.success,
          imageUrlError: '',
        });
      } else {
        this.setState({
          validationState: 'invalid',
          validationResult: payload,
          imageUrlValidated: ValidatedOptions.error,
          imageUrlError: payload.error || 'Backup image is not accessible.',
        });
      }
    } catch {
      this.setState({
        validationState: 'invalid',
        validationResult: undefined,
        imageUrlValidated: ValidatedOptions.error,
        imageUrlError: 'Failed to validate backup image.',
      });
    }
  }

  private handleCancel(): void {
    const location = buildWorkspacesLocation();
    this.props.navigate(location);
  }

  private handleRestoreClick(): void {
    this.setState({ isConfirmModalOpen: true });
  }

  private handleConfirmCancel(): void {
    this.setState({ isConfirmModalOpen: false });
  }

  private async handleConfirmRestore(): Promise<void> {
    this.setState({ isConfirmModalOpen: false, isSubmitting: true, submitError: '' });

    try {
      // Navigate to factory loader with restore attributes
      const imageUrl = this.getResolvedImageUrl();
      const workspaceName = this.getResolvedWorkspaceName();
      const factoryUrl = `/load-factory?restoreFromBackup=true&backupImageUrl=${encodeURIComponent(imageUrl)}`;
      if (workspaceName) {
        this.props.navigate(`${factoryUrl}&name=${encodeURIComponent(workspaceName)}`);
      } else {
        this.props.navigate(factoryUrl);
      }
    } catch (e: unknown) {
      const errorMessage = e instanceof Error ? e.message : 'Failed to initiate restore.';
      this.setState({ isSubmitting: false, submitError: errorMessage });
    }
  }

  private isRestoreEnabled(): boolean {
    const { restoreMode, workspaceNameValidated, validationState, isSubmitting } = this.state;

    if (isSubmitting) {
      return false;
    }

    if (restoreMode === 'same-cluster') {
      return workspaceNameValidated === ValidatedOptions.success;
    }

    return validationState === 'valid';
  }

  private renderValidationStatus(): React.ReactElement | null {
    const { validationState, validationResult } = this.state;

    switch (validationState) {
      case 'validating':
        return (
          <HelperText>
            <HelperTextItem variant="indeterminate" hasIcon>
              <span className={styles.validationIcon}>
                <Spinner size="sm" aria-label="Validating backup image" />
                Validating backup image...
              </span>
            </HelperTextItem>
          </HelperText>
        );
      case 'valid':
        return (
          <HelperText>
            <HelperTextItem variant="success" hasIcon icon={<CheckCircleIcon />}>
              Backup image is valid and accessible
              {validationResult?.metadata && (
                <> &mdash; {validationResult.metadata.workspaceName}</>
              )}
            </HelperTextItem>
          </HelperText>
        );
      case 'invalid':
        return null;
      default:
        return null;
    }
  }

  private renderSameClusterFields(): React.ReactElement {
    const {
      workspaceName,
      workspaceNameValidated,
      workspaceNameError,
      selectedBackup,
      isBackupSelectOpen,
    } = this.state;
    const { backups } = this.props;
    const imagePreview = this.getResolvedImageUrl();

    return (
      <div className={styles.formFields}>
        {backups.length > 0 && (
          <FormGroup fieldId="restore-backup-select" label="Select a backup">
            <Select
              variant={SelectVariant.single}
              placeholderText="Select a backup to restore"
              aria-label="Select a backup"
              isOpen={isBackupSelectOpen}
              onToggle={isOpen => this.handleBackupSelectToggle(isOpen)}
              onSelect={(event, selection) =>
                this.handleBackupSelect(event as React.MouseEvent, selection as string)
              }
              selections={selectedBackup?.imageUrl}
              data-testid="backup-select"
            >
              {backups.map(backup => (
                <SelectOption key={backup.imageUrl} value={backup.imageUrl}>
                  {backup.workspaceName}
                  {backup.workspaceExists ? ' (Active)' : ' (Deleted)'}
                </SelectOption>
              ))}
            </Select>
          </FormGroup>
        )}

        <FormGroup
          fieldId="restore-workspace-name"
          label="Workspace name"
          isRequired
          helperText="Enter the name of the workspace to restore."
          helperTextInvalid={workspaceNameError}
          helperTextInvalidIcon={<ExclamationCircleIcon />}
          validated={workspaceNameValidated}
        >
          <TextInput
            id="restore-workspace-name"
            aria-label="Workspace name"
            placeholder="my-workspace"
            value={workspaceName}
            validated={workspaceNameValidated}
            onChange={value => this.handleWorkspaceNameChange(value)}
          />
        </FormGroup>

        {imagePreview && (
          <FormGroup fieldId="restore-image-preview" label="Backup image URL">
            <div className={styles.imagePreview} data-testid="image-preview">
              {imagePreview}
            </div>
            <HelperText>
              <HelperTextItem>
                This URL will be used to locate the backup image in the cluster registry.
              </HelperTextItem>
            </HelperText>
          </FormGroup>
        )}
      </div>
    );
  }

  private renderCrossClusterFields(): React.ReactElement {
    const { imageUrl, imageUrlValidated, imageUrlError } = this.state;

    return (
      <div className={styles.formFields}>
        <FormGroup
          fieldId="restore-image-url"
          label="Backup image URL"
          isRequired
          helperText="Enter the full URL of the backup image from the source cluster."
          helperTextInvalid={imageUrlError}
          helperTextInvalidIcon={<ExclamationCircleIcon />}
          validated={imageUrlValidated}
        >
          <TextInput
            id="restore-image-url"
            aria-label="Backup image URL"
            placeholder="registry.example.com/namespace/workspace:latest"
            value={imageUrl}
            validated={imageUrlValidated}
            onChange={value => this.handleImageUrlChange(value)}
          />
        </FormGroup>

        <div aria-live="polite" aria-atomic="true">
          {this.renderValidationStatus()}
        </div>

        <HelperText>
          <HelperTextItem>Format: registry-host/namespace/workspace-name:tag</HelperTextItem>
        </HelperText>
      </div>
    );
  }

  public render(): React.ReactElement {
    const { restoreMode, isConfirmModalOpen, isSubmitting, submitError } = this.state;

    return (
      <React.Fragment>
        <Head pageName="Restore from Backup" />

        <PageSection variant={PageSectionVariants.light}>
          <Title headingLevel="h1">Restore from Backup</Title>
        </PageSection>

        <Divider />

        <PageSection variant={PageSectionVariants.default}>
          {submitError && (
            <Alert
              variant={AlertVariant.danger}
              title="Restore failed"
              isInline
              data-testid="restore-error-alert"
            >
              {submitError}
            </Alert>
          )}

          <div className={styles.restoreForm} data-testid="restore-from-backup-page">
            <div className={styles.radioGroup}>
              <div className={styles.radioItem}>
                <Radio
                  id="restore-mode-same-cluster"
                  name="restore-mode"
                  label="Same cluster"
                  description="Restore a workspace from a backup on this cluster."
                  isChecked={restoreMode === 'same-cluster'}
                  onChange={() => this.handleModeChange('same-cluster')}
                />
              </div>
              <div className={styles.radioItem}>
                <Radio
                  id="restore-mode-cross-cluster"
                  name="restore-mode"
                  label="Cross cluster"
                  description="Restore from a backup image on a different cluster or registry."
                  isChecked={restoreMode === 'cross-cluster'}
                  onChange={() => this.handleModeChange('cross-cluster')}
                />
              </div>
            </div>

            {restoreMode === 'same-cluster'
              ? this.renderSameClusterFields()
              : this.renderCrossClusterFields()}

            <div className={styles.actionButtons}>
              <Button
                variant={ButtonVariant.primary}
                isDisabled={!this.isRestoreEnabled()}
                isLoading={isSubmitting}
                onClick={() => this.handleRestoreClick()}
                data-testid="restore-submit-button"
              >
                Restore Workspace
              </Button>
              <Button
                variant={ButtonVariant.link}
                onClick={() => this.handleCancel()}
                data-testid="restore-cancel-button"
              >
                Cancel
              </Button>
            </div>
          </div>
        </PageSection>

        <ConfirmationModal
          isOpen={isConfirmModalOpen}
          restoreMode={restoreMode}
          workspaceName={this.getResolvedWorkspaceName()}
          imageUrl={this.getResolvedImageUrl()}
          onConfirm={() => this.handleConfirmRestore()}
          onCancel={() => this.handleConfirmCancel()}
        />
      </React.Fragment>
    );
  }
}

const mapStateToProps = (state: RootState) => {
  const defaultNamespace = selectDefaultNamespace(state);
  const namespace = defaultNamespace.name;
  return {
    defaultNamespace,
    backups: selectNamespaceBackups(state, namespace),
  };
};

const mapDispatchToProps = (dispatch: AppDispatch) => ({
  validateBackupImage: (params: { namespace: string; imageUrl: string }) =>
    dispatch(validateBackupImage(params)),
  fetchBackupList: (params: { namespace: string }) => dispatch(fetchBackupList(params)),
});

const connector = connect(mapStateToProps, mapDispatchToProps);

export default connector(RestoreFromBackupPage);
