/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupStatus } from '@eclipse-che/common';
import { AnyAction } from 'redux';
import { ThunkDispatch } from 'redux-thunk';

import {
  fetchBackupList,
  fetchWorkspaceBackupStatus,
  validateBackupImage,
} from '@/store/Backups/actions';
import { unloadedState } from '@/store/Backups/reducer';
import { RootState } from '@/store';

// Mock axios
jest.mock('axios');
import axios from 'axios';
const mockedAxios = axios as jest.Mocked<typeof axios>;

describe('Backup Actions', () => {
  let dispatch: ThunkDispatch<RootState, undefined, AnyAction>;
  let getState: () => RootState;

  beforeEach(() => {
    dispatch = jest.fn((action: any) => {
      if (typeof action === 'function') {
        return action(dispatch, getState, undefined);
      }
      return Promise.resolve(action);
    }) as any;

    getState = jest.fn(() => ({
      backups: unloadedState,
    })) as any;

    jest.clearAllMocks();
  });

  describe('fetchWorkspaceBackupStatus', () => {
    const namespace = 'user-che';
    const workspaceName = 'my-workspace';
    const workspaceUID = 'workspace-123';

    it('should fetch workspace backup status successfully', async () => {
      const mockBackupInfo = {
        status: BackupStatus.SUCCESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
        backupImageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
        sizeBytes: 1024000,
      };

      mockedAxios.get.mockResolvedValueOnce({ data: mockBackupInfo });

      const result = await dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(mockedAxios.get).toHaveBeenCalledWith(
        `/api/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`,
      );
      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/fulfilled');
      expect(result.payload).toEqual(mockBackupInfo);
    });

    it('should handle successful fetch with NEVER status', async () => {
      const mockBackupInfo = {
        status: BackupStatus.NEVER,
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
      };

      mockedAxios.get.mockResolvedValueOnce({ data: mockBackupInfo });

      const result = await dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.payload).toEqual(mockBackupInfo);
      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/fulfilled');
    });

    it('should handle API error with error message', async () => {
      const errorMessage = 'Workspace not found';
      mockedAxios.get.mockRejectedValueOnce({
        response: {
          data: {
            message: errorMessage,
          },
        },
      });

      const result = await dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/rejected');
      expect(result.payload).toBe(errorMessage);
    });

    it('should handle network error without response', async () => {
      mockedAxios.get.mockRejectedValueOnce(new Error('Network error'));

      const result = await dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/rejected');
      expect(result.payload).toBe('Failed to fetch backup status');
    });

    it('should handle IN_PROGRESS status', async () => {
      const mockBackupInfo = {
        status: BackupStatus.IN_PROGRESS,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
        backupImageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
      };

      mockedAxios.get.mockResolvedValueOnce({ data: mockBackupInfo });

      const result = await dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.payload).toEqual(mockBackupInfo);
    });

    it('should handle FAILED status with error', async () => {
      const mockBackupInfo = {
        status: BackupStatus.FAILED,
        lastBackupTime: '2026-02-10T12:00:00.000Z',
        nextScheduledBackup: '2026-02-11T12:00:00.000Z',
        error: 'Backup job failed: insufficient storage',
      };

      mockedAxios.get.mockResolvedValueOnce({ data: mockBackupInfo });

      const result = await dispatch(
        fetchWorkspaceBackupStatus({ namespace, workspaceUID, workspaceName }),
      );

      expect(result.payload).toEqual(mockBackupInfo);
      expect(result.type).toBe('backups/fetchWorkspaceBackupStatus/fulfilled');
      if (result.payload && typeof result.payload !== 'string') {
        expect(result.payload.error).toContain('insufficient storage');
      }
    });
  });

  describe('fetchBackupList', () => {
    const namespace = 'user-che';

    it('should fetch backup list successfully', async () => {
      const mockBackupItems = [
        {
          workspaceName: 'my-workspace',
          imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          workspaceExists: true,
          labels: {},
        },
        {
          workspaceName: 'other-workspace',
          imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/other-workspace:latest',
          timestamp: '2026-02-09T12:00:00.000Z',
          sizeBytes: 2048000,
          workspaceExists: false,
          labels: {},
        },
      ];

      mockedAxios.get.mockResolvedValueOnce({
        data: {
          backups: mockBackupItems,
          total: 2,
          page: 1,
          perPage: 50,
        },
      });

      const result = await dispatch(fetchBackupList({ namespace }));

      expect(mockedAxios.get).toHaveBeenCalledWith(
        `/api/namespace/${namespace}/backups`,
        {
          params: {
            workspaceName: undefined,
            page: undefined,
            perPage: undefined,
          },
        },
      );
      expect(result.type).toBe('backups/fetchBackupList/fulfilled');
      expect(result.payload).toEqual(mockBackupItems);
    });

    it('should fetch backup list with workspace name filter', async () => {
      const workspaceName = 'my-workspace';
      const mockBackupItems = [
        {
          workspaceName: 'my-workspace',
          imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          workspaceExists: true,
          labels: {},
        },
      ];

      mockedAxios.get.mockResolvedValueOnce({
        data: {
          backups: mockBackupItems,
          total: 1,
          page: 1,
          perPage: 50,
        },
      });

      const result = await dispatch(fetchBackupList({ namespace, workspaceName }));

      expect(mockedAxios.get).toHaveBeenCalledWith(
        `/api/namespace/${namespace}/backups`,
        {
          params: {
            workspaceName,
            page: undefined,
            perPage: undefined,
          },
        },
      );
      expect(result.payload).toHaveLength(1);
      if (result.payload && typeof result.payload !== 'string') {
        expect(result.payload[0].workspaceName).toBe(workspaceName);
      }
    });

    it('should fetch backup list with pagination parameters', async () => {
      const page = 2;
      const perPage = 10;
      const mockBackupItems = [
        {
          workspaceName: 'workspace-11',
          imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-che/workspace-11:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          workspaceExists: true,
          labels: {},
        },
      ];

      mockedAxios.get.mockResolvedValueOnce({
        data: {
          backups: mockBackupItems,
          total: 15,
          page,
          perPage,
        },
      });

      const result = await dispatch(fetchBackupList({ namespace, page, perPage }));

      expect(mockedAxios.get).toHaveBeenCalledWith(
        `/api/namespace/${namespace}/backups`,
        {
          params: {
            workspaceName: undefined,
            page,
            perPage,
          },
        },
      );
      expect(result.payload).toEqual(mockBackupItems);
    });

    it('should handle empty backup list', async () => {
      mockedAxios.get.mockResolvedValueOnce({
        data: {
          backups: [],
          total: 0,
          page: 1,
          perPage: 50,
        },
      });

      const result = await dispatch(fetchBackupList({ namespace }));

      expect(result.type).toBe('backups/fetchBackupList/fulfilled');
      expect(result.payload).toEqual([]);
    });

    it('should handle API error', async () => {
      const errorMessage = 'Namespace not found';
      mockedAxios.get.mockRejectedValueOnce({
        response: {
          data: {
            message: errorMessage,
          },
        },
      });

      const result = await dispatch(fetchBackupList({ namespace }));

      expect(result.type).toBe('backups/fetchBackupList/rejected');
      expect(result.payload).toBe(errorMessage);
    });

    it('should handle network error', async () => {
      mockedAxios.get.mockRejectedValueOnce(new Error('Network error'));

      const result = await dispatch(fetchBackupList({ namespace }));

      expect(result.type).toBe('backups/fetchBackupList/rejected');
      expect(result.payload).toBe('Failed to fetch backup list');
    });
  });

  describe('validateBackupImage', () => {
    const namespace = 'user-che';
    const imageUrl = 'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest';

    it('should validate accessible backup image successfully', async () => {
      const mockValidationResult = {
        valid: true,
        accessible: true,
        metadata: {
          workspaceName: 'my-workspace',
          namespace: 'user-che',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
        },
      };

      mockedAxios.post.mockResolvedValueOnce({ data: mockValidationResult });

      const result = await dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(mockedAxios.post).toHaveBeenCalledWith(
        `/api/namespace/${namespace}/backups/validate`,
        { imageUrl },
      );
      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
      expect(result.payload).toEqual(mockValidationResult);
    });

    it('should validate inaccessible backup image', async () => {
      const mockValidationResult = {
        valid: true,
        accessible: false,
      };

      mockedAxios.post.mockResolvedValueOnce({ data: mockValidationResult });

      const result = await dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.payload).toEqual(mockValidationResult);
      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
      if (result.payload && typeof result.payload !== 'string') {
        expect(result.payload.accessible).toBe(false);
        expect(result.payload.metadata).toBeUndefined();
      }
    });

    it('should handle invalid backup image format', async () => {
      const mockValidationResult = {
        valid: false,
        accessible: false,
        error: 'Invalid image URL format',
      };

      mockedAxios.post.mockResolvedValueOnce({ data: mockValidationResult });

      const result = await dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.payload).toEqual(mockValidationResult);
      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
      if (result.payload && typeof result.payload !== 'string') {
        expect(result.payload.valid).toBe(false);
        expect(result.payload.error).toContain('Invalid image URL format');
      }
    });

    it('should handle API error', async () => {
      const errorMessage = 'Image not found';
      mockedAxios.post.mockRejectedValueOnce({
        response: {
          data: {
            message: errorMessage,
          },
        },
      });

      const result = await dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.type).toBe('backups/validateBackupImage/rejected');
      expect(result.payload).toBe(errorMessage);
    });

    it('should handle network error', async () => {
      mockedAxios.post.mockRejectedValueOnce(new Error('Network error'));

      const result = await dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.type).toBe('backups/validateBackupImage/rejected');
      expect(result.payload).toBe('Failed to validate backup image');
    });

    it('should handle timeout error', async () => {
      const mockValidationResult = {
        valid: false,
        accessible: false,
        error: 'Registry query timed out while validating image',
      };

      mockedAxios.post.mockResolvedValueOnce({ data: mockValidationResult });

      const result = await dispatch(validateBackupImage({ namespace, imageUrl }));

      expect(result.type).toBe('backups/validateBackupImage/fulfilled');
      if (result.payload && typeof result.payload !== 'string') {
        expect(result.payload.error).toContain('timed out');
      }
    });
  });
});
