/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupStatus } from '@eclipse-che/common';
import { UnknownAction } from 'redux';

import { reducer, State, unloadedState } from '@/store/Backups/reducer';

describe('Backups, reducer', () => {
  let initialState: State;

  beforeEach(() => {
    initialState = { ...unloadedState };
  });

  it('should return initial state', () => {
    expect(unloadedState).toEqual({
      byWorkspace: {},
      byNamespace: {},
      loading: {
        isLoading: false,
        isUpdating: false,
        isValidating: false,
      },
      error: undefined,
    });
  });

  it('should return the current state for unknown actions', () => {
    const unknownAction = { type: 'UNKNOWN_ACTION' } as UnknownAction;
    expect(reducer(initialState, unknownAction)).toEqual(initialState);
  });

  it('should preserve initial state structure', () => {
    const state = reducer(undefined, { type: '@@INIT' } as UnknownAction);
    expect(state).toHaveProperty('byWorkspace');
    expect(state).toHaveProperty('byNamespace');
    expect(state).toHaveProperty('loading');
    expect(state).toHaveProperty('error');
  });

  it('should have properly typed loading state', () => {
    expect(initialState.loading).toHaveProperty('isLoading');
    expect(initialState.loading).toHaveProperty('isUpdating');
    expect(initialState.loading).toHaveProperty('isValidating');
    expect(typeof initialState.loading.isLoading).toBe('boolean');
    expect(typeof initialState.loading.isUpdating).toBe('boolean');
    expect(typeof initialState.loading.isValidating).toBe('boolean');
  });

  it('should initialize with empty byWorkspace map', () => {
    expect(initialState.byWorkspace).toEqual({});
    expect(Object.keys(initialState.byWorkspace)).toHaveLength(0);
  });

  it('should initialize with empty byNamespace map', () => {
    expect(initialState.byNamespace).toEqual({});
    expect(Object.keys(initialState.byNamespace)).toHaveLength(0);
  });

  it('should initialize with no error', () => {
    expect(initialState.error).toBeUndefined();
  });

  it('should initialize with all loading states false', () => {
    expect(initialState.loading.isLoading).toBe(false);
    expect(initialState.loading.isUpdating).toBe(false);
    expect(initialState.loading.isValidating).toBe(false);
  });

  describe('State structure validation', () => {
    it('should maintain immutability for unknown actions', () => {
      const stateBefore = { ...initialState };
      const unknownAction = { type: 'UNKNOWN_ACTION' } as UnknownAction;
      const stateAfter = reducer(initialState, unknownAction);

      expect(stateAfter).toEqual(stateBefore);
      expect(stateAfter).toBe(initialState); // Should return same reference
    });

    it('should allow byWorkspace to be typed correctly', () => {
      // TypeScript compilation test - if this compiles, types are correct
      const testState: State = {
        byWorkspace: {
          'workspace-uid-1': {
            status: BackupStatus.SUCCESS,
            lastBackupTime: '2026-02-10T12:00:00.000Z',
            nextScheduledBackup: '2026-02-11T12:00:00.000Z',
            backupImageUrl: 'registry.example.com/namespace/workspace:latest',
            sizeBytes: 1024,
          },
        },
        byNamespace: {},
        loading: {
          isLoading: false,
          isUpdating: false,
          isValidating: false,
        },
        error: undefined,
      };

      expect(testState.byWorkspace['workspace-uid-1'].status).toBe(BackupStatus.SUCCESS);
    });

    it('should allow byNamespace to be typed correctly', () => {
      // TypeScript compilation test - if this compiles, types are correct
      const testState: State = {
        byWorkspace: {},
        byNamespace: {
          'user-che': [
            {
              workspaceName: 'my-workspace',
              imageUrl: 'registry.example.com/user-che/my-workspace:latest',
              timestamp: '2026-02-10T12:00:00.000Z',
              sizeBytes: 2048,
              workspaceExists: true,
              labels: { 'backup.timestamp': '2026-02-10T12:00:00.000Z' },
            },
          ],
        },
        loading: {
          isLoading: false,
          isUpdating: false,
          isValidating: false,
        },
        error: undefined,
      };

      expect(testState.byNamespace['user-che']).toHaveLength(1);
      expect(testState.byNamespace['user-che'][0].workspaceName).toBe('my-workspace');
    });
  });

  describe('Future async thunk actions (Task #11)', () => {
    it('should be ready to handle fetchBackupStatus actions', () => {
      // Placeholder test - will be implemented in Task #11
      // This ensures the reducer structure is ready for async thunks
      expect(reducer).toBeDefined();
      expect(typeof reducer).toBe('function');
    });

    it('should be ready to handle fetchBackupList actions', () => {
      // Placeholder test - will be implemented in Task #11
      expect(reducer).toBeDefined();
    });

    it('should be ready to handle validateBackupImage actions', () => {
      // Placeholder test - will be implemented in Task #11
      expect(reducer).toBeDefined();
    });
  });
});
