/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

describe('Backup Configuration Environment Variables', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    jest.resetModules();
    process.env = { ...originalEnv };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  describe('backupRegistryAdapter', () => {
    it('should use default value "openshift" when env var not set', () => {
      delete process.env.BACKUP_REGISTRY_ADAPTER;
      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('openshift');
    });

    it('should accept valid value "docker"', () => {
      process.env.BACKUP_REGISTRY_ADAPTER = 'docker';
      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('docker');
    });

    it('should accept valid value "custom"', () => {
      process.env.BACKUP_REGISTRY_ADAPTER = 'custom';
      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('custom');
    });

    it('should fall back to default for invalid value', () => {
      process.env.BACKUP_REGISTRY_ADAPTER = 'invalid-adapter';
      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('openshift');
    });

    it('should fall back to default for empty string', () => {
      process.env.BACKUP_REGISTRY_ADAPTER = '';
      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('openshift');
    });
  });

  describe('backupListPageSize', () => {
    it('should use default value 50 when env var not set', () => {
      delete process.env.BACKUP_LIST_PAGE_SIZE;
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });

    it('should accept valid value within range (1)', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '1';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(1);
    });

    it('should accept valid value within range (100)', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '100';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(100);
    });

    it('should accept valid value within range (25)', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '25';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(25);
    });

    it('should fall back to default for value below minimum (0)', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '0';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });

    it('should fall back to default for value above maximum (101)', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '101';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });

    it('should fall back to default for negative value', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '-10';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });

    it('should fall back to default for non-numeric value', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = 'not-a-number';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });

    it('should fall back to default for empty string', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });

    it('should fall back to default for floating point value', () => {
      process.env.BACKUP_LIST_PAGE_SIZE = '50.5';
      const config = require('../config');
      expect(config.backupListPageSize).toBe(50);
    });
  });

  describe('backupRegistryTimeout', () => {
    it('should use default value 30 when env var not set', () => {
      delete process.env.BACKUP_REGISTRY_TIMEOUT;
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(30);
    });

    it('should accept valid value within range (10)', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = '10';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(10);
    });

    it('should accept valid value within range (300)', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = '300';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(300);
    });

    it('should accept valid value within range (60)', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = '60';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(60);
    });

    it('should fall back to default for value below minimum (9)', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = '9';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(30);
    });

    it('should fall back to default for value above maximum (301)', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = '301';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(30);
    });

    it('should fall back to default for negative value', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = '-30';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(30);
    });

    it('should fall back to default for non-numeric value', () => {
      process.env.BACKUP_REGISTRY_TIMEOUT = 'invalid';
      const config = require('../config');
      expect(config.backupRegistryTimeout).toBe(30);
    });
  });

  describe('backupCacheTTL', () => {
    it('should use default value 300 when env var not set', () => {
      delete process.env.BACKUP_CACHE_TTL;
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(300);
    });

    it('should accept valid value within range (60)', () => {
      process.env.BACKUP_CACHE_TTL = '60';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(60);
    });

    it('should accept valid value within range (3600)', () => {
      process.env.BACKUP_CACHE_TTL = '3600';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(3600);
    });

    it('should accept valid value within range (600)', () => {
      process.env.BACKUP_CACHE_TTL = '600';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(600);
    });

    it('should fall back to default for value below minimum (59)', () => {
      process.env.BACKUP_CACHE_TTL = '59';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(300);
    });

    it('should fall back to default for value above maximum (3601)', () => {
      process.env.BACKUP_CACHE_TTL = '3601';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(300);
    });

    it('should fall back to default for negative value', () => {
      process.env.BACKUP_CACHE_TTL = '-100';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(300);
    });

    it('should fall back to default for non-numeric value', () => {
      process.env.BACKUP_CACHE_TTL = 'abc';
      const config = require('../config');
      expect(config.backupCacheTTL).toBe(300);
    });
  });

  describe('Multiple environment variables', () => {
    it('should handle all valid custom values simultaneously', () => {
      process.env.BACKUP_REGISTRY_ADAPTER = 'docker';
      process.env.BACKUP_LIST_PAGE_SIZE = '75';
      process.env.BACKUP_REGISTRY_TIMEOUT = '120';
      process.env.BACKUP_CACHE_TTL = '1800';

      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('docker');
      expect(config.backupListPageSize).toBe(75);
      expect(config.backupRegistryTimeout).toBe(120);
      expect(config.backupCacheTTL).toBe(1800);
    });

    it('should use defaults for all when none are set', () => {
      delete process.env.BACKUP_REGISTRY_ADAPTER;
      delete process.env.BACKUP_LIST_PAGE_SIZE;
      delete process.env.BACKUP_REGISTRY_TIMEOUT;
      delete process.env.BACKUP_CACHE_TTL;

      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('openshift');
      expect(config.backupListPageSize).toBe(50);
      expect(config.backupRegistryTimeout).toBe(30);
      expect(config.backupCacheTTL).toBe(300);
    });

    it('should handle mix of valid and invalid values', () => {
      process.env.BACKUP_REGISTRY_ADAPTER = 'custom';
      process.env.BACKUP_LIST_PAGE_SIZE = '200'; // invalid - out of range
      process.env.BACKUP_REGISTRY_TIMEOUT = '150'; // valid
      process.env.BACKUP_CACHE_TTL = 'invalid'; // invalid - not a number

      const config = require('../config');
      expect(config.backupRegistryAdapter).toBe('custom');
      expect(config.backupListPageSize).toBe(50); // default
      expect(config.backupRegistryTimeout).toBe(150);
      expect(config.backupCacheTTL).toBe(300); // default
    });
  });

  describe('Backward compatibility', () => {
    it('should maintain existing behavior when env vars not set', () => {
      delete process.env.BACKUP_REGISTRY_ADAPTER;
      delete process.env.BACKUP_LIST_PAGE_SIZE;
      delete process.env.BACKUP_REGISTRY_TIMEOUT;
      delete process.env.BACKUP_CACHE_TTL;

      const config = require('../config');

      // Defaults match the original hardcoded values from common package
      expect(config.backupListPageSize).toBe(50);
      expect(config.backupRegistryTimeout).toBe(30);
      expect(config.backupCacheTTL).toBe(300);
    });
  });
});
