/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import {
  BACKUP_ERROR_CODES,
  BACKUP_IMAGE_DEFAULT_TAG,
  BackupItem,
  BackupListResponse,
  BackupValidationResult,
  DEVWORKSPACE_BACKUP_ANNOTATIONS,
} from '@eclipse-che/common';
import { KubeConfig } from '@kubernetes/client-node';
import { CustomObjectsApi } from '@kubernetes/client-node';

import { backupCacheTTL, backupRegistryTimeout } from '@/constants/config';
import { createError } from '@/devworkspaceClient/services/helpers/createError';
import { IRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters';

// DevWorkspaceOperatorConfig constants
const DWOC_GROUP = 'controller.devfile.io';
const DWOC_VERSION = 'v1alpha1';
const DWOC_PLURAL = 'devworkspaceoperatorconfigs';
const DWOC_NAME = 'devworkspace-operator-config';
const DWOC_NAMESPACE = 'openshift-operators';

// DevWorkspace constants
const DEVWORKSPACE_GROUP = 'workspace.devfile.io';
const DEVWORKSPACE_VERSION = 'v1alpha2';
const DEVWORKSPACE_PLURAL = 'devworkspaces';

/**
 * Validates Kubernetes DNS-1123 subdomain naming convention
 * Rules: lowercase alphanumeric, hyphens allowed, max 63 chars
 * Must start/end with alphanumeric character
 *
 * SECURITY: Prevents cache key injection attacks
 */
function validateK8sName(name: string, fieldName: string): void {
  const dns1123Pattern = /^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/;

  if (!name || name.length === 0) {
    throw createError(
      new Error('Empty name'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} cannot be empty`,
    );
  }

  if (name.length > 63) {
    throw createError(
      new Error('Name too long'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} exceeds maximum length of 63 characters`,
    );
  }

  if (!dns1123Pattern.test(name)) {
    throw createError(
      new Error('Invalid name format'),
      BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      `${fieldName} must follow Kubernetes DNS-1123 naming convention: lowercase alphanumeric characters or '-', must start and end with alphanumeric`,
    );
  }
}

/**
 * Cache entry with TTL tracking
 * Used for namespace-scoped caching with expiration logic
 */
class CacheEntry<T> {
  constructor(
    public data: T,
    public timestamp: number,
    public ttlSeconds: number,
  ) {}

  isExpired(): boolean {
    return (Date.now() - this.timestamp) / 1000 > this.ttlSeconds;
  }
}

/**
 * Registry API Service with namespace-scoped caching
 *
 * Provides high-level operations for backup image discovery and validation
 * with built-in caching, timeout protection, and security validations.
 *
 * SECURITY FEATURES:
 * - Namespace-scoped cache keys (prevents cross-namespace data leakage)
 * - K8s DNS-1123 validation (prevents cache key injection)
 * - No error caching (ensures fresh security checks on retry)
 * - Defense-in-depth validation (input → cache → data → caching)
 */
export class RegistryApiService {
  private adapter: IRegistryAdapter;
  private cache: Map<string, CacheEntry<unknown>>;
  private customObjectsApi: CustomObjectsApi;

  constructor(kubeConfig: KubeConfig, adapter: IRegistryAdapter) {
    this.adapter = adapter;
    this.cache = new Map();
    this.customObjectsApi = kubeConfig.makeApiClient(CustomObjectsApi);
  }

  /**
   * Generates namespace-scoped cache key
   * Format: ${namespace}:${operation}:${id?}
   *
   * SECURITY: Namespace-scoped to prevent cross-tenant data leakage
   */
  private getCacheKey(namespace: string, operation: string, id?: string): string {
    if (id) {
      return `${namespace}:${operation}:${id}`;
    }
    return `${namespace}:${operation}`;
  }

  /**
   * Retrieves cached data if not expired
   * Returns undefined if cache miss or expired
   */
  private getFromCache<T>(key: string): T | undefined {
    const entry = this.cache.get(key) as CacheEntry<T> | undefined;

    if (!entry) {
      return undefined;
    }

    if (entry.isExpired()) {
      this.cache.delete(key);
      return undefined;
    }

    return entry.data;
  }

  /**
   * Stores data in cache with TTL
   */
  private setCache<T>(key: string, data: T, ttlSeconds: number): void {
    const entry = new CacheEntry(data, Date.now(), ttlSeconds);
    this.cache.set(key, entry);
  }

  /**
   * Check if a DevWorkspace exists in the namespace
   */
  private async doesWorkspaceExist(namespace: string, workspaceName: string): Promise<boolean> {
    try {
      await this.customObjectsApi.getNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
        name: workspaceName,
      });
      return true;
    } catch (e) {
      // Handle both old HttpError (response.statusCode) and new ApiException (code) formats
      const statusCode = (e as any)?.response?.statusCode ?? (e as any)?.code;
      if (statusCode === 404) {
        return false;
      }
      // On error, assume workspace exists (fail-safe)
      return true;
    }
  }

  /**
   * Get backup registry path from DevWorkspaceOperatorConfig
   * Returns the configured registry path for backup images
   */
  private async getBackupRegistryPath(): Promise<string> {
    try {
      const response = await this.customObjectsApi.getNamespacedCustomObject({
        group: DWOC_GROUP,
        version: DWOC_VERSION,
        namespace: DWOC_NAMESPACE,
        plural: DWOC_PLURAL,
        name: DWOC_NAME,
      });

      const operatorConfig = (response as any).body || response;
      const registryPath = operatorConfig.config?.workspace?.backupCronJob?.registry?.path;

      if (!registryPath) {
        throw new Error('Backup registry path not configured');
      }

      return registryPath;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        'Unable to get backup registry configuration',
      );
    }
  }

  /**
   * List DevWorkspaces with backup annotations in the namespace
   * Returns workspaces that have been backed up at least once
   */
  private async listDevWorkspacesWithBackups(namespace: string): Promise<any[]> {
    try {
      const response = await this.customObjectsApi.listNamespacedCustomObject({
        group: DEVWORKSPACE_GROUP,
        version: DEVWORKSPACE_VERSION,
        namespace,
        plural: DEVWORKSPACE_PLURAL,
      });

      const devworkspaces = (response as unknown as { items: any[] }).items;

      // Filter for workspaces with backup annotations
      return devworkspaces.filter(dw => {
        const annotations = dw.metadata?.annotations || {};
        return annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT];
      });
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list DevWorkspaces in namespace ${namespace}`,
      );
    }
  }

  /**
   * Build BackupItem from DevWorkspace annotations
   * Used for external registry backups where ImageStream is not available
   */
  private buildBackupItemFromAnnotations(
    devworkspace: any,
    registryPath: string,
    namespace: string,
  ): BackupItem {
    const workspaceName = devworkspace.metadata.name;
    const annotations = devworkspace.metadata.annotations || {};

    // Construct image URL: registry/namespace/workspace:tag
    const imageUrl = `${registryPath}/${namespace}/${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`;

    // Populate labels with backup-relevant DevWorkspace annotations
    // so the frontend can derive backup status from them
    const backupLabels: Record<string, string> = {};
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
    }
    if (annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
      backupLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
        annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
    }

    return {
      workspaceName,
      imageUrl,
      timestamp: annotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_FINISHED_AT],
      sizeBytes: 0, // Unknown for external registry
      workspaceExists: true, // DevWorkspace exists (we're querying it)
      labels: backupLabels,
    };
  }

  /**
   * Lists backup images for a namespace, optionally filtered by workspace name
   *
   * @param namespace - Kubernetes namespace (validated against DNS-1123)
   * @param workspaceName - Optional DevWorkspace name filter (validated against DNS-1123)
   * @returns List of all backup images with metadata
   *
   * CACHING: Results cached for 5 minutes per namespace (not per workspace)
   * TIMEOUT: 10-second timeout with fallback to cached results
   */
  async listBackupImages(
    namespace: string,
    workspaceName?: string,
  ): Promise<BackupListResponse> {
    // SECURITY: Validate K8s naming convention
    validateK8sName(namespace, 'namespace');
    if (workspaceName) {
      validateK8sName(workspaceName, 'workspaceName');
    }

    const cacheKey = this.getCacheKey(namespace, 'listBackupImages');
    const cached = this.getFromCache<BackupItem[]>(cacheKey);

    if (cached) {
      // Filter by workspace name if provided
      let filteredBackups = cached;
      if (workspaceName) {
        filteredBackups = cached.filter(backup => backup.workspaceName === workspaceName);
      }

      return {
        backups: filteredBackups,
        total: filteredBackups.length,
        page: 1,
        perPage: filteredBackups.length,
      };
    }

    // HYBRID APPROACH: Query both ImageStreams (internal registry) and DevWorkspace annotations (all registries)
    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      // Query ImageStreams for internal registry backups (existing logic)
      const imageStreamPromise = this.adapter.listBackupImages(namespace);

      // Query DevWorkspaces with backup annotations (handles external registries)
      const devworkspacesPromise = this.listDevWorkspacesWithBackups(namespace);
      const registryPathPromise = this.getBackupRegistryPath();

      // Execute all queries in parallel
      const [imageStreamResults, devworkspacesWithBackups, registryPath] = await Promise.race([
        Promise.all([imageStreamPromise, devworkspacesPromise, registryPathPromise]),
        timeoutPromise,
      ]);

      // SECURITY: Validate ImageStream data before processing
      if (!Array.isArray(imageStreamResults)) {
        throw createError(
          new Error('Invalid response from registry adapter'),
          BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
          'Expected array of backup images from ImageStreams',
        );
      }

      // Build a map of backups by workspace name (ImageStream data takes precedence)
      const backupMap = new Map<string, BackupItem>();

      // Add ImageStream results first (these have full data including size)
      // Merge DevWorkspace backup annotations into labels so frontend can derive status
      for (const image of imageStreamResults) {
        const exists = await this.doesWorkspaceExist(namespace, image.workspaceName);
        const matchingDW = devworkspacesWithBackups.find(
          dw => dw.metadata.name === image.workspaceName,
        );
        const dwAnnotations = matchingDW?.metadata?.annotations || {};
        const mergedLabels: Record<string, string> = { ...image.labels };
        if (dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] !== undefined) {
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL] =
            dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_SUCCESSFUL];
        }
        if (dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] !== undefined) {
          mergedLabels[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR] =
            dwAnnotations[DEVWORKSPACE_BACKUP_ANNOTATIONS.LAST_BACKUP_ERROR];
        }
        backupMap.set(image.workspaceName, {
          ...image,
          workspaceExists: exists,
          labels: mergedLabels,
        });
      }

      // Add annotation-based results for workspaces NOT in ImageStream results
      // This handles external registry backups
      for (const dw of devworkspacesWithBackups) {
        const wsName = dw.metadata.name;
        if (!backupMap.has(wsName)) {
          const backupItem = this.buildBackupItemFromAnnotations(dw, registryPath, namespace);
          backupMap.set(wsName, backupItem);
        }
      }

      // Convert map to array
      const allBackups = Array.from(backupMap.values());

      // Cache the full result set
      this.setCache(cacheKey, allBackups, backupCacheTTL);

      // Filter by workspace name if provided
      let filteredBackups = allBackups;
      if (workspaceName) {
        filteredBackups = allBackups.filter(backup => backup.workspaceName === workspaceName);
      }

      return {
        backups: filteredBackups,
        total: filteredBackups.length,
        page: 1,
        perPage: filteredBackups.length,
      };
    } catch (e) {
      // On timeout, return cached results if available
      if ((e as Error).message === 'Registry query timeout') {
        const cachedResults = this.getFromCache<BackupItem[]>(cacheKey);
        if (cachedResults) {
          let filteredBackups = cachedResults;
          if (workspaceName) {
            filteredBackups = cachedResults.filter(
              backup => backup.workspaceName === workspaceName,
            );
          }

          return {
            backups: filteredBackups,
            total: filteredBackups.length,
            page: 1,
            perPage: filteredBackups.length,
          };
        }
      }

      // No cache available, propagate error
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list backup images in namespace '${namespace}'`,
      );
    }
  }

  /**
   * Validates if a backup image is accessible
   *
   * @param imageUrl - Backup image URL (format validated by adapter)
   * @returns Validation result with accessibility status
   *
   * CACHING: Results cached for 5 minutes per image URL
   * TIMEOUT: 10-second timeout with error result
   * SECURITY: No error caching to ensure fresh security checks
   */
  async validateBackupImage(imageUrl: string): Promise<BackupValidationResult> {
    // Basic URL validation
    if (!imageUrl || imageUrl.trim().length === 0) {
      throw createError(
        new Error('Empty image URL'),
        BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
        'Image URL cannot be empty',
      );
    }

    const cacheKey = this.getCacheKey('global', 'validateBackupImage', imageUrl);
    const cached = this.getFromCache<BackupValidationResult>(cacheKey);

    if (cached) {
      return cached;
    }

    // Validate with adapter (includes timeout protection)
    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      const accessibilityPromise = this.adapter.validateImageAccessibility(imageUrl);
      const metadataPromise = this.adapter.getImageMetadata(imageUrl);

      const [accessible, metadata] = await Promise.race([
        Promise.all([accessibilityPromise, metadataPromise]),
        timeoutPromise,
      ]);

      const result: BackupValidationResult = {
        valid: true,
        accessible,
        metadata: accessible
          ? {
              workspaceName: metadata.workspaceName,
              namespace: metadata.namespace,
              timestamp: metadata.timestamp,
              sizeBytes: metadata.sizeBytes,
            }
          : undefined,
      };

      // SECURITY: Only cache successful validations (no error caching)
      if (result.valid && result.accessible) {
        this.setCache(cacheKey, result, backupCacheTTL);
      }

      return result;
    } catch (e) {
      if ((e as Error).message === 'Registry query timeout') {
        return {
          valid: false,
          accessible: false,
          error: 'Registry query timed out while validating image',
        };
      }

      return {
        valid: false,
        accessible: false,
        error: (e as Error).message || 'Unknown error during validation',
      };
    }
  }

  /**
   * Retrieves metadata for a specific backup image
   *
   * @param imageUrl - Backup image URL (format validated by adapter)
   * @returns Backup item with metadata (timestamp, size, labels)
   *
   * CACHING: Results cached for 5 minutes per image URL
   * TIMEOUT: 10-second timeout with fallback to cached results
   */
  async getImageMetadata(imageUrl: string): Promise<BackupItem> {
    // Basic URL validation
    if (!imageUrl || imageUrl.trim().length === 0) {
      throw createError(
        new Error('Empty image URL'),
        BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
        'Image URL cannot be empty',
      );
    }

    const cacheKey = this.getCacheKey('global', 'getImageMetadata', imageUrl);
    const cached = this.getFromCache<BackupItem>(cacheKey);

    if (cached) {
      return cached;
    }

    // Fetch metadata with timeout protection
    try {
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new Error('Registry query timeout'));
        }, backupRegistryTimeout * 1000);
      });

      const fetchPromise = this.adapter.getImageMetadata(imageUrl);

      const metadata = await Promise.race([fetchPromise, timeoutPromise]);

      // SECURITY: Validate data before caching
      if (!metadata || typeof metadata !== 'object') {
        throw createError(
          new Error('Invalid metadata response'),
          BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
          'Expected image metadata object',
        );
      }

      // Check if workspace exists
      const workspaceExists = await this.doesWorkspaceExist(
        metadata.namespace,
        metadata.workspaceName,
      );

      const backupItem: BackupItem = {
        workspaceName: metadata.workspaceName,
        imageUrl,
        timestamp: metadata.timestamp,
        sizeBytes: metadata.sizeBytes,
        workspaceExists,
        labels: metadata.labels,
      };

      // Cache the result
      this.setCache(cacheKey, backupItem, backupCacheTTL);

      return backupItem;
    } catch (e) {
      // On timeout, return cached results if available
      if ((e as Error).message === 'Registry query timeout' && cached) {
        return cached;
      }

      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to retrieve metadata for backup image: ${imageUrl}`,
      );
    }
  }

  /**
   * Clears all cached data
   * Useful for testing and forced cache invalidation
   */
  clearCache(): void {
    this.cache.clear();
  }

  /**
   * Clears cached data for a specific namespace
   * SECURITY: Namespace-scoped invalidation prevents cross-tenant cache interference
   */
  clearNamespaceCache(namespace: string): void {
    validateK8sName(namespace, 'namespace');

    const keysToDelete: string[] = [];
    for (const key of this.cache.keys()) {
      if (key.startsWith(`${namespace}:`)) {
        keysToDelete.push(key);
      }
    }

    keysToDelete.forEach(key => this.cache.delete(key));
  }
}
