/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

/* eslint-disable @typescript-eslint/no-unused-vars */

import {
  BACKUP_ERROR_CODES,
  BACKUP_IMAGE_DEFAULT_TAG,
  DEVWORKSPACE_BACKUP_LABELS,
  OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME,
  OPENSHIFT_INTERNAL_REGISTRY_PORT,
} from '@eclipse-che/common';
import * as mockClient from '@kubernetes/client-node';
import { CustomObjectsApi } from '@kubernetes/client-node';

import { OpenShiftRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters/OpenShiftRegistryAdapter';

const namespace = 'user-che';
const workspaceName = 'my-workspace';
const imageUrl = `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:${OPENSHIFT_INTERNAL_REGISTRY_PORT}/${namespace}/${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`;

describe('OpenShiftRegistryAdapter', () => {
  let registryAdapter: OpenShiftRegistryAdapter;
  let stubCustomObjectsApi: CustomObjectsApi;

  const mockImageStream = {
    apiVersion: 'image.openshift.io/v1',
    kind: 'ImageStream',
    metadata: {
      name: workspaceName,
      namespace,
      labels: {
        [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME]: workspaceName,
        [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAMESPACE]: namespace,
      },
    },
    spec: {},
    status: {
      dockerImageRepository: `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:${OPENSHIFT_INTERNAL_REGISTRY_PORT}/${namespace}/${workspaceName}`,
      tags: [
        {
          tag: BACKUP_IMAGE_DEFAULT_TAG,
          items: [
            {
              created: '2026-02-10T12:00:00Z',
              dockerImageReference: `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:${OPENSHIFT_INTERNAL_REGISTRY_PORT}/${namespace}/${workspaceName}@sha256:abc123`,
              image: 'sha256:abc123',
            },
          ],
        },
      ],
    },
  };

  const mockImageStreamTag = {
    apiVersion: 'image.openshift.io/v1',
    kind: 'ImageStreamTag',
    metadata: {
      name: `${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`,
      namespace,
      labels: {
        [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME]: workspaceName,
        [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAMESPACE]: namespace,
      },
    },
    image: {
      dockerImageMetadata: {
        Size: 1024000,
        Config: {
          Labels: {
            [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME]: workspaceName,
            [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAMESPACE]: namespace,
            'backup.timestamp': '2026-02-10T12:00:00Z',
          },
        },
      },
      dockerImageReference: `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:${OPENSHIFT_INTERNAL_REGISTRY_PORT}/${namespace}/${workspaceName}@sha256:abc123`,
      metadata: {
        name: 'sha256:abc123',
      },
    },
  };

  beforeEach(() => {
    stubCustomObjectsApi = {
      listNamespacedCustomObject: jest.fn().mockResolvedValue({
        body: {
          items: [mockImageStream],
        },
      }),
      getNamespacedCustomObject: jest.fn().mockResolvedValue({
        body: mockImageStreamTag,
      }),
    } as unknown as CustomObjectsApi;

    const { KubeConfig } = mockClient;
    const kubeConfig = new KubeConfig();
    kubeConfig.makeApiClient = jest.fn().mockImplementation(_api => stubCustomObjectsApi);

    registryAdapter = new OpenShiftRegistryAdapter(kubeConfig);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('listBackupImages', () => {
    it('should list all backup images in namespace', async () => {
      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(1);
      expect(backupImages[0]).toEqual({
        workspaceName,
        imageUrl,
        timestamp: '2026-02-10T12:00:00Z',
        sizeBytes: 1024000,
        labels: {
          [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME]: workspaceName,
          [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAMESPACE]: namespace,
          'backup.timestamp': '2026-02-10T12:00:00Z',
        },
      });

      expect(stubCustomObjectsApi.listNamespacedCustomObject).toHaveBeenCalledWith({
        group: 'image.openshift.io',
        version: 'v1',
        namespace,
        plural: 'imagestreams',
      });

      expect(stubCustomObjectsApi.getNamespacedCustomObject).toHaveBeenCalledWith({
        group: 'image.openshift.io',
        version: 'v1',
        namespace,
        plural: 'imagestreamtags',
        name: `${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`,
      });
    });

    it('should skip ImageStreams without workspace label', async () => {
      const imageStreamWithoutLabel = {
        ...mockImageStream,
        metadata: {
          ...mockImageStream.metadata,
          labels: {},
        },
      };

      stubCustomObjectsApi.listNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: {
          items: [imageStreamWithoutLabel],
        },
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(0);
    });

    it('should skip ImageStreams without :latest tag', async () => {
      const imageStreamWithoutLatest = {
        ...mockImageStream,
        status: {
          ...mockImageStream.status,
          tags: [
            {
              tag: 'v1.0.0',
              items: [mockImageStream.status.tags[0].items[0]],
            },
          ],
        },
      };

      stubCustomObjectsApi.listNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: {
          items: [imageStreamWithoutLatest],
        },
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(0);
    });

    it('should handle empty ImageStream list', async () => {
      stubCustomObjectsApi.listNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: {
          items: [],
        },
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(0);
    });

    it('should skip ImageStreams with empty tag items array', async () => {
      const imageStreamWithEmptyItems = {
        ...mockImageStream,
        status: {
          ...mockImageStream.status,
          tags: [
            {
              tag: BACKUP_IMAGE_DEFAULT_TAG,
              items: [],
            },
          ],
        },
      };

      stubCustomObjectsApi.listNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: {
          items: [imageStreamWithEmptyItems],
        },
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(0);
    });

    it('should skip ImageStreams without status', async () => {
      const imageStreamWithoutStatus = {
        ...mockImageStream,
        status: undefined,
      };

      stubCustomObjectsApi.listNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: {
          items: [imageStreamWithoutStatus],
        },
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(0);
    });

    it('should handle ImageStreamTag without size', async () => {
      const imageStreamTagWithoutSize = {
        ...mockImageStreamTag,
        image: {
          ...mockImageStreamTag.image,
          dockerImageMetadata: {
            Config: {
              Labels: {
                [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME]: workspaceName,
              },
            },
          },
        },
      };

      stubCustomObjectsApi.getNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: imageStreamTagWithoutSize,
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(1);
      expect(backupImages[0].sizeBytes).toBe(0);
    });

    it('should handle ImageStreamTag without Config.Labels', async () => {
      const imageStreamTagWithoutLabels = {
        ...mockImageStreamTag,
        image: {
          ...mockImageStreamTag.image,
          dockerImageMetadata: {
            Size: 1024000,
          },
        },
      };

      stubCustomObjectsApi.getNamespacedCustomObject = jest.fn().mockResolvedValue({
        body: imageStreamTagWithoutLabels,
      });

      const backupImages = await registryAdapter.listBackupImages(namespace);

      expect(backupImages).toHaveLength(1);
      expect(backupImages[0].labels).toEqual({});
    });

    it('should throw REGISTRY_API_ERROR on API failure', async () => {
      stubCustomObjectsApi.listNamespacedCustomObject = jest
        .fn()
        .mockRejectedValue(new Error('API Error'));

      await expect(registryAdapter.listBackupImages(namespace)).rejects.toThrow();
    }, 30000); // Increase timeout for retryable exec

    it('should throw TIMEOUT error on timeout', async () => {
      stubCustomObjectsApi.listNamespacedCustomObject = jest
        .fn()
        .mockImplementation(() => new Promise(resolve => setTimeout(resolve, 15000)));

      await expect(registryAdapter.listBackupImages(namespace)).rejects.toThrow();
    }, 20000); // Increase timeout for this test
  });

  describe('getImageMetadata', () => {
    it('should get metadata for a specific image', async () => {
      const metadata = await registryAdapter.getImageMetadata(imageUrl);

      expect(metadata).toEqual({
        workspaceName,
        namespace,
        timestamp: expect.any(String),
        sizeBytes: 1024000,
        labels: {
          [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME]: workspaceName,
          [DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAMESPACE]: namespace,
          'backup.timestamp': '2026-02-10T12:00:00Z',
        },
      });

      expect(stubCustomObjectsApi.getNamespacedCustomObject).toHaveBeenCalledWith({
        group: 'image.openshift.io',
        version: 'v1',
        namespace,
        plural: 'imagestreamtags',
        name: `${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`,
      });
    });

    it('should handle invalid image URL format', async () => {
      const invalidUrl = 'invalid-url';

      await expect(registryAdapter.getImageMetadata(invalidUrl)).rejects.toThrow();
    });

    it('should throw BACKUP_IMAGE_NOT_FOUND when image does not exist', async () => {
      stubCustomObjectsApi.getNamespacedCustomObject = jest
        .fn()
        .mockRejectedValue(new Error('Not found'));

      await expect(registryAdapter.getImageMetadata(imageUrl)).rejects.toThrow();
    }, 30000); // Increase timeout for retryable exec

    it('should handle image URL without tag (default to :latest)', async () => {
      const urlWithoutTag = `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:${OPENSHIFT_INTERNAL_REGISTRY_PORT}/${namespace}/${workspaceName}`;

      const metadata = await registryAdapter.getImageMetadata(urlWithoutTag);

      expect(metadata.workspaceName).toBe(workspaceName);
      expect(stubCustomObjectsApi.getNamespacedCustomObject).toHaveBeenCalledWith({
        group: 'image.openshift.io',
        version: 'v1',
        namespace,
        plural: 'imagestreamtags',
        name: `${workspaceName}:${BACKUP_IMAGE_DEFAULT_TAG}`,
      });
    });
  });

  describe('validateImageAccessibility', () => {
    it('should return true for accessible image', async () => {
      const isAccessible = await registryAdapter.validateImageAccessibility(imageUrl);

      expect(isAccessible).toBe(true);
    });

    it('should return false for inaccessible image', async () => {
      stubCustomObjectsApi.getNamespacedCustomObject = jest
        .fn()
        .mockRejectedValue(new Error('Not found'));

      const isAccessible = await registryAdapter.validateImageAccessibility(imageUrl);

      expect(isAccessible).toBe(false);
    }, 30000); // Increase timeout for retryable exec

    it('should return false for invalid image URL', async () => {
      const invalidUrl = 'invalid-url';

      const isAccessible = await registryAdapter.validateImageAccessibility(invalidUrl);

      expect(isAccessible).toBe(false);
    });

    it('should reject malicious URLs (SSRF protection)', async () => {
      const maliciousUrl = 'http://internal-api.local:8080/admin/secrets:tag';

      await expect(registryAdapter.getImageMetadata(maliciousUrl)).rejects.toThrow(
        'Invalid image URL',
      );
    }, 30000); // Increase timeout for retryable exec

    it('should reject external registry URLs (Phase 1 restriction)', async () => {
      const externalRegistryUrl = 'docker.io/library/nginx:latest';

      await expect(registryAdapter.getImageMetadata(externalRegistryUrl)).rejects.toThrow(
        'Only OpenShift internal registry is allowed',
      );
    }, 30000); // Increase timeout for retryable exec
  });
});
