/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

/* eslint-disable @typescript-eslint/no-unused-vars */

import { OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME } from '@eclipse-che/common';
import * as mockClient from '@kubernetes/client-node';
import { ApisApi } from '@kubernetes/client-node';

import { OpenShiftRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters/OpenShiftRegistryAdapter';
import { RegistryAdapterFactory } from '@/devworkspaceClient/services/helpers/registryAdapters/RegistryAdapterFactory';
import * as kubeclientHelpers from '@/services/kubeclient/helpers';

describe('RegistryAdapterFactory', () => {
  let kubeConfig: mockClient.KubeConfig;
  let stubApisApi: ApisApi;

  beforeEach(() => {
    const { KubeConfig } = mockClient;
    kubeConfig = new KubeConfig();

    stubApisApi = {} as ApisApi;

    kubeConfig.makeApiClient = jest.fn().mockImplementation(api => {
      if (api === mockClient.ApisApi) {
        return stubApisApi;
      }
      return {};
    });
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('create', () => {
    it('should create OpenShiftRegistryAdapter for OpenShift cluster with internal registry', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockResolvedValue(true);

      const registryUrl = `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:5000`;

      const adapter = await RegistryAdapterFactory.create(kubeConfig, registryUrl);

      expect(adapter).toBeInstanceOf(OpenShiftRegistryAdapter);
      expect(kubeclientHelpers.isOpenShift).toHaveBeenCalledWith(stubApisApi);
    });

    it('should accept OpenShift internal registry hostname variants', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockResolvedValue(true);

      // Test with port
      let adapter = await RegistryAdapterFactory.create(
        kubeConfig,
        `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:5000`,
      );
      expect(adapter).toBeInstanceOf(OpenShiftRegistryAdapter);

      // Test without port
      adapter = await RegistryAdapterFactory.create(
        kubeConfig,
        OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME,
      );
      expect(adapter).toBeInstanceOf(OpenShiftRegistryAdapter);

      // Test short form
      adapter = await RegistryAdapterFactory.create(
        kubeConfig,
        'image-registry.openshift-image-registry',
      );
      expect(adapter).toBeInstanceOf(OpenShiftRegistryAdapter);

      // Test with subdomain
      adapter = await RegistryAdapterFactory.create(
        kubeConfig,
        'image-registry.openshift-image-registry.svc.cluster.local',
      );
      expect(adapter).toBeInstanceOf(OpenShiftRegistryAdapter);
    });

    it('should throw error for non-OpenShift cluster', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockResolvedValue(false);

      const registryUrl = `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:5000`;

      await expect(RegistryAdapterFactory.create(kubeConfig, registryUrl)).rejects.toThrow(
        'OpenShift cluster required for backup features',
      );
    });

    it('should throw error for external registry in Phase 1', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockResolvedValue(true);

      const externalRegistry = 'quay.io';

      await expect(RegistryAdapterFactory.create(kubeConfig, externalRegistry)).rejects.toThrow(
        'External registry "quay.io" is not supported in Phase 1',
      );
    });

    it('should throw error for Docker Hub', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockResolvedValue(true);

      const dockerHub = 'docker.io';

      await expect(RegistryAdapterFactory.create(kubeConfig, dockerHub)).rejects.toThrow(
        'not supported in Phase 1',
      );
    });

    it('should throw error for Harbor registry', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockResolvedValue(true);

      const harbor = 'harbor.example.com';

      await expect(RegistryAdapterFactory.create(kubeConfig, harbor)).rejects.toThrow(
        'not supported in Phase 1',
      );
    });

    it('should propagate cluster detection errors', async () => {
      jest.spyOn(kubeclientHelpers, 'isOpenShift').mockRejectedValue(new Error('API error'));

      const registryUrl = `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:5000`;

      await expect(RegistryAdapterFactory.create(kubeConfig, registryUrl)).rejects.toThrow(
        'API error',
      );
    });
  });
});
