/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupInfo, BackupItem } from '@eclipse-che/common';
import { createReducer } from '@reduxjs/toolkit';

import {
  fetchBackupList,
  fetchWorkspaceBackupStatus,
  validateBackupImage,
} from '@/store/Backups/actions';

/**
 * Normalized backup state indexed by workspace UID
 * Allows efficient O(1) lookup of backup status for specific workspaces
 */
export interface BackupsByWorkspace {
  [workspaceUID: string]: BackupInfo;
}

/**
 * Backup items indexed by namespace
 * Used for the backup discovery/list view per namespace
 */
export interface BackupsByNamespace {
  [namespace: string]: BackupItem[];
}

/**
 * Loading state for different backup operations
 * Separated to allow granular UI loading indicators
 */
export interface LoadingState {
  /** Count of in-flight fetchWorkspaceBackupStatus requests */
  loadingCount: number;
  /** Updating backup list for a namespace */
  isUpdating: boolean;
  /** Validating a backup image URL */
  isValidating: boolean;
}

/** Whether any workspace backup status fetch is in-flight */
export function isLoading(state: LoadingState): boolean {
  return state.loadingCount > 0;
}

/**
 * Redux state shape for Backups feature
 */
export interface State {
  /** Backup status indexed by workspace UID for efficient lookups */
  byWorkspace: BackupsByWorkspace;
  /** Backup items indexed by namespace for discovery view */
  byNamespace: BackupsByNamespace;
  /** Loading states for different operations */
  loading: LoadingState;
  /** Error message if any operation failed */
  error: string | undefined;
}

/**
 * Initial/unloaded state for Backups feature
 */
export const unloadedState: State = {
  byWorkspace: {},
  byNamespace: {},
  loading: {
    loadingCount: 0,
    isUpdating: false,
    isValidating: false,
  },
  error: undefined,
};

/**
 * Backups reducer with async thunk handlers
 *
 * Handles async thunks from Task #11 (FRONTEND-02):
 * - fetchWorkspaceBackupStatus: Fetches backup status for a specific workspace
 * - fetchBackupList: Lists backup images for a namespace
 * - validateBackupImage: Validates a backup image URL
 */
export const reducer = createReducer(unloadedState, builder =>
  builder
    // fetchWorkspaceBackupStatus handlers
    .addCase(fetchWorkspaceBackupStatus.pending, state => {
      state.loading.loadingCount += 1;
      state.error = undefined;
    })
    .addCase(fetchWorkspaceBackupStatus.fulfilled, (state, action) => {
      const { workspaceUID } = action.meta.arg;
      state.byWorkspace[workspaceUID] = action.payload;
      state.loading.loadingCount = Math.max(0, state.loading.loadingCount - 1);
    })
    .addCase(fetchWorkspaceBackupStatus.rejected, (state, action) => {
      state.loading.loadingCount = Math.max(0, state.loading.loadingCount - 1);
      state.error = action.payload;
    })

    // fetchBackupList handlers
    .addCase(fetchBackupList.pending, state => {
      state.loading.isUpdating = true;
      state.error = undefined;
    })
    .addCase(fetchBackupList.fulfilled, (state, action) => {
      const { namespace } = action.meta.arg;
      state.byNamespace[namespace] = action.payload;
      state.loading.isUpdating = false;
    })
    .addCase(fetchBackupList.rejected, (state, action) => {
      state.loading.isUpdating = false;
      state.error = action.payload;
    })

    // validateBackupImage handlers
    .addCase(validateBackupImage.pending, state => {
      state.loading.isValidating = true;
      state.error = undefined;
    })
    .addCase(validateBackupImage.fulfilled, state => {
      state.loading.isValidating = false;
    })
    .addCase(validateBackupImage.rejected, (state, action) => {
      state.loading.isValidating = false;
      state.error = action.payload;
    })

    .addDefaultCase(state => state),
);
