/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupStatus } from '@eclipse-che/common';
import { createSelector } from '@reduxjs/toolkit';

import { RootState } from '@/store';
import { State as BackupsState } from '@/store/Backups/reducer';

/**
 * Extended RootState type that includes backups slice
 * Note: This will be part of the actual RootState when Task #14 (Register Backup Store Slice) is complete
 */
type RootStateWithBackups = RootState & { backups: BackupsState };

/**
 * Base selector for the entire backups state slice
 */
const selectBackupsState = (state: RootStateWithBackups) => state.backups;

/**
 * Basic Selectors
 */

/**
 * Select the entire backups state
 */
export const selectBackups = selectBackupsState;

/**
 * Select the loading state for all backup operations
 */
export const selectBackupsLoading = createSelector(
  selectBackupsState,
  state => state.loading,
);

/**
 * Select the error message if any operation failed
 */
export const selectBackupsError = createSelector(selectBackupsState, state => state.error);

/**
 * Workspace Selectors
 */

/**
 * Select backup info for a specific workspace by UID
 * Returns undefined if workspace has no backup info
 */
export const selectWorkspaceBackupInfo = createSelector(
  [selectBackupsState, (_state: RootStateWithBackups, workspaceUID: string) => workspaceUID],
  (backups, workspaceUID) => backups.byWorkspace[workspaceUID],
);

/**
 * Select just the backup status for a specific workspace
 * Returns BackupStatus.NEVER if workspace has no backup info
 */
export const selectWorkspaceBackupStatus = createSelector(
  [selectBackupsState, (_state: RootStateWithBackups, workspaceUID: string) => workspaceUID],
  (backups, workspaceUID) => backups.byWorkspace[workspaceUID]?.status || BackupStatus.NEVER,
);

/**
 * Check if a workspace has any backup info
 * Returns true if backup info exists (regardless of status)
 */
export const selectWorkspaceHasBackup = createSelector(
  [selectBackupsState, (_state: RootStateWithBackups, workspaceUID: string) => workspaceUID],
  (backups, workspaceUID) => {
    const info = backups.byWorkspace[workspaceUID];
    return !!info && info.status !== BackupStatus.NEVER;
  },
);

/**
 * Namespace Selectors
 */

/**
 * Select all backup items for a specific namespace
 * Returns empty array if namespace has no backups
 */
export const selectNamespaceBackups = createSelector(
  [selectBackupsState, (_state: RootStateWithBackups, namespace: string) => namespace],
  (backups, namespace) => backups.byNamespace[namespace] || [],
);

/**
 * Select the count of backups in a specific namespace
 */
export const selectNamespaceBackupCount = createSelector(
  [selectBackupsState, (_state: RootStateWithBackups, namespace: string) => namespace],
  (backups, namespace) => backups.byNamespace[namespace]?.length || 0,
);

/**
 * Memoized Selectors
 */

/**
 * Select filtered backup items for a namespace, optionally filtered by workspace name
 * Returns all backups for namespace if workspaceName is not provided
 * Returns only matching backups if workspaceName is provided
 */
export const selectFilteredNamespaceBackups = createSelector(
  [
    selectBackupsState,
    (_state: RootStateWithBackups, namespace: string) => namespace,
    (_state: RootStateWithBackups, _namespace: string, workspaceName?: string) => workspaceName,
  ],
  (backups, namespace, workspaceName) => {
    const namespaceBackups = backups.byNamespace[namespace] || [];

    if (!workspaceName) {
      return namespaceBackups;
    }

    return namespaceBackups.filter(backup => backup.workspaceName === workspaceName);
  },
);

/**
 * Select array of workspace UIDs that have backups
 * Useful for filtering workspace lists to show only backed-up workspaces
 */
export const selectWorkspacesWithBackups = createSelector(selectBackupsState, backups => {
  return Object.keys(backups.byWorkspace).filter(workspaceUID => {
    const info = backups.byWorkspace[workspaceUID];
    return info && info.status !== BackupStatus.NEVER;
  });
});

/**
 * Select all backup items across all namespaces
 * Returns a flat array of all backup items
 */
export const selectAllBackupItems = createSelector(selectBackupsState, backups => {
  return Object.values(backups.byNamespace).flat();
});

/**
 * Select loading state flags individually
 */
export const selectIsLoadingBackups = createSelector(
  selectBackupsState,
  state => state.loading.isLoading,
);

export const selectIsUpdatingBackups = createSelector(
  selectBackupsState,
  state => state.loading.isUpdating,
);

export const selectIsValidatingBackup = createSelector(
  selectBackupsState,
  state => state.loading.isValidating,
);
