/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import {
  BACKUP_ERROR_CODES,
  BACKUP_IMAGE_DEFAULT_TAG,
  DEVWORKSPACE_BACKUP_LABELS,
  OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME,
  OPENSHIFT_INTERNAL_REGISTRY_PORT,
  REGISTRY_QUERY_TIMEOUT_SECONDS,
} from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';

import { createError } from '@/devworkspaceClient/services/helpers/createError';
import { prepareCustomObjectAPI } from '@/devworkspaceClient/services/helpers/prepareCustomObjectAPI';
import {
  IBackupImage,
  IImageMetadata,
  IRegistryAdapter,
} from '@/devworkspaceClient/services/helpers/registryAdapters/IRegistryAdapter';
import { logger } from '@/utils/logger';

/**
 * OpenShift ImageStream object structure
 * Based on OpenShift Image API v1
 */
interface ImageStream {
  apiVersion: 'image.openshift.io/v1';
  kind: 'ImageStream';
  metadata: {
    name: string;
    namespace: string;
    labels?: Record<string, string>;
    annotations?: Record<string, string>;
    creationTimestamp?: string;
  };
  spec: {
    lookupPolicy?: {
      local: boolean;
    };
    tags?: Array<{
      name: string;
      annotations?: Record<string, string>;
      from?: {
        kind: string;
        name: string;
      };
    }>;
  };
  status?: {
    dockerImageRepository?: string;
    tags?: Array<{
      tag: string;
      items?: Array<{
        created: string;
        dockerImageReference: string;
        image: string;
      }>;
    }>;
  };
}

/**
 * ImageStreamTag object structure
 * Provides detailed metadata about a specific image tag
 */
interface ImageStreamTag {
  apiVersion: 'image.openshift.io/v1';
  kind: 'ImageStreamTag';
  metadata: {
    name: string;
    namespace: string;
    labels?: Record<string, string>;
    annotations?: Record<string, string>;
  };
  image: {
    dockerImageMetadata: {
      Size?: number;
      Config?: {
        Labels?: Record<string, string>;
      };
    };
    dockerImageReference: string;
    metadata: {
      name: string;
    };
  };
}

/**
 * OpenShift ImageStream API adapter for backup image discovery
 *
 * This adapter uses OpenShift's ImageStream API to discover and validate
 * backup images stored in the internal registry.
 *
 * API Endpoints Used:
 * - /apis/image.openshift.io/v1/namespaces/{namespace}/imagestreams
 * - /apis/image.openshift.io/v1/namespaces/{namespace}/imagestreamtags/{name}:{tag}
 *
 * MVP Scope:
 * - OpenShift internal registry only
 * - Images tagged with :latest
 * - Filtered by workspace labels
 */
export class OpenShiftRegistryAdapter implements IRegistryAdapter {
  private readonly customObjectAPI: ReturnType<typeof prepareCustomObjectAPI>;
  private readonly apiGroup = 'image.openshift.io';
  private readonly apiVersion = 'v1';
  private readonly timeout: number;

  constructor(kubeConfig: k8s.KubeConfig) {
    this.customObjectAPI = prepareCustomObjectAPI(kubeConfig);
    this.timeout = REGISTRY_QUERY_TIMEOUT_SECONDS * 1000; // Convert to milliseconds
  }

  /**
   * List all backup images in a namespace
   *
   * Queries OpenShift ImageStream API to find all ImageStreams that represent
   * workspace backups. Images are identified by the presence of the
   * DevWorkspace label (controller.devfile.io/devworkspace-name).
   *
   * @param namespace - Kubernetes namespace to query
   * @returns Promise resolving to array of backup images
   * @throws Error if registry query fails or times out
   */
  async listBackupImages(namespace: string): Promise<IBackupImage[]> {
    try {
      logger.info(`Listing backup images in namespace: ${namespace}`);

      // Query ImageStreams in the namespace with timeout
      const response = await this.withTimeout(
        this.customObjectAPI.listNamespacedCustomObject({
          group: this.apiGroup,
          version: this.apiVersion,
          namespace,
          plural: 'imagestreams',
        }),
        this.timeout,
        `Registry query timeout for namespace ${namespace}`,
      );

      const imageStreams = (response.body as { items: ImageStream[] }).items;

      // Filter and map ImageStreams to backup images
      const backupImages: IBackupImage[] = [];

      for (const imageStream of imageStreams) {
        // Check if ImageStream has DevWorkspace label
        const workspaceName =
          imageStream.metadata.labels?.[DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME];

        if (!workspaceName) {
          // Skip ImageStreams without workspace label
          continue;
        }

        // Get the :latest tag information
        const latestTag = imageStream.status?.tags?.find(
          tag => tag.tag === BACKUP_IMAGE_DEFAULT_TAG,
        );

        if (!latestTag || !latestTag.items || latestTag.items.length === 0) {
          logger.warn(`ImageStream ${imageStream.metadata.name} has no :latest tag, skipping`);
          continue;
        }

        // Get the most recent image (first in items array)
        const latestImage = latestTag.items[0];

        // Construct full image URL
        const imageUrl = `${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}:${OPENSHIFT_INTERNAL_REGISTRY_PORT}/${namespace}/${imageStream.metadata.name}:${BACKUP_IMAGE_DEFAULT_TAG}`;

        // Get image size and labels by querying ImageStreamTag
        const metadata = await this.getImageStreamTagMetadata(
          namespace,
          imageStream.metadata.name,
          BACKUP_IMAGE_DEFAULT_TAG,
        );

        backupImages.push({
          workspaceName,
          imageUrl,
          timestamp: latestImage.created,
          sizeBytes: metadata.sizeBytes,
          labels: metadata.labels,
        });
      }

      logger.info(`Found ${backupImages.length} backup images in namespace: ${namespace}`);
      return backupImages;
    } catch (e) {
      if ((e as Error).message.includes('timeout')) {
        throw createError(e, BACKUP_ERROR_CODES.TIMEOUT, 'Registry query timeout');
      }
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to list backup images in namespace ${namespace}`,
      );
    }
  }

  /**
   * Get metadata for a specific backup image
   *
   * Queries ImageStreamTag API to retrieve detailed metadata including
   * size, labels, and timestamp for a specific backup image.
   *
   * @param imageUrl - Full URL to the backup image
   * @returns Promise resolving to image metadata
   * @throws Error if image not found or metadata cannot be retrieved
   */
  async getImageMetadata(imageUrl: string): Promise<IImageMetadata> {
    try {
      // Parse image URL: registry/namespace/name:tag
      const parsedUrl = this.parseImageUrl(imageUrl);

      logger.info(`Getting metadata for image: ${imageUrl}`);

      // Query ImageStreamTag for detailed metadata
      const metadata = await this.getImageStreamTagMetadata(
        parsedUrl.namespace,
        parsedUrl.name,
        parsedUrl.tag,
      );

      return metadata;
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.BACKUP_IMAGE_NOT_FOUND,
        `Unable to get metadata for image: ${imageUrl}`,
      );
    }
  }

  /**
   * Validate that a backup image is accessible
   *
   * Attempts to retrieve image metadata to verify accessibility.
   * Used for cross-cluster restore validation.
   *
   * @param imageUrl - Full URL to the backup image
   * @returns Promise resolving to true if image is accessible
   */
  async validateImageAccessibility(imageUrl: string): Promise<boolean> {
    try {
      await this.getImageMetadata(imageUrl);
      return true;
    } catch (e) {
      logger.warn(`Image not accessible: ${imageUrl}`, e);
      return false;
    }
  }

  /**
   * Get ImageStreamTag metadata
   *
   * Helper method to query OpenShift ImageStreamTag API for detailed
   * image metadata including size and labels.
   *
   * @param namespace - Kubernetes namespace
   * @param name - ImageStream name
   * @param tag - Image tag
   * @returns Promise resolving to image metadata
   */
  private async getImageStreamTagMetadata(
    namespace: string,
    name: string,
    tag: string,
  ): Promise<IImageMetadata> {
    try {
      const imageStreamTagName = `${name}:${tag}`;

      const response = await this.withTimeout(
        this.customObjectAPI.getNamespacedCustomObject({
          group: this.apiGroup,
          version: this.apiVersion,
          namespace,
          plural: 'imagestreamtags',
          name: imageStreamTagName,
        }),
        this.timeout,
        `Registry query timeout for ImageStreamTag ${imageStreamTagName}`,
      );

      const imageStreamTag = response.body as ImageStreamTag;

      // Extract metadata from ImageStreamTag
      const sizeBytes = imageStreamTag.image.dockerImageMetadata.Size || 0;
      const labels = imageStreamTag.image.dockerImageMetadata.Config?.Labels || {};

      // Get workspace name and namespace from labels
      const workspaceName = labels[DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAME] || name;
      const workspaceNamespace =
        labels[DEVWORKSPACE_BACKUP_LABELS.WORKSPACE_NAMESPACE] || namespace;

      // Get timestamp from image metadata (use current time as fallback)
      const timestamp = imageStreamTag.metadata.annotations?.['openshift.io/image.managed']
        ? new Date().toISOString()
        : new Date().toISOString();

      return {
        workspaceName,
        namespace: workspaceNamespace,
        timestamp,
        sizeBytes,
        labels,
      };
    } catch (e) {
      throw createError(
        e,
        BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        `Unable to get ImageStreamTag metadata: ${name}:${tag}`,
      );
    }
  }

  /**
   * Parse image URL into components
   *
   * Expected format: registry/namespace/name:tag
   * Example: image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest
   *
   * @param imageUrl - Full image URL
   * @returns Parsed URL components
   * @throws Error if URL format is invalid
   */
  private parseImageUrl(imageUrl: string): {
    registry: string;
    namespace: string;
    name: string;
    tag: string;
  } {
    // Remove registry prefix (everything before the first /)
    const parts = imageUrl.split('/');
    if (parts.length < 3) {
      throw new Error(`Invalid image URL format: ${imageUrl}`);
    }

    const registry = parts[0];
    const namespace = parts[1];
    const nameAndTag = parts.slice(2).join('/'); // Handle image names with /

    // Split name and tag
    const [name, tag = BACKUP_IMAGE_DEFAULT_TAG] = nameAndTag.split(':');

    return {
      registry,
      namespace,
      name,
      tag,
    };
  }

  /**
   * Execute a promise with timeout
   *
   * Wraps a promise with a timeout to prevent hanging registry queries.
   *
   * @param promise - Promise to execute
   * @param timeoutMs - Timeout in milliseconds
   * @param errorMessage - Error message if timeout occurs
   * @returns Promise that resolves or rejects based on the original promise or timeout
   */
  private async withTimeout<T>(
    promise: Promise<T>,
    timeoutMs: number,
    errorMessage: string,
  ): Promise<T> {
    const timeoutPromise = new Promise<never>((_, reject) => {
      setTimeout(() => reject(new Error(errorMessage)), timeoutMs);
    });

    return Promise.race([promise, timeoutPromise]);
  }
}
