/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME } from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';

import { IRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters/IRegistryAdapter';
import { OpenShiftRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters/OpenShiftRegistryAdapter';
import { isOpenShift } from '@/services/kubeclient/helpers';
import { logger } from '@/utils/logger';

/**
 * Factory for creating registry adapters based on cluster type and configuration
 *
 * Phase 1 (MVP):
 * - OpenShift internal registry only (ImageStream API)
 * - Factory returns OpenShiftRegistryAdapter for OpenShift clusters
 *
 * Phase 2 (Future):
 * - Generic OCI registry adapter for external registries
 * - Support for Docker Hub, Quay.io, Harbor, etc.
 * - Adapter selection based on registry URL
 */
export class RegistryAdapterFactory {
  /**
   * Create a registry adapter based on cluster type and configuration
   *
   * MVP Implementation:
   * - Detects if cluster is OpenShift
   * - Checks if registry URL is OpenShift internal registry
   * - Returns OpenShiftRegistryAdapter if both conditions are met
   * - Throws error for external registries (not supported in Phase 1)
   *
   * @param kubeConfig - Kubernetes configuration
   * @param registryUrl - Container registry URL from backup configuration
   * @returns Promise resolving to appropriate registry adapter
   * @throws Error if registry type is not supported in current phase
   */
  static async create(kubeConfig: k8s.KubeConfig, registryUrl: string): Promise<IRegistryAdapter> {
    logger.info(`Creating registry adapter for registry: ${registryUrl}`);

    // Check if cluster is OpenShift
    const apisApi = kubeConfig.makeApiClient(k8s.ApisApi);
    const isOpenshiftCluster = await isOpenShift(apisApi);

    if (!isOpenshiftCluster) {
      throw new Error(
        'OpenShift cluster required for backup features. ' +
          'Generic Kubernetes clusters are not supported in Phase 1.',
      );
    }

    // Check if using OpenShift internal registry
    const usesInternalRegistry = this.isOpenShiftInternalRegistry(registryUrl);

    if (!usesInternalRegistry) {
      throw new Error(
        `External registry "${registryUrl}" is not supported in Phase 1. ` +
          `Only OpenShift internal registry (${OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME}) is supported.`,
      );
    }

    logger.info('Using OpenShift internal registry adapter');
    return new OpenShiftRegistryAdapter(kubeConfig);
  }

  /**
   * Check if registry URL is OpenShift internal registry
   *
   * OpenShift internal registry hostnames:
   * - image-registry.openshift-image-registry.svc:5000
   * - image-registry.openshift-image-registry.svc
   * - image-registry.openshift-image-registry (short form)
   *
   * @param registryUrl - Registry URL to check
   * @returns True if URL is OpenShift internal registry
   */
  private static isOpenShiftInternalRegistry(registryUrl: string): boolean {
    // Remove port if present
    const registryHost = registryUrl.split(':')[0];

    // Check if it matches OpenShift internal registry hostname patterns
    return (
      registryHost === OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME ||
      registryHost === 'image-registry.openshift-image-registry' ||
      registryHost.startsWith('image-registry.openshift-image-registry.')
    );
  }
}
