/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import {
  Card,
  CardBody,
  CardTitle,
  Content,
  ContentVariants,
  EmptyState,
  EmptyStateBody,
  Gallery,
  Label,
  PageSection,
  PageSectionVariants,
} from '@patternfly/react-core';
import { CubesIcon } from '@patternfly/react-icons';
import React from 'react';

import { AgentStatusBadge } from '@/components/AgentStatusBadge';
import Head from '@/components/Head';
import styles from '@/pages/AgentActivity/index.module.css';
import devfileApi from '@/services/devfileApi';
import {
  AgentStatus,
  DEVWORKSPACE_AGENT_BACKEND,
  DEVWORKSPACE_AGENT_SESSION,
  DEVWORKSPACE_AGENT_STARTED,
  DEVWORKSPACE_AGENT_STATUS,
  DEVWORKSPACE_AGENT_TASK,
} from '@/services/devfileApi/devWorkspace/metadata';

type Props = {
  workspaces: devfileApi.DevWorkspace[];
};

function getStatusFromWorkspace(workspace: devfileApi.DevWorkspace): AgentStatus | undefined {
  const status = workspace.metadata.annotations?.[DEVWORKSPACE_AGENT_STATUS];
  if (status === 'running' || status === 'finished' || status === 'lost' || status === 'idle') {
    return status;
  }
  return undefined;
}

function getElapsedTime(startedISO: string | undefined): string {
  if (!startedISO) {
    return '--';
  }

  try {
    const startedDate = new Date(startedISO);
    if (isNaN(startedDate.getTime())) {
      return '--';
    }

    const now = new Date();
    const elapsedMs = now.getTime() - startedDate.getTime();
    const elapsedSeconds = Math.floor(elapsedMs / 1000);

    if (elapsedSeconds < 60) {
      return `${elapsedSeconds}s`;
    } else if (elapsedSeconds < 3600) {
      const minutes = Math.floor(elapsedSeconds / 60);
      return `${minutes}m`;
    } else if (elapsedSeconds < 86400) {
      const hours = Math.floor(elapsedSeconds / 3600);
      const minutes = Math.floor((elapsedSeconds % 3600) / 60);
      return `${hours}h ${minutes}m`;
    } else {
      const days = Math.floor(elapsedSeconds / 86400);
      const hours = Math.floor((elapsedSeconds % 86400) / 3600);
      return `${days}d ${hours}h`;
    }
  } catch {
    return '--';
  }
}

function truncateTask(task: string | undefined, maxLength = 100): string {
  if (!task) {
    return 'No task description';
  }
  if (task.length <= maxLength) {
    return task;
  }
  return task.substring(0, maxLength) + '...';
}

export default class AgentActivityPage extends React.PureComponent<Props> {
  private getStatusCounts(): Record<AgentStatus | 'total', number> {
    const counts: Record<AgentStatus | 'total', number> = {
      running: 0,
      finished: 0,
      lost: 0,
      idle: 0,
      total: this.props.workspaces.length,
    };

    this.props.workspaces.forEach(workspace => {
      const status = getStatusFromWorkspace(workspace);
      if (status) {
        counts[status]++;
      }
    });

    return counts;
  }

  private renderSummaryBar(): React.ReactElement {
    const counts = this.getStatusCounts();

    return (
      <PageSection variant={PageSectionVariants.default}>
        <div className={styles.summaryBar}>
          <Label color="blue" data-testid="total-count">
            Total: {counts.total}
          </Label>
          <Label color="blue" data-testid="running-count">
            Running: {counts.running}
          </Label>
          <Label color="green" data-testid="finished-count">
            Finished: {counts.finished}
          </Label>
          <Label color="orange" data-testid="lost-count">
            Lost: {counts.lost}
          </Label>
          <Label color="grey" data-testid="idle-count">
            Idle: {counts.idle}
          </Label>
        </div>
      </PageSection>
    );
  }

  private renderEmptyState(): React.ReactElement {
    return (
      <PageSection>
        <EmptyState icon={CubesIcon} titleText="No active agent sessions">
          <EmptyStateBody>
            There are currently no workspaces with active agent sessions.
          </EmptyStateBody>
        </EmptyState>
      </PageSection>
    );
  }

  private renderWorkspaceCard(workspace: devfileApi.DevWorkspace): React.ReactElement {
    const annotations = workspace.metadata.annotations || {};
    const status = getStatusFromWorkspace(workspace);
    const backend = annotations[DEVWORKSPACE_AGENT_BACKEND] || 'Unknown';
    const sessionId = annotations[DEVWORKSPACE_AGENT_SESSION] || 'N/A';
    const task = annotations[DEVWORKSPACE_AGENT_TASK];
    const started = annotations[DEVWORKSPACE_AGENT_STARTED];
    const elapsed = getElapsedTime(started);
    const taskPreview = truncateTask(task);

    return (
      <Card key={workspace.metadata.uid} isFullHeight>
        <CardTitle>{workspace.metadata.name}</CardTitle>
        <CardBody>
          <Content component={ContentVariants.small}>
            <p>
              <strong>Agent Type:</strong> {backend}
            </p>
            <p>
              <strong>Status:</strong> <AgentStatusBadge status={status} />
            </p>
            <p>
              <strong>Session ID:</strong> {sessionId}
            </p>
            <p>
              <strong>Elapsed:</strong> {elapsed}
            </p>
            <p>
              <strong>Task:</strong> {taskPreview}
            </p>
          </Content>
        </CardBody>
      </Card>
    );
  }

  private renderCardGallery(): React.ReactElement {
    return (
      <PageSection>
        <Gallery hasGutter minWidths={{ default: '100%', sm: '300px', md: '400px' }}>
          {this.props.workspaces.map(workspace => this.renderWorkspaceCard(workspace))}
        </Gallery>
      </PageSection>
    );
  }

  public render(): React.ReactElement {
    const { workspaces } = this.props;

    return (
      <React.Fragment>
        <Head pageName="Agent Activity" />
        {workspaces.length === 0 ? (
          this.renderEmptyState()
        ) : (
          <React.Fragment>
            {this.renderSummaryBar()}
            {this.renderCardGallery()}
          </React.Fragment>
        )}
      </React.Fragment>
    );
  }
}
