/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BackupInfo, BackupItem, BackupValidationResult, helpers } from '@eclipse-che/common';

import { AxiosWrapper } from '@/services/axios-wrapper/axiosWrapper';
import { dashboardBackendPrefix } from '@/services/backend-client/const';

export interface BackupListResponse {
  backups: BackupItem[];
  total: number;
  page: number;
  perPage: number;
}

/**
 * Get backup status for a specific workspace
 *
 * @param namespace - Kubernetes namespace
 * @param workspaceName - DevWorkspace name
 * @returns BackupInfo with status, timestamps, and backup URL
 */
export async function getWorkspaceBackupStatus(
  namespace: string,
  workspaceName: string,
): Promise<BackupInfo> {
  try {
    const response = await AxiosWrapper.createToRetryMissedBearerTokenError().get<BackupInfo>(
      `${dashboardBackendPrefix}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`,
    );
    return response.data;
  } catch (e) {
    throw new Error(
      `Failed to fetch backup status for workspace '${workspaceName}'. ${helpers.errors.getMessage(e)}`,
    );
  }
}

/**
 * List backup images for a namespace with optional filtering and pagination
 *
 * @param namespace - Kubernetes namespace
 * @param workspaceName - Optional workspace name filter
 * @param page - Page number (1-indexed)
 * @param perPage - Items per page
 * @returns Paginated list of backup images
 */
export async function listBackups(
  namespace: string,
  workspaceName?: string,
  page?: number,
  perPage?: number,
): Promise<BackupListResponse> {
  try {
    const response = await AxiosWrapper.createToRetryMissedBearerTokenError().get<BackupListResponse>(
      `${dashboardBackendPrefix}/namespace/${namespace}/backups`,
      {
        params: {
          workspaceName,
          page,
          perPage,
        },
      },
    );
    return response.data;
  } catch (e) {
    throw new Error(`Failed to list backups for namespace '${namespace}'. ${helpers.errors.getMessage(e)}`);
  }
}

/**
 * Validate a backup image URL for accessibility and format
 *
 * @param namespace - Kubernetes namespace
 * @param imageUrl - Backup image URL to validate
 * @returns Validation result with accessibility status and metadata
 */
export async function validateBackupImage(
  namespace: string,
  imageUrl: string,
): Promise<BackupValidationResult> {
  try {
    const response = await AxiosWrapper.createToRetryMissedBearerTokenError().post<BackupValidationResult>(
      `${dashboardBackendPrefix}/namespace/${namespace}/backups/validate`,
      { imageUrl },
    );
    return response.data;
  } catch (e) {
    throw new Error(`Failed to validate backup image. ${helpers.errors.getMessage(e)}`);
  }
}

/**
 * Get metadata for a specific backup image
 *
 * @param namespace - Kubernetes namespace
 * @param imageUrl - Backup image URL
 * @returns Backup metadata including workspace name, timestamp, size, and labels
 */
export async function getBackupMetadata(
  namespace: string,
  imageUrl: string,
): Promise<BackupItem> {
  try {
    const response = await AxiosWrapper.createToRetryMissedBearerTokenError().post<BackupItem>(
      `${dashboardBackendPrefix}/namespace/${namespace}/backups/metadata`,
      { imageUrl },
    );
    return response.data;
  } catch (e) {
    throw new Error(`Failed to get backup metadata. ${helpers.errors.getMessage(e)}`);
  }
}
