/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupItem, BackupStatus } from '@eclipse-che/common';
import {
  Dropdown,
  DropdownItem,
  InputGroup,
  KebabToggle,
  Label,
  PageSection,
  PageSectionVariants,
  Spinner,
  TextInput,
  Toolbar,
  ToolbarContent,
  ToolbarItem,
} from '@patternfly/react-core';
import { SearchIcon } from '@patternfly/react-icons';
import {
  ICell,
  sortable,
  SortByDirection,
  Table,
  TableBody,
  TableHeader,
  TableVariant,
} from '@patternfly/react-table';
import React from 'react';
import { connect, ConnectedProps } from 'react-redux';

import { BackupStatusBadge } from '@/components/BackupStatusBadge';
import { BackupsEmptyState } from '@/pages/WorkspacesList/BackupsView/EmptyState';
import styles from '@/pages/WorkspacesList/BackupsView/index.module.css';
import { formatDate, formatRelativeDate } from '@/services/helpers/dates';
import { buildGettingStartedLocation } from '@/services/helpers/location';
import { RootState } from '@/store';
import { fetchBackupList } from '@/store/Backups/actions';
import {
  selectBackupsError,
  selectIsUpdatingBackups,
  selectNamespaceBackups,
} from '@/store/Backups/selectors';
import { selectDefaultNamespace } from '@/store/InfrastructureNamespaces/selectors';

type MappedProps = ConnectedProps<typeof connector>;

type Props = MappedProps & {
  navigate: (location: ReturnType<typeof buildGettingStartedLocation>) => void;
};

type State = {
  filterValue: string;
  sortBy: {
    index: number;
    direction: SortByDirection;
  };
  expandedDropdowns: Record<string, boolean>;
};

const COLUMNS: (ICell | string)[] = [
  {
    title: 'Workspace Name',
    dataLabel: 'Workspace Name',
    transforms: [sortable],
  },
  {
    title: 'Backup Time',
    dataLabel: 'Backup Time',
    transforms: [sortable],
  },
  {
    title: 'Size',
    dataLabel: 'Size',
    transforms: [sortable],
  },
  {
    title: 'Status',
    dataLabel: 'Status',
  },
  {
    title: '',
    dataLabel: 'Actions',
  },
];

export class BackupsView extends React.PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      filterValue: '',
      sortBy: {
        index: 1,
        direction: SortByDirection.desc,
      },
      expandedDropdowns: {},
    };
  }

  public componentDidMount(): void {
    const { namespace } = this.props;
    if (namespace) {
      this.props.fetchBackupList({ namespace });
    }
  }

  public componentDidUpdate(prevProps: Props): void {
    const { namespace } = this.props;
    if (namespace && namespace !== prevProps.namespace) {
      this.props.fetchBackupList({ namespace });
    }
  }

  private handleFilterChange(value: string): void {
    this.setState({ filterValue: value });
  }

  private handleSort(_event: React.MouseEvent, index: number, direction: SortByDirection): void {
    this.setState({
      sortBy: { index, direction },
    });
  }

  private handleDropdownToggle(imageUrl: string, isOpen: boolean): void {
    this.setState(prevState => ({
      expandedDropdowns: {
        ...prevState.expandedDropdowns,
        [imageUrl]: isOpen,
      },
    }));
  }

  private handleCreateFromBackup(backup: BackupItem): void {
    const location = buildGettingStartedLocation();
    location.search = `?restoreFromBackup=true&backupImageUrl=${encodeURIComponent(backup.imageUrl)}`;
    this.props.navigate(location);
  }

  private getFilteredBackups(): BackupItem[] {
    const { backups } = this.props;
    const { filterValue } = this.state;

    if (!filterValue) {
      return backups;
    }

    const lowerFilter = filterValue.toLowerCase();
    return backups.filter(backup => backup.workspaceName.toLowerCase().includes(lowerFilter));
  }

  private getSortedBackups(backups: BackupItem[]): BackupItem[] {
    const { sortBy } = this.state;
    const sorted = [...backups];

    sorted.sort((a, b) => {
      let comparison = 0;
      switch (sortBy.index) {
        case 0: // Workspace Name
          comparison = a.workspaceName.localeCompare(b.workspaceName);
          break;
        case 1: // Backup Time
          comparison = new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime();
          break;
        case 2: // Size
          comparison = a.sizeBytes - b.sizeBytes;
          break;
        default:
          comparison = 0;
      }
      return sortBy.direction === SortByDirection.asc ? comparison : -comparison;
    });

    return sorted;
  }

  private buildRows(backups: BackupItem[]): { cells: { title: React.ReactNode; key: string }[] }[] {
    return backups.map(backup => ({
      cells: [
        {
          title: (
            <span data-testid="backup-workspace-name">
              {backup.workspaceName}{' '}
              {backup.workspaceExists ? (
                <Label color="green" isCompact data-testid="backup-workspace-active">
                  Active
                </Label>
              ) : (
                <Label color="grey" isCompact data-testid="backup-workspace-deleted">
                  Deleted
                </Label>
              )}
            </span>
          ),
          key: 'workspace-name',
        },
        {
          title: (
            <span data-testid="backup-time" title={formatDate(new Date(backup.timestamp))}>
              {formatRelativeDate(new Date(backup.timestamp))}
            </span>
          ),
          key: 'backup-time',
        },
        {
          title: <span data-testid="backup-size">{formatBytes(backup.sizeBytes)}</span>,
          key: 'size',
        },
        {
          title: (
            <span data-testid="backup-status">
              <BackupStatusBadge
                status={BackupStatus.SUCCESS}
                lastBackupTime={backup.timestamp}
                backupImageUrl={backup.imageUrl}
                size="sm"
              />
            </span>
          ),
          key: 'status',
        },
        {
          title: this.buildActionsDropdown(backup),
          key: 'actions',
        },
      ],
    }));
  }

  private buildActionsDropdown(backup: BackupItem): React.ReactElement {
    const isExpanded = this.state.expandedDropdowns[backup.imageUrl] || false;

    return (
      <Dropdown
        isPlain
        position="right"
        isOpen={isExpanded}
        toggle={
          <KebabToggle
            aria-label={`Actions for ${backup.workspaceName}`}
            data-testid={`actions-dropdown-toggle-${backup.workspaceName}`}
            onToggle={isOpen => this.handleDropdownToggle(backup.imageUrl, isOpen)}
          />
        }
        dropdownItems={[
          <DropdownItem
            key="create-from-backup"
            component="button"
            data-testid={`create-from-backup-${backup.workspaceName}`}
            onClick={() => this.handleCreateFromBackup(backup)}
          >
            Create from Backup
          </DropdownItem>,
        ]}
      />
    );
  }

  private renderToolbar(): React.ReactElement {
    const { filterValue } = this.state;

    return (
      <Toolbar id="backups-view-toolbar" data-testid="backups-view-toolbar">
        <ToolbarContent>
          <ToolbarItem variant="search-filter">
            <InputGroup>
              <TextInput
                name="backups-filter-input"
                id="backups-filter-input"
                type="search"
                aria-label="Filter backups by workspace name"
                placeholder="Search by workspace name"
                value={filterValue}
                onChange={value => this.handleFilterChange(value)}
                data-testid="backups-filter-input"
              />
              <span className={styles.searchIcon}>
                <SearchIcon />
              </span>
            </InputGroup>
          </ToolbarItem>
        </ToolbarContent>
      </Toolbar>
    );
  }

  private renderLoading(): React.ReactElement {
    return (
      <PageSection
        variant={PageSectionVariants.light}
        isFilled={true}
        className={styles.loadingContainer}
      >
        <Spinner size="xl" data-testid="backups-loading-spinner" aria-label="Loading backups" />
      </PageSection>
    );
  }

  public render(): React.ReactElement {
    const { isLoading, error } = this.props;
    const { sortBy } = this.state;

    if (isLoading) {
      return this.renderLoading();
    }

    const filtered = this.getFilteredBackups();
    const sorted = this.getSortedBackups(filtered);
    const rows = this.buildRows(sorted);

    const toolbar = this.renderToolbar();

    if (this.props.backups.length === 0) {
      return (
        <div data-testid="backups-view">
          <BackupsEmptyState />
        </div>
      );
    }

    return (
      <div data-testid="backups-view">
        {error && (
          <PageSection variant={PageSectionVariants.light}>
            <span className={styles.errorMessage} data-testid="backups-error">
              {error}
            </span>
          </PageSection>
        )}
        <PageSection
          padding={{ default: 'noPadding' }}
          variant={PageSectionVariants.light}
          isFilled={false}
        >
          <Table
            aria-label="Backups List Table"
            cells={COLUMNS}
            rows={rows}
            variant={TableVariant.compact}
            header={toolbar}
            sortBy={sortBy}
            onSort={(event, index, direction) => this.handleSort(event, index, direction)}
            data-testid="backups-table"
          >
            <TableHeader />
            <TableBody />
          </Table>
        </PageSection>
        {rows.length === 0 && this.props.backups.length > 0 && (
          <PageSection variant={PageSectionVariants.light} isFilled={true}>
            <span data-testid="backups-nothing-found">No backups match the filter criteria.</span>
          </PageSection>
        )}
      </div>
    );
  }
}

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  const index = Math.min(i, units.length - 1);
  const value = bytes / Math.pow(1024, index);
  return `${value.toFixed(index === 0 ? 0 : 1)} ${units[index]}`;
}

const mapStateToProps = (state: RootState) => {
  const defaultNamespace = selectDefaultNamespace(state);
  const namespace = defaultNamespace.name;
  return {
    namespace,
    backups: selectNamespaceBackups(state, namespace),
    isLoading: selectIsUpdatingBackups(state),
    error: selectBackupsError(state),
  };
};

const mapDispatchToProps = {
  fetchBackupList,
};

const connector = connect(mapStateToProps, mapDispatchToProps);

export default connector(BackupsView);
