/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { namespacedSchema } from '@/constants/schemas';
import { BackupApiService } from '@/devworkspaceClient/services/backupApi';
import { OpenShiftRegistryAdapter } from '@/devworkspaceClient/services/helpers/registryAdapters/OpenShiftRegistryAdapter';
import { RegistryApiService } from '@/devworkspaceClient/services/registryApi';
import { restParams } from '@/models';
import { getServiceAccountToken } from '@/routes/api/helpers/getServiceAccountToken';
import { getSchema } from '@/services/helpers';
import { KubeConfigProvider } from '@/services/kubeclient/kubeConfigProvider';

const tags = ['Backup'];

interface IBackupStatusParams extends restParams.INamespacedParams {
  workspaceName: string;
}

const backupStatusParamsSchema = {
  type: 'object',
  required: ['namespace', 'workspaceName'],
  properties: {
    namespace: { type: 'string' },
    workspaceName: { type: 'string' },
  },
} as const;

interface IBackupListQuery {
  workspaceName?: string;
  page?: number;
  perPage?: number;
}

const backupListQuerySchema = {
  type: 'object',
  properties: {
    workspaceName: { type: 'string' },
    page: { type: 'number' },
    perPage: { type: 'number' },
  },
} as const;

interface IImageUrlBody {
  imageUrl: string;
}

const imageUrlBodySchema = {
  type: 'object',
  required: ['imageUrl'],
  properties: {
    imageUrl: { type: 'string', minLength: 1 },
  },
} as const;

export function registerBackupRoutes(instance: FastifyInstance) {
  instance.register(async server => {
    server.get(
      `${baseApiPath}/namespace/:namespace/devworkspaces/:workspaceName/backup-status`,
      getSchema({ tags, params: backupStatusParamsSchema }),
      async function (request: FastifyRequest) {
        const { namespace, workspaceName } = request.params as IBackupStatusParams;

        const token = getServiceAccountToken();
        const kubeConfigProvider = new KubeConfigProvider();
        const kubeConfig = kubeConfigProvider.getKubeConfig(token);
        const backupApiService = new BackupApiService(kubeConfig);

        return await backupApiService.getWorkspaceBackupStatus(namespace, workspaceName);
      },
    );

    // Route 1: List backup images for namespace
    server.get(
      `${baseApiPath}/namespace/:namespace/backups`,
      getSchema({ tags, params: namespacedSchema, querystring: backupListQuerySchema }),
      async function (request: FastifyRequest, reply: FastifyReply) {
        const { namespace } = request.params as restParams.INamespacedParams;
        const { workspaceName, page, perPage } = request.query as IBackupListQuery;

        // Layer 1: Input validation
        if (!namespace || namespace.trim() === '') {
          return reply.code(400).send({ message: 'Namespace is required' });
        }

        // Layer 3: Service call (Kubernetes RBAC enforced via kubeConfig)
        const token = getServiceAccountToken();
        const kubeConfigProvider = new KubeConfigProvider();
        const kubeConfig = kubeConfigProvider.getKubeConfig(token);
        const adapter = new OpenShiftRegistryAdapter(kubeConfig);
        const service = new RegistryApiService(kubeConfig, adapter);

        try {
          const result = await service.listBackupImages(namespace, workspaceName, page, perPage);
          return result;
        } catch (error) {
          console.error('Backup listing failed:', error);
          return reply.code(500).send({ message: 'Unable to list backups' });
        }
      },
    );

    // Route 2: Validate backup image URL
    server.post(
      `${baseApiPath}/namespace/:namespace/backups/validate`,
      getSchema({ tags, params: namespacedSchema, body: imageUrlBodySchema }),
      async function (request: FastifyRequest, reply: FastifyReply) {
        const { namespace } = request.params as restParams.INamespacedParams;
        const { imageUrl } = request.body as IImageUrlBody;

        // Layer 1: Input validation
        if (!namespace || namespace.trim() === '') {
          return reply.code(400).send({ message: 'Namespace is required' });
        }

        if (!imageUrl || imageUrl.trim() === '') {
          return reply.code(400).send({ message: 'imageUrl is required' });
        }

        // Layer 3: Service call (Kubernetes RBAC enforced via kubeConfig)
        const token = getServiceAccountToken();
        const kubeConfigProvider = new KubeConfigProvider();
        const kubeConfig = kubeConfigProvider.getKubeConfig(token);
        const adapter = new OpenShiftRegistryAdapter(kubeConfig);
        const service = new RegistryApiService(kubeConfig, adapter);

        try {
          const result = await service.validateBackupImage(imageUrl);
          return result;
        } catch (error) {
          console.error('Backup image validation failed:', error);
          return reply.code(500).send({ message: 'Unable to validate backup image' });
        }
      },
    );

    // Route 3: Get backup image metadata
    server.post(
      `${baseApiPath}/namespace/:namespace/backups/metadata`,
      getSchema({ tags, params: namespacedSchema, body: imageUrlBodySchema }),
      async function (request: FastifyRequest, reply: FastifyReply) {
        const { namespace } = request.params as restParams.INamespacedParams;
        const { imageUrl } = request.body as IImageUrlBody;

        // Layer 1: Input validation
        if (!namespace || namespace.trim() === '') {
          return reply.code(400).send({ message: 'Namespace is required' });
        }

        if (!imageUrl || imageUrl.trim() === '') {
          return reply.code(400).send({ message: 'imageUrl is required' });
        }

        // Layer 3: Service call (Kubernetes RBAC enforced via kubeConfig)
        const token = getServiceAccountToken();
        const kubeConfigProvider = new KubeConfigProvider();
        const kubeConfig = kubeConfigProvider.getKubeConfig(token);
        const adapter = new OpenShiftRegistryAdapter(kubeConfig);
        const service = new RegistryApiService(kubeConfig, adapter);

        try {
          const result = await service.getImageMetadata(imageUrl);
          return result;
        } catch (error) {
          console.error('Backup image metadata retrieval failed:', error);
          return reply.code(500).send({ message: 'Unable to get backup image metadata' });
        }
      },
    );
  });
}
