/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { V1Job, V1Status } from '@kubernetes/client-node';
import { FastifyInstance, FastifyRequest } from 'fastify';
import WebSocket from 'ws';

import { baseApiPath } from '@/constants/config';
import { prepareCustomObjectWatch } from '@/devworkspaceClient/services/helpers/prepareCustomObjectWatch';
import { getServiceAccountToken } from '@/routes/api/helpers/getServiceAccountToken';
import { KubeConfigProvider } from '@/services/kubeclient/kubeConfigProvider';
import { logger } from '@/utils/logger';

export type BackupJobPhase = 'Pending' | 'Running' | 'Succeeded' | 'Failed';

export interface StatusUpdateEvent {
  type: 'status-update';
  phase: BackupJobPhase;
  startTime?: string;
  completionTime?: string;
}

export interface CompletedEvent {
  type: 'completed';
  status: 'success' | 'failed';
  backupImageUrl?: string;
  error?: string;
}

export type BackupJobEvent = StatusUpdateEvent | CompletedEvent;

interface IBackupJobParams {
  namespace: string;
  jobName: string;
}

export function determineJobPhase(job: V1Job): BackupJobPhase {
  if (job.status?.succeeded && job.status.succeeded > 0) {
    return 'Succeeded';
  }
  if (job.status?.failed && job.status.failed > 0) {
    return 'Failed';
  }
  if (job.status?.active && job.status.active > 0) {
    return 'Running';
  }
  return 'Pending';
}

export function extractBackupImageUrl(job: V1Job): string | undefined {
  const containers = job.spec?.template?.spec?.containers;
  if (!containers || containers.length === 0) {
    return undefined;
  }

  const backupContainer = containers[0];
  const envVars = backupContainer.env;
  if (!envVars) {
    return undefined;
  }

  const backupImageUrlEnv = envVars.find(env => env.name === 'BACKUP_IMAGE_URL');
  return backupImageUrlEnv?.value;
}

export function registerBackupJobWebSocket(instance: FastifyInstance) {
  instance.register(async server => {
    server.get(
      `${baseApiPath}/ws/backup-job/:namespace/:jobName`,
      { websocket: true },
      backupJobWebSocketHandler,
    );
  });
}

export function backupJobWebSocketHandler(ws: WebSocket, request: FastifyRequest): void {
  const { namespace, jobName } = request.params as IBackupJobParams;
  let lastPhase: BackupJobPhase | undefined;
  let stopWatch: (() => void) | undefined;

  function sendEvent(event: BackupJobEvent): void {
    if (ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(event));
    }
  }

  function handleJobUpdate(job: V1Job): void {
    const phase = determineJobPhase(job);

    if (phase === lastPhase) {
      return;
    }
    lastPhase = phase;

    const statusEvent: StatusUpdateEvent = {
      type: 'status-update',
      phase,
      startTime: job.status?.startTime?.toISOString(),
      completionTime: job.status?.completionTime?.toISOString(),
    };
    sendEvent(statusEvent);

    if (phase === 'Succeeded' || phase === 'Failed') {
      const completedEvent: CompletedEvent = {
        type: 'completed',
        status: phase === 'Succeeded' ? 'success' : 'failed',
      };

      if (phase === 'Succeeded') {
        completedEvent.backupImageUrl = extractBackupImageUrl(job);
      }

      if (phase === 'Failed') {
        const failedCondition = job.status?.conditions?.find(c => c.type === 'Failed');
        completedEvent.error = failedCondition?.message || 'Backup job failed';
      }

      sendEvent(completedEvent);
      cleanup();
      ws.close(1000, 'Job completed');
    }
  }

  function handleWatchError(error: unknown): void {
    logger.error(error, `Backup job watch error for ${namespace}/${jobName}`);
    sendEvent({
      type: 'completed',
      status: 'failed',
      error: 'Lost connection to job watcher',
    });
    cleanup();
    ws.close(1011, 'Watch error');
  }

  function cleanup(): void {
    stopWatch?.();
    stopWatch = undefined;
  }

  async function startWatching(): Promise<void> {
    try {
      const token = getServiceAccountToken();
      const kubeConfigProvider = new KubeConfigProvider();
      const kubeConfig = kubeConfigProvider.getKubeConfig(token);
      const watch = prepareCustomObjectWatch(kubeConfig);

      const path = `/apis/batch/v1/namespaces/${namespace}/jobs`;
      const queryParams = {
        watch: true,
        fieldSelector: `metadata.name=${jobName}`,
      };

      const abortController: AbortController = await watch.watch(
        path,
        queryParams,
        (eventPhase: string, apiObj: V1Job | V1Status) => {
          if (eventPhase === 'ERROR') {
            const status = apiObj as V1Status;
            logger.error(`Watch error for backup job ${namespace}/${jobName}: ${status.message}`);
            handleWatchError(new Error(status.message || 'Watch API error'));
            abortController.abort();
            return;
          }

          const job = apiObj as V1Job;
          handleJobUpdate(job);
        },
        (error: unknown) => {
          handleWatchError(error);
          abortController.abort();
        },
      );

      stopWatch = () => abortController.abort();
    } catch (error) {
      logger.error(error, `Failed to start watching backup job ${namespace}/${jobName}`);
      sendEvent({
        type: 'completed',
        status: 'failed',
        error: 'Failed to start job watcher',
      });
      ws.close(1011, 'Failed to start watcher');
    }
  }

  ws.on('close', () => {
    logger.info(`Backup job WebSocket closed for ${namespace}/${jobName}`);
    cleanup();
  });

  ws.on('error', (error: Error) => {
    logger.error(error, `Backup job WebSocket error for ${namespace}/${jobName}`);
    cleanup();
  });

  startWatching();
}
