/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

import { api, DEVWORKSPACE_BACKUP_ANNOTATIONS } from '@eclipse-che/common';
import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';

import { baseApiPath } from '@/constants/config';
import {
  devWorkspacePatchSchema,
  devworkspaceSchema,
  namespacedSchema,
  namespacedWorkspaceSchema,
} from '@/constants/schemas';
import { restParams } from '@/models';
import { getDevWorkspaceClient } from '@/routes/api/helpers/getDevWorkspaceClient';
import { getToken } from '@/routes/api/helpers/getToken';
import { getSchema } from '@/services/helpers';

const tags = ['Devworkspace'];

/**
 * Validates backup image URL format and namespace
 * Generated by Claude Sonnet 4.5
 *
 * @param imageUrl - The backup image URL to validate
 * @param namespace - The expected namespace for SSRF protection
 * @returns true if valid, throws error otherwise
 */
function validateBackupImageUrl(imageUrl: string, namespace: string): void {
  // Basic URL validation
  if (!imageUrl || imageUrl.trim().length === 0) {
    throw new Error('Backup image URL cannot be empty');
  }

  // Check for valid format: registry/namespace/image:tag
  const urlPattern = /^([a-z0-9.-]+(?::\d+)?)\/([\w.-]+)\/([\w.-]+)(?::[\w.-]+)?$/;
  const match = imageUrl.match(urlPattern);

  if (!match) {
    throw new Error(
      'Invalid backup image URL format. Expected format: registry/namespace/workspace:tag',
    );
  }

  const [, registry, urlNamespace] = match;

  // SSRF Protection: Validate that namespace in URL matches request namespace
  if (urlNamespace !== namespace) {
    throw new Error(
      `Namespace mismatch: URL namespace '${urlNamespace}' does not match request namespace '${namespace}'`,
    );
  }

  // Validate registry format (allow internal services and HTTPS)
  const trustedPatterns = [
    /^image-registry\.openshift-image-registry\.svc(?::\d+)?$/, // OpenShift internal registry
    /^[a-z0-9.-]+\.svc(?::\d+)?$/, // Kubernetes service
    /^quay\.io$/,
    /^docker\.io$/,
    /^gcr\.io$/,
    /^ghcr\.io$/,
    /^localhost(?::\d+)?$/, // For local development
  ];

  const isTrusted = trustedPatterns.some(pattern => pattern.test(registry));
  if (!isTrusted) {
    throw new Error(
      `Untrusted registry '${registry}'. Only internal service registries and well-known public registries are allowed.`,
    );
  }
}

export function registerDevworkspacesRoutes(instance: FastifyInstance) {
  instance.register(async server => {
    server.get(
      `${baseApiPath}/namespace/:namespace/devworkspaces`,
      getSchema({ tags, params: namespacedSchema }),
      async function (request: FastifyRequest) {
        const { namespace } = request.params as restParams.INamespacedParams;
        const token = getToken(request);
        const { devworkspaceApi } = getDevWorkspaceClient(token);
        return await devworkspaceApi.listInNamespace(namespace);
      },
    );

    server.post(
      `${baseApiPath}/namespace/:namespace/devworkspaces`,
      getSchema({ tags, params: namespacedSchema, body: devworkspaceSchema }),
      async function (request: FastifyRequest, reply: FastifyReply) {
        const { devworkspace, restoreFromBackup, backupImageUrl } =
          request.body as restParams.IDevWorkspaceSpecParams;
        const { namespace } = request.params as restParams.INamespacedParams;
        if (!devworkspace.metadata) {
          devworkspace.metadata = {};
        }
        if (!devworkspace.metadata.annotations) {
          devworkspace.metadata.annotations = {};
        }
        devworkspace.metadata.namespace = namespace;

        const token = getToken(request);
        const { devworkspaceApi, backupApi } = getDevWorkspaceClient(token);

        // Handle restore from backup
        // Generated by Claude Sonnet 4.5
        if (restoreFromBackup) {
          let finalBackupImageUrl = backupImageUrl;

          // Auto-generate backup image URL if not provided
          if (!finalBackupImageUrl) {
            try {
              const backupConfig = await backupApi.getClusterBackupConfig();

              if (!backupConfig.enabled) {
                return reply.code(400).send({
                  message: 'Backup feature is not enabled on the cluster',
                });
              }

              if (!backupConfig.registry) {
                return reply.code(400).send({
                  message: 'Backup registry is not configured on the cluster',
                });
              }

              const workspaceName = devworkspace.metadata.name || 'workspace';
              finalBackupImageUrl = `${backupConfig.registry}/${namespace}/${workspaceName}:latest`;
            } catch (error) {
              return reply.code(500).send({
                message: 'Failed to retrieve backup configuration',
                error: error instanceof Error ? error.message : 'Unknown error',
              });
            }
          }

          // Validate backup image URL (format + SSRF protection)
          try {
            validateBackupImageUrl(finalBackupImageUrl, namespace);
          } catch (error) {
            return reply.code(400).send({
              message: 'Invalid backup image URL',
              error: error instanceof Error ? error.message : 'Unknown error',
            });
          }

          // Set restore config on spec.template.attributes (DWO reads from here, not annotations)
          const spec = devworkspace.spec ?? ({ started: false } as any);
          devworkspace.spec = spec;
          const template = spec.template ?? ({} as any);
          spec.template = template;
          const attributes = template.attributes ?? {};
          template.attributes = attributes;
          attributes[DEVWORKSPACE_BACKUP_ANNOTATIONS.RESTORE_WORKSPACE] = 'true';
          attributes[DEVWORKSPACE_BACKUP_ANNOTATIONS.RESTORE_SOURCE_IMAGE] = finalBackupImageUrl;
        }

        const { headers, devWorkspace } = await devworkspaceApi.create(devworkspace, namespace);

        reply.headers(headers).send(devWorkspace);
      },
    );

    server.get(
      `${baseApiPath}/namespace/:namespace/devworkspaces/:workspaceName`,
      getSchema({ tags, params: namespacedWorkspaceSchema }),
      async function (request: FastifyRequest) {
        const { namespace, workspaceName } =
          request.params as restParams.INamespacedWorkspaceParams;
        const token = getToken(request);
        const { devworkspaceApi } = getDevWorkspaceClient(token);
        return devworkspaceApi.getByName(namespace, workspaceName);
      },
    );

    server.patch(
      `${baseApiPath}/namespace/:namespace/devworkspaces/:workspaceName`,
      getSchema({ tags, params: namespacedWorkspaceSchema, body: devWorkspacePatchSchema }),
      async function (request: FastifyRequest, reply: FastifyReply) {
        const { namespace, workspaceName } =
          request.params as restParams.INamespacedWorkspaceParams;
        const patch = request.body as api.IPatch[];
        const token = getToken(request);
        const { devworkspaceApi } = getDevWorkspaceClient(token);
        const { headers, devWorkspace } = await devworkspaceApi.patch(
          namespace,
          workspaceName,
          patch,
        );

        reply.headers(headers).send(devWorkspace);
      },
    );

    server.delete(
      `${baseApiPath}/namespace/:namespace/devworkspaces/:workspaceName`,
      getSchema({
        tags,
        params: namespacedWorkspaceSchema,
        response: {
          204: {
            description: 'The DevWorkspace is successfully marked for deletion',
            type: 'null',
          },
        },
      }),
      async function (request: FastifyRequest, reply: FastifyReply) {
        const { namespace, workspaceName } =
          request.params as restParams.INamespacedWorkspaceParams;
        const token = getToken(request);
        const { devworkspaceApi } = getDevWorkspaceClient(token);

        await devworkspaceApi.delete(namespace, workspaceName);

        reply.code(204).send();
      },
    );
  });
}
