/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BACKUP_ERROR_CODES } from '@eclipse-che/common';
import { V1JobCondition } from '@kubernetes/client-node';
import { FastifyInstance, FastifyRequest } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { createError } from '@/devworkspaceClient/services/helpers/createError';
import { prepareBatchV1API } from '@/devworkspaceClient/services/helpers/prepareBatchV1API';
import { restParams } from '@/models';
import { getServiceAccountToken } from '@/routes/api/helpers/getServiceAccountToken';
import { getSchema } from '@/services/helpers';
import { KubeConfigProvider } from '@/services/kubeclient/kubeConfigProvider';

const tags = ['Job'];

interface IJobStatusParams extends restParams.INamespacedParams {
  jobName: string;
}

const jobStatusParamsSchema = {
  type: 'object',
  required: ['namespace', 'jobName'],
  properties: {
    namespace: { type: 'string' },
    jobName: { type: 'string' },
  },
} as const;

interface IJobListQuery {
  labelSelector?: string;
}

const jobListQuerySchema = {
  type: 'object',
  properties: {
    labelSelector: { type: 'string' },
  },
} as const;

const namespacedSchema = {
  type: 'object',
  required: ['namespace'],
  properties: {
    namespace: { type: 'string' },
  },
} as const;

export function registerJobsRoutes(instance: FastifyInstance) {
  instance.register(async server => {
    // Route 1: Get job status
    server.get(
      `${baseApiPath}/namespace/:namespace/jobs/:jobName/status`,
      getSchema({ tags, params: jobStatusParamsSchema }),
      async function (request: FastifyRequest) {
        const { namespace, jobName } = request.params as IJobStatusParams;

        try {
          const token = getServiceAccountToken();
          const kubeConfigProvider = new KubeConfigProvider();
          const kubeConfig = kubeConfigProvider.getKubeConfig(token);
          const batchV1API = prepareBatchV1API(kubeConfig);

          // Query Kubernetes Job status
          const jobStatusResponse = await batchV1API.readNamespacedJobStatus({
            name: jobName,
            namespace,
          });

          const job = (jobStatusResponse as any).body;

          // Determine phase based on job status
          let phase: 'Pending' | 'Running' | 'Succeeded' | 'Failed' = 'Pending';

          if (job.status?.succeeded && job.status.succeeded > 0) {
            phase = 'Succeeded';
          } else if (job.status?.failed && job.status.failed > 0) {
            phase = 'Failed';
          } else if (job.status?.active && job.status.active > 0) {
            phase = 'Running';
          }

          // Extract relevant status information
          const response = {
            phase,
            startTime: job.status?.startTime?.toISOString(),
            completionTime: job.status?.completionTime?.toISOString(),
            conditions: job.status?.conditions?.map((condition: V1JobCondition) => ({
              type: condition.type,
              status: condition.status,
              reason: condition.reason,
              message: condition.message,
            })),
          };

          return response;
        } catch (e) {
          // Handle 404 Not Found specifically
          if ((e as any)?.response?.statusCode === 404) {
            throw createError(
              e,
              BACKUP_ERROR_CODES.JOB_NOT_FOUND,
              `Job '${jobName}' not found in namespace '${namespace}'`,
            );
          }

          // Generic error for other failures
          throw createError(
            e,
            BACKUP_ERROR_CODES.JOB_API_ERROR,
            `Unable to get job status for '${jobName}'`,
          );
        }
      },
    );

    // Route 2: List jobs in namespace (with optional label filter)
    server.get(
      `${baseApiPath}/namespace/:namespace/jobs`,
      getSchema({ tags, params: namespacedSchema, querystring: jobListQuerySchema }),
      async function (request: FastifyRequest) {
        const { namespace } = request.params as restParams.INamespacedParams;
        const { labelSelector } = request.query as IJobListQuery;

        try {
          const token = getServiceAccountToken();
          const kubeConfigProvider = new KubeConfigProvider();
          const kubeConfig = kubeConfigProvider.getKubeConfig(token);
          const batchV1API = prepareBatchV1API(kubeConfig);

          // List jobs in namespace with optional label filter
          const jobsResponse = await batchV1API.listNamespacedJob({
            namespace,
            labelSelector,
          });

          const jobs = (jobsResponse as any).body.items;

          // Transform to simplified response format
          const response = jobs.map((job: any) => ({
            name: job.metadata.name,
            namespace: job.metadata.namespace,
            status: job.status?.succeeded
              ? 'Succeeded'
              : job.status?.failed
                ? 'Failed'
                : job.status?.active
                  ? 'Running'
                  : 'Pending',
            startTime: job.status?.startTime?.toISOString(),
            completionTime: job.status?.completionTime?.toISOString(),
            succeeded: job.status?.succeeded || 0,
            failed: job.status?.failed || 0,
          }));

          return response;
        } catch (e) {
          throw createError(
            e,
            BACKUP_ERROR_CODES.JOB_API_ERROR,
            `Unable to list jobs in namespace '${namespace}'`,
          );
        }
      },
    );

    // Route 3: Delete completed job
    server.delete(
      `${baseApiPath}/namespace/:namespace/jobs/:jobName`,
      getSchema({ tags, params: jobStatusParamsSchema }),
      async function (request: FastifyRequest) {
        const { namespace, jobName } = request.params as IJobStatusParams;

        try {
          const token = getServiceAccountToken();
          const kubeConfigProvider = new KubeConfigProvider();
          const kubeConfig = kubeConfigProvider.getKubeConfig(token);
          const batchV1API = prepareBatchV1API(kubeConfig);

          // Delete job with propagationPolicy to clean up pods
          await batchV1API.deleteNamespacedJob({
            name: jobName,
            namespace,
            propagationPolicy: 'Background',
          });

          return { message: `Job '${jobName}' deleted successfully` };
        } catch (e) {
          // Handle 404 Not Found specifically
          if ((e as any)?.response?.statusCode === 404) {
            throw createError(
              e,
              BACKUP_ERROR_CODES.JOB_NOT_FOUND,
              `Job '${jobName}' not found in namespace '${namespace}'`,
            );
          }

          // Generic error for other failures
          throw createError(
            e,
            BACKUP_ERROR_CODES.JOB_API_ERROR,
            `Unable to delete job '${jobName}'`,
          );
        }
      },
    );
  });
}
