/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { Icon, Label, LabelProps } from '@patternfly/react-core';
import {
  CheckCircleIcon,
  ExclamationCircleIcon,
  InfoCircleIcon,
  OutlinedClockIcon,
} from '@patternfly/react-icons';
import React from 'react';

import styles from '@/components/AgentStatusBadge/index.module.css';
import { CheTooltip } from '@/components/CheTooltip';

export type AgentStatusType = 'active' | 'idle' | 'error' | 'unknown';

export type Props = {
  status: AgentStatusType;
  agentName?: string;
  lastActivity?: string;
};

const AGENT_STATUS_LABELS: Record<AgentStatusType, string> = {
  active: 'Active',
  idle: 'Idle',
  error: 'Error',
  unknown: 'Unknown',
};

const STATUS_COLORS: Record<AgentStatusType, LabelProps['color']> = {
  active: 'green',
  idle: 'grey',
  error: 'red',
  unknown: 'grey',
};

function getStatusIcon(status: AgentStatusType): React.ReactElement {
  switch (status) {
    case 'active':
      return (
        <Icon status="success" isInline>
          <CheckCircleIcon />
        </Icon>
      );
    case 'idle':
      return (
        <Icon status="custom" isInline>
          <OutlinedClockIcon />
        </Icon>
      );
    case 'error':
      return (
        <Icon status="danger" isInline>
          <ExclamationCircleIcon />
        </Icon>
      );
    case 'unknown':
      return (
        <Icon status="info" isInline>
          <InfoCircleIcon />
        </Icon>
      );
  }
}

function getTooltipContent(
  status: AgentStatusType,
  agentName?: string,
  lastActivity?: string,
): React.ReactElement {
  const lines: string[] = [`Status: ${AGENT_STATUS_LABELS[status]}`];

  if (agentName) {
    lines.push(`Agent: ${agentName}`);
  }

  if (lastActivity) {
    lines.push(`Last activity: ${lastActivity}`);
  }

  return (
    <div data-testid="agent-status-tooltip-content">
      {lines.map((line, index) => (
        <div key={index}>{line}</div>
      ))}
    </div>
  );
}

export function AgentStatusBadge(props: Props): React.ReactElement {
  const { status, agentName, lastActivity } = props;

  const color = STATUS_COLORS[status];
  const icon = getStatusIcon(status);
  const tooltipContent = getTooltipContent(status, agentName, lastActivity);

  const className = styles.agentStatusBadge;

  const statusLabel = AGENT_STATUS_LABELS[status];

  return (
    <CheTooltip content={tooltipContent}>
      <Label
        className={className}
        color={color}
        icon={icon}
        data-testid="agent-status-badge"
        aria-label={`Agent status: ${statusLabel}`}
      >
        {statusLabel}
      </Label>
    </CheTooltip>
  );
}
