/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { Icon, Label, LabelProps } from '@patternfly/react-core';
import {
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InProgressIcon,
  OutlinedClockIcon,
} from '@patternfly/react-icons';
import React from 'react';

import styles from '@/components/AgentStatusBadge/index.module.css';
import { AgentStatus } from '@/services/devfileApi/devWorkspace/metadata';

export type Props = {
  status: AgentStatus | undefined;
};

const AGENT_STATUS_LABELS: Record<AgentStatus, string> = {
  running: 'Running',
  finished: 'Finished',
  lost: 'Lost',
  idle: 'Idle',
};

const STATUS_COLORS: Record<AgentStatus, LabelProps['color']> = {
  running: 'blue',
  finished: 'green',
  lost: 'orange',
  idle: 'grey',
};

function getStatusIcon(status: AgentStatus | undefined): React.ReactElement {
  switch (status) {
    case 'running':
      return (
        <Icon status="info" isInline>
          <InProgressIcon className={styles.rotate} aria-label="Agent running" />
        </Icon>
      );
    case 'finished':
      return (
        <Icon status="success" isInline>
          <CheckCircleIcon />
        </Icon>
      );
    case 'lost':
      return (
        <Icon status="warning" isInline>
          <ExclamationTriangleIcon />
        </Icon>
      );
    case 'idle':
      return (
        <Icon status="custom" isInline>
          <OutlinedClockIcon />
        </Icon>
      );
    default:
      return (
        <Icon status="custom" isInline>
          <OutlinedClockIcon />
        </Icon>
      );
  }
}

export function AgentStatusBadge(props: Props): React.ReactElement {
  const { status } = props;

  const statusLabel =
    status && status in AGENT_STATUS_LABELS ? AGENT_STATUS_LABELS[status] : 'Unknown';
  const color = status && status in STATUS_COLORS ? STATUS_COLORS[status] : 'grey';
  const icon = getStatusIcon(status);

  const className = styles.agentStatusBadge;

  return (
    <Label
      className={className}
      color={color}
      icon={icon}
      data-testid="agent-status-badge"
      aria-label={`Agent status: ${statusLabel}`}
    >
      {statusLabel}
    </Label>
  );
}
