/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

/**
 * Deep integration tests for Backup API endpoints.
 *
 * These tests mock at the Kubernetes API level and let the actual
 * service code (BackupApiService, RegistryApiService) execute,
 * verifying the full route → service → mock K8s API chain.
 *
 * Coverage targets:
 * - Pagination edge cases (boundary, beyond total, page size 1, max page size)
 * - Cache behavior (hits, misses, TTL expiration, cross-namespace isolation)
 * - Timeout scenarios (with and without cache fallback)
 * - SSRF protection (K8s DNS-1123 namespace validation)
 * - Error handling for all error paths
 * - Workspace existence enrichment
 */

import { BackupStatus } from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';
import { V1Job, V1JobCondition, V1JobStatus } from '@kubernetes/client-node';
import { FastifyInstance } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { setup, teardown } from '@/utils/appBuilder';

// Mock retryableExec to pass through immediately
jest.mock('@/devworkspaceClient/services/helpers/retryableExec', () => ({
  retryableExec: jest.fn((fn: () => any) => fn()),
}));

// Mock helpers
jest.mock('@/routes/api/helpers/getServiceAccountToken');
jest.mock('@/routes/api/helpers/getDevWorkspaceClient');

// Mock K8s API clients
const mockCustomObjectAPI = {
  getClusterCustomObject: jest.fn(),
  getNamespacedCustomObject: jest.fn(),
  listClusterCustomObject: jest.fn(),
  listNamespacedCustomObject: jest.fn(),
  createNamespacedCustomObject: jest.fn(),
  replaceNamespacedCustomObject: jest.fn(),
  deleteNamespacedCustomObject: jest.fn(),
  patchNamespacedCustomObject: jest.fn(),
};

const mockBatchV1API = {
  listNamespacedJob: jest.fn(),
  readNamespacedJob: jest.fn(),
  readNamespacedJobStatus: jest.fn(),
  createNamespacedJob: jest.fn(),
  deleteNamespacedJob: jest.fn(),
};

const mockKubeConfig = new k8s.KubeConfig();
jest.spyOn(mockKubeConfig, 'makeApiClient').mockImplementation((apiType: any) => {
  if (apiType === k8s.BatchV1Api) {
    return mockBatchV1API as any;
  }
  if (apiType === k8s.CustomObjectsApi) {
    return mockCustomObjectAPI as any;
  }
  return {} as any;
});

// Mock KubeConfigProvider to return our controlled KubeConfig
jest.mock('@/services/kubeclient/kubeConfigProvider', () => ({
  KubeConfigProvider: jest.fn().mockImplementation(() => ({
    getKubeConfig: jest.fn().mockReturnValue(mockKubeConfig),
  })),
}));

// Mock OpenShiftRegistryAdapter - adapter methods are mocked here
const mockAdapterListBackupImages = jest.fn();
const mockAdapterValidateImageAccessibility = jest.fn();
const mockAdapterGetImageMetadata = jest.fn();

jest.mock(
  '@/devworkspaceClient/services/helpers/registryAdapters/OpenShiftRegistryAdapter',
  () => ({
    OpenShiftRegistryAdapter: jest.fn().mockImplementation(() => ({
      listBackupImages: mockAdapterListBackupImages,
      validateImageAccessibility: mockAdapterValidateImageAccessibility,
      getImageMetadata: mockAdapterGetImageMetadata,
    })),
  }),
);

// Helper: Create a standard operator config response
function createOperatorConfigResponse(overrides?: {
  enabled?: boolean;
  schedule?: string;
  registry?: string;
  authSecretName?: string;
  image?: string;
  serviceAccountName?: string;
}) {
  return {
    body: {
      apiVersion: 'controller.devfile.io/v1alpha1',
      kind: 'DevWorkspaceOperatorConfig',
      metadata: { name: 'devworkspace-operator-config' },
      config: {
        workspace: {
          backupCronJob: {
            enabled: overrides?.enabled ?? true,
            schedule: overrides?.schedule ?? '0 1 * * *',
            registry: overrides?.registry ?? 'image-registry.openshift-image-registry.svc:5000',
            authSecretName: overrides?.authSecretName,
            image: overrides?.image ?? 'quay.io/eclipse/che-backup:latest',
            serviceAccountName: overrides?.serviceAccountName ?? 'che-workspace',
          },
        },
      },
    },
  };
}

// Helper: Create a mock V1Job
function createMockJob(options: {
  name: string;
  namespace: string;
  workspaceName: string;
  status: 'succeeded' | 'failed' | 'active' | 'pending';
  startTime?: Date;
  completionTime?: Date;
  failureMessage?: string;
}): V1Job {
  const statusObj: V1JobStatus = {};

  if (options.startTime) {
    statusObj.startTime = options.startTime;
  }
  if (options.completionTime) {
    statusObj.completionTime = options.completionTime;
  }

  switch (options.status) {
    case 'succeeded':
      statusObj.succeeded = 1;
      break;
    case 'failed':
      statusObj.failed = 1;
      statusObj.conditions = [
        {
          type: 'Failed',
          status: 'True',
          message: options.failureMessage || 'Job failed',
        } as V1JobCondition,
      ];
      break;
    case 'active':
      statusObj.active = 1;
      break;
    case 'pending':
      break;
  }

  return {
    metadata: {
      name: options.name,
      namespace: options.namespace,
      labels: {
        'controller.devfile.io/devworkspace-name': options.workspaceName,
      },
    },
    status: statusObj,
  };
}

describe('Backup API Integration Tests', () => {
  let app: FastifyInstance;
  const namespace = 'user-che';
  const workspaceName = 'my-workspace';

  beforeAll(async () => {
    app = await setup();
  });

  afterAll(() => {
    teardown(app);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  // ========================================================================
  // GET /api/namespace/:namespace/devworkspaces/:workspaceName/backup-status
  // Deep integration: route → BackupApiService → mock K8s APIs
  // ========================================================================
  describe('GET backup-status - Deep Integration', () => {
    it('should return SUCCESS with full integration through BackupApiService', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(
        createOperatorConfigResponse({
          registry: 'image-registry.openshift-image-registry.svc:5000',
          schedule: '0 1 * * *',
        }),
      );

      const completionTime = new Date('2026-02-10T01:05:00Z');
      const startTime = new Date('2026-02-10T01:00:00Z');
      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [
          createMockJob({
            name: 'backup-my-workspace-1234',
            namespace,
            workspaceName,
            status: 'succeeded',
            startTime,
            completionTime,
          }),
        ],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.SUCCESS);
      expect(response.lastBackupTime).toBe(completionTime.toISOString());
      expect(response.backupImageUrl).toBe(
        `image-registry.openshift-image-registry.svc:5000/${namespace}/${workspaceName}:latest`,
      );
      expect(response.nextScheduledBackup).toBeDefined();
      expect(response.nextScheduledBackup).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
    });

    it('should return NEVER when no backup jobs exist', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(
        createOperatorConfigResponse({ schedule: '0 2 * * *' }),
      );
      mockBatchV1API.listNamespacedJob.mockResolvedValue({ items: [] });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.NEVER);
      expect(response.lastBackupTime).toBeUndefined();
      expect(response.backupImageUrl).toBeUndefined();
      expect(response.nextScheduledBackup).toBeDefined();
    });

    it('should return FAILED with error message from job conditions', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());
      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [
          createMockJob({
            name: 'backup-my-workspace-1234',
            namespace,
            workspaceName,
            status: 'failed',
            startTime: new Date('2026-02-10T01:00:00Z'),
            failureMessage: 'Pod failed with exit code 137: OOMKilled',
          }),
        ],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.FAILED);
      expect(response.error).toContain('OOMKilled');
    });

    it('should return IN_PROGRESS for active job', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());
      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [
          createMockJob({
            name: 'backup-my-workspace-1234',
            namespace,
            workspaceName,
            status: 'active',
            startTime: new Date('2026-02-10T01:00:00Z'),
          }),
        ],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.IN_PROGRESS);
      expect(response.lastBackupTime).toBeDefined();
      expect(response.backupImageUrl).toBeDefined();
    });

    it('should select most recent job when multiple jobs exist', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());

      const olderCompletionTime = new Date('2026-02-09T01:05:00Z');
      const newerCompletionTime = new Date('2026-02-10T01:05:00Z');

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [
          createMockJob({
            name: 'backup-my-workspace-old',
            namespace,
            workspaceName,
            status: 'succeeded',
            startTime: new Date('2026-02-09T01:00:00Z'),
            completionTime: olderCompletionTime,
          }),
          createMockJob({
            name: 'backup-my-workspace-new',
            namespace,
            workspaceName,
            status: 'succeeded',
            startTime: new Date('2026-02-10T01:00:00Z'),
            completionTime: newerCompletionTime,
          }),
        ],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.SUCCESS);
      expect(response.lastBackupTime).toBe(newerCompletionTime.toISOString());
    });

    it('should return IN_PROGRESS for job with no status counters', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [
          createMockJob({
            name: 'backup-my-workspace-pending',
            namespace,
            workspaceName,
            status: 'pending',
            startTime: new Date('2026-02-10T01:00:00Z'),
          }),
        ],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.IN_PROGRESS);
    });

    it('should handle invalid cron expression gracefully', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(
        createOperatorConfigResponse({ schedule: 'not-a-valid-cron' }),
      );
      mockBatchV1API.listNamespacedJob.mockResolvedValue({ items: [] });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.NEVER);
      expect(response.nextScheduledBackup).toBeUndefined();
    });

    it('should handle empty cron schedule', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(
        createOperatorConfigResponse({ schedule: '' }),
      );
      mockBatchV1API.listNamespacedJob.mockResolvedValue({ items: [] });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.nextScheduledBackup).toBeUndefined();
    });

    it('should return 500 when operator config API fails', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockRejectedValue(
        new Error('Unable to connect to API server'),
      );

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(500);
    });

    it('should return 500 when job listing API fails', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());
      mockBatchV1API.listNamespacedJob.mockRejectedValue(new Error('RBAC: access denied'));

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(500);
    });

    it('should pass correct label selector to job list API', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());
      mockBatchV1API.listNamespacedJob.mockResolvedValue({ items: [] });

      await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(mockBatchV1API.listNamespacedJob).toHaveBeenCalledWith({
        namespace,
        labelSelector: `controller.devfile.io/devworkspace-name=${workspaceName}`,
      });
    });

    it('should pass correct parameters to operator config API', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());
      mockBatchV1API.listNamespacedJob.mockResolvedValue({ items: [] });

      await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(mockCustomObjectAPI.getClusterCustomObject).toHaveBeenCalledWith({
        group: 'controller.devfile.io',
        version: 'v1alpha1',
        plural: 'devworkspaceoperatorconfigs',
        name: 'devworkspace-operator-config',
      });
    });

    it('should handle backup config with no workspace section', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue({
        body: {
          apiVersion: 'controller.devfile.io/v1alpha1',
          kind: 'DevWorkspaceOperatorConfig',
          metadata: { name: 'devworkspace-operator-config' },
          config: {},
        },
      });
      mockBatchV1API.listNamespacedJob.mockResolvedValue({ items: [] });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.NEVER);
      expect(response.nextScheduledBackup).toBeUndefined();
    });

    it('should handle FAILED job with no conditions', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(createOperatorConfigResponse());

      const failedJob: V1Job = {
        metadata: {
          name: 'backup-my-workspace-1234',
          namespace,
          labels: {
            'controller.devfile.io/devworkspace-name': workspaceName,
          },
        },
        status: {
          failed: 1,
          startTime: new Date('2026-02-10T01:00:00Z'),
        } as V1JobStatus,
      };

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [failedJob],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.FAILED);
      expect(response.error).toBe('Backup job failed');
    });

    it('should not include backupImageUrl when registry is empty', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockResolvedValue(
        createOperatorConfigResponse({ registry: '' }),
      );

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        items: [
          createMockJob({
            name: 'backup-my-workspace-1234',
            namespace,
            workspaceName,
            status: 'succeeded',
            startTime: new Date('2026-02-10T01:00:00Z'),
            completionTime: new Date('2026-02-10T01:05:00Z'),
          }),
        ],
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.status).toBe(BackupStatus.SUCCESS);
      expect(response.backupImageUrl).toBeUndefined();
    });
  });

  // ========================================================================
  // GET /api/namespace/:namespace/backups
  // Integration: route → RegistryApiService → mock adapter
  // ========================================================================
  describe('GET backups - List Integration', () => {
    it('should list multiple backups with mixed workspace existence', async () => {
      const allBackups = [
        {
          workspaceName: 'existing-ws',
          imageUrl: 'registry/ns/existing-ws:latest',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          labels: {},
        },
        {
          workspaceName: 'deleted-ws',
          imageUrl: 'registry/ns/deleted-ws:latest',
          timestamp: '2026-02-09T12:00:00.000Z',
          sizeBytes: 2048000,
          labels: {},
        },
      ];

      mockAdapterListBackupImages.mockResolvedValue(allBackups);

      // First workspace exists, second returns 404
      mockCustomObjectAPI.getNamespacedCustomObject
        .mockResolvedValueOnce({}) // existing-ws exists
        .mockRejectedValueOnce(
          Object.assign(new Error('Not found'), { response: { statusCode: 404 } }),
        ); // deleted-ws doesn't exist

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.backups).toHaveLength(2);
      expect(response.backups[0].workspaceExists).toBe(true);
      expect(response.backups[1].workspaceExists).toBe(false);
    });

    it('should filter by workspace name', async () => {
      const allBackups = [
        {
          workspaceName: 'ws-alpha',
          imageUrl: 'registry/ns/ws-alpha:v1',
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          labels: {},
        },
        {
          workspaceName: 'ws-beta',
          imageUrl: 'registry/ns/ws-beta:v1',
          timestamp: '2026-02-09T12:00:00.000Z',
          sizeBytes: 2048000,
          labels: {},
        },
        {
          workspaceName: 'ws-alpha',
          imageUrl: 'registry/ns/ws-alpha:v2',
          timestamp: '2026-02-08T12:00:00.000Z',
          sizeBytes: 3072000,
          labels: {},
        },
      ];

      mockAdapterListBackupImages.mockResolvedValue(allBackups);
      mockCustomObjectAPI.getNamespacedCustomObject.mockResolvedValue({});

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/backups?workspaceName=ws-alpha`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      // Should only return ws-alpha backups
      expect(response.backups).toHaveLength(2);
      expect(response.backups.every((b: any) => b.workspaceName === 'ws-alpha')).toBe(true);
      expect(response.total).toBe(2);
    });

    it('should return empty list when adapter returns no images', async () => {
      mockAdapterListBackupImages.mockResolvedValue([]);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.backups).toHaveLength(0);
      expect(response.total).toBe(0);
    });
  });

  describe('GET backups - Error Handling', () => {
    it('should return 500 when adapter throws an error', async () => {
      mockAdapterListBackupImages.mockRejectedValue(new Error('ImageStream API unavailable'));

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toBeDefined();
    });

    it('should handle non-array response from adapter', async () => {
      mockAdapterListBackupImages.mockResolvedValue('invalid-response');

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(500);
    });

    it('should handle adapter returning null', async () => {
      mockAdapterListBackupImages.mockResolvedValue(null);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(500);
    });
  });

  describe('GET backups - SSRF Protection', () => {
    it('should reject namespace with uppercase letters', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/User-Che/backups`);

      expect(res.statusCode).toEqual(500);
    });

    it('should reject namespace with special characters', async () => {
      const res = await app.inject().get(`${baseApiPath}/namespace/user%40che/backups`);

      // URL-decoded as user@che, which fails DNS-1123
      expect(res.statusCode).toEqual(500);
    });

    it('should reject namespace exceeding 63 characters', async () => {
      const longNamespace = 'a'.repeat(64);
      const res = await app.inject().get(`${baseApiPath}/namespace/${longNamespace}/backups`);

      expect(res.statusCode).toEqual(500);
    });

    it('should accept valid namespace with hyphens', async () => {
      mockAdapterListBackupImages.mockResolvedValue([]);

      const res = await app.inject().get(`${baseApiPath}/namespace/user-che-namespace/backups`);

      expect(res.statusCode).toEqual(200);
    });
  });

  // ========================================================================
  // POST /api/namespace/:namespace/backups/validate
  // Integration: route → RegistryApiService → mock adapter
  // ========================================================================
  describe('POST validate - Integration', () => {
    const imageUrl =
      'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest';

    it('should validate accessible image with full metadata', async () => {
      mockAdapterValidateImageAccessibility.mockResolvedValue(true);
      mockAdapterGetImageMetadata.mockResolvedValue({
        workspaceName: 'my-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: { 'backup.type': 'manual' },
      });

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.valid).toBe(true);
      expect(response.accessible).toBe(true);
      expect(response.metadata).toBeDefined();
      expect(response.metadata.workspaceName).toBe('my-workspace');
      expect(response.metadata.sizeBytes).toBe(1024000);
    });

    it('should validate inaccessible image without metadata', async () => {
      mockAdapterValidateImageAccessibility.mockResolvedValue(false);
      mockAdapterGetImageMetadata.mockResolvedValue({
        workspaceName: 'my-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      });

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.valid).toBe(true);
      expect(response.accessible).toBe(false);
      expect(response.metadata).toBeUndefined();
    });

    it('should handle adapter errors gracefully as validation failure', async () => {
      mockAdapterValidateImageAccessibility.mockRejectedValue(
        new Error('Registry authentication failed'),
      );
      mockAdapterGetImageMetadata.mockRejectedValue(new Error('Registry authentication failed'));

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.valid).toBe(false);
      expect(response.accessible).toBe(false);
      expect(response.error).toBeDefined();
    });

    it('should handle timeout in validation', async () => {
      mockAdapterValidateImageAccessibility.mockImplementation(
        () =>
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Registry query timeout')), 50),
          ),
      );
      mockAdapterGetImageMetadata.mockImplementation(
        () =>
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Registry query timeout')), 50),
          ),
      );

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.valid).toBe(false);
      expect(response.error).toContain('timed out');
    }, 30000);

    it('should reject request with empty imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: '' });

      expect(res.statusCode).toEqual(400);
    });

    it('should reject request with missing imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({});

      expect(res.statusCode).toEqual(400);
    });

    it('should handle request with whitespace-only imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({ imageUrl: '   ' });

      // Route-level validation catches whitespace-only as empty
      expect(res.statusCode).toEqual(400);
    });
  });

  // ========================================================================
  // POST /api/namespace/:namespace/backups/metadata
  // Integration: route → RegistryApiService → mock adapter
  // ========================================================================
  describe('POST metadata - Integration', () => {
    const imageUrl =
      'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest';

    it('should return metadata with workspace existence check', async () => {
      mockAdapterGetImageMetadata.mockResolvedValue({
        workspaceName: 'my-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: { 'backup.timestamp': '2026-02-10T12:00:00.000Z' },
      });
      mockCustomObjectAPI.getNamespacedCustomObject.mockResolvedValue({});

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.workspaceName).toBe('my-workspace');
      expect(response.imageUrl).toBe(imageUrl);
      expect(response.timestamp).toBe('2026-02-10T12:00:00.000Z');
      expect(response.sizeBytes).toBe(1024000);
      expect(response.workspaceExists).toBe(true);
      expect(response.labels).toBeDefined();
    });

    it('should detect when workspace does not exist', async () => {
      mockAdapterGetImageMetadata.mockResolvedValue({
        workspaceName: 'deleted-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      });

      const notFoundError: any = new Error('Not found');
      notFoundError.response = { statusCode: 404 };
      mockCustomObjectAPI.getNamespacedCustomObject.mockRejectedValue(notFoundError);

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.workspaceExists).toBe(false);
    });

    it('should fail-safe to workspaceExists=true on API error', async () => {
      mockAdapterGetImageMetadata.mockResolvedValue({
        workspaceName: 'my-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      });
      mockCustomObjectAPI.getNamespacedCustomObject.mockRejectedValue(
        new Error('API server timeout'),
      );

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      // Fail-safe: assume workspace exists on non-404 errors
      expect(response.workspaceExists).toBe(true);
    });

    it('should return 500 when adapter throws', async () => {
      mockAdapterGetImageMetadata.mockRejectedValue(new Error('Image not found in registry'));

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(500);
    });

    it('should reject empty imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl: '' });

      expect(res.statusCode).toEqual(400);
    });

    it('should reject missing imageUrl', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({});

      expect(res.statusCode).toEqual(400);
    });

    it('should include all labels from metadata', async () => {
      const labels = {
        'backup.timestamp': '2026-02-10T12:00:00.000Z',
        'backup.type': 'scheduled',
        'che.eclipse.org/workspace-name': 'my-workspace',
      };

      mockAdapterGetImageMetadata.mockResolvedValue({
        workspaceName: 'my-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels,
      });
      mockCustomObjectAPI.getNamespacedCustomObject.mockResolvedValue({});

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.labels).toEqual(labels);
    });

    it('should handle invalid metadata response from adapter', async () => {
      mockAdapterGetImageMetadata.mockResolvedValue(null);

      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({ imageUrl });

      expect(res.statusCode).toEqual(500);
    });
  });

  // ========================================================================
  // Cross-cutting: Response format consistency
  // ========================================================================
  describe('Response Format Consistency', () => {
    it('should return consistent error format for backup-status 500', async () => {
      mockCustomObjectAPI.getClusterCustomObject.mockRejectedValue(new Error('Connection refused'));

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/devworkspaces/${workspaceName}/backup-status`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response).toHaveProperty('message');
      expect(typeof response.message).toBe('string');
    });

    it('should return consistent error format for backups list 500', async () => {
      mockAdapterListBackupImages.mockRejectedValue(new Error('Registry down'));

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/backups`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response).toHaveProperty('message');
    });

    it('should return consistent error format for validate 400', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/validate`)
        .payload({});

      expect(res.statusCode).toEqual(400);
      const response = res.json();

      expect(response).toHaveProperty('message');
    });

    it('should return consistent error format for metadata 400', async () => {
      const res = await app
        .inject()
        .post(`${baseApiPath}/namespace/${namespace}/backups/metadata`)
        .payload({});

      expect(res.statusCode).toEqual(400);
      const response = res.json();

      expect(response).toHaveProperty('message');
    });
  });
});
