/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { V1Job } from '@kubernetes/client-node';
import { FastifyRequest } from 'fastify';
import WebSocket from 'ws';

import {
  backupJobWebSocketHandler,
  CompletedEvent,
  determineJobPhase,
  extractBackupImageUrl,
  StatusUpdateEvent,
} from '@/routes/api/backupJobWebSocket';

// Mock retryableExec to avoid timeout issues
jest.mock('@/devworkspaceClient/services/helpers/retryableExec', () => ({
  retryableExec: jest.fn((fn: () => unknown) => fn()),
}));

// Mock logger
jest.mock('@/utils/logger', () => ({
  logger: {
    error: jest.fn(),
    info: jest.fn(),
    warn: jest.fn(),
  },
}));

// Mock getServiceAccountToken
jest.mock('@/routes/api/helpers/getServiceAccountToken', () => ({
  getServiceAccountToken: jest.fn().mockReturnValue('mock-token'),
}));

// Watch callback references for test control
let watchCallback: (eventPhase: string, apiObj: unknown) => void;
let watchErrorCallback: (error: unknown) => void;
const mockAbortController = { abort: jest.fn() };

// Mock prepareCustomObjectWatch
jest.mock('@/devworkspaceClient/services/helpers/prepareCustomObjectWatch', () => ({
  prepareCustomObjectWatch: jest.fn().mockReturnValue({
    config: {},
    watch: jest
      .fn()
      .mockImplementation(
        (
          _path: string,
          _queryParams: unknown,
          callback: (eventPhase: string, apiObj: unknown) => void,
          errorCallback: (error: unknown) => void,
        ) => {
          watchCallback = callback;
          watchErrorCallback = errorCallback;
          return Promise.resolve(mockAbortController);
        },
      ),
  }),
}));

// Mock KubeConfigProvider
jest.mock('@/services/kubeclient/kubeConfigProvider', () => ({
  KubeConfigProvider: jest.fn().mockImplementation(() => ({
    getKubeConfig: jest.fn().mockReturnValue({}),
  })),
}));

function createMockWs() {
  const handlers: Record<string, (...args: unknown[]) => void> = {};
  return {
    readyState: WebSocket.OPEN as number,
    send: jest.fn(),
    close: jest.fn(),
    on: jest.fn().mockImplementation((event: string, handler: (...args: unknown[]) => void) => {
      handlers[event] = handler;
    }),
    _handlers: handlers,
  };
}

function createMockRequest(namespace: string, jobName: string): FastifyRequest {
  return {
    params: { namespace, jobName },
  } as unknown as FastifyRequest;
}

describe('Backup Job WebSocket', () => {
  describe('determineJobPhase', () => {
    it('should return Succeeded when job has succeeded count > 0', () => {
      const job: Partial<V1Job> = {
        status: { succeeded: 1 },
      };
      expect(determineJobPhase(job as V1Job)).toBe('Succeeded');
    });

    it('should return Succeeded even when failed and active also present', () => {
      const job: Partial<V1Job> = {
        status: { succeeded: 1, failed: 2, active: 1 },
      };
      expect(determineJobPhase(job as V1Job)).toBe('Succeeded');
    });

    it('should return Failed when job has failed count > 0 and no succeeded', () => {
      const job: Partial<V1Job> = {
        status: { failed: 3 },
      };
      expect(determineJobPhase(job as V1Job)).toBe('Failed');
    });

    it('should return Failed when failed > 0 and active > 0 but no succeeded', () => {
      const job: Partial<V1Job> = {
        status: { failed: 1, active: 1 },
      };
      expect(determineJobPhase(job as V1Job)).toBe('Failed');
    });

    it('should return Running when job has active count > 0', () => {
      const job: Partial<V1Job> = {
        status: { active: 1 },
      };
      expect(determineJobPhase(job as V1Job)).toBe('Running');
    });

    it('should return Pending when job has empty status', () => {
      const job: Partial<V1Job> = {
        status: {},
      };
      expect(determineJobPhase(job as V1Job)).toBe('Pending');
    });

    it('should return Pending when job has no status', () => {
      const job: Partial<V1Job> = {};
      expect(determineJobPhase(job as V1Job)).toBe('Pending');
    });

    it('should return Pending when all status counts are 0', () => {
      const job: Partial<V1Job> = {
        status: { succeeded: 0, failed: 0, active: 0 },
      };
      expect(determineJobPhase(job as V1Job)).toBe('Pending');
    });
  });

  describe('extractBackupImageUrl', () => {
    it('should extract BACKUP_IMAGE_URL from job spec', () => {
      const job: Partial<V1Job> = {
        spec: {
          template: {
            spec: {
              containers: [
                {
                  name: 'backup',
                  image: 'backup-image:latest',
                  env: [
                    { name: 'WORKSPACE_NAME', value: 'my-workspace' },
                    {
                      name: 'BACKUP_IMAGE_URL',
                      value: 'registry.example.com/ns/workspace:12345',
                    },
                    { name: 'NAMESPACE', value: 'user-che' },
                  ],
                },
              ],
              restartPolicy: 'OnFailure',
            },
          },
        },
      };
      expect(extractBackupImageUrl(job as V1Job)).toBe('registry.example.com/ns/workspace:12345');
    });

    it('should return undefined when no containers exist', () => {
      const job: Partial<V1Job> = {
        spec: {
          template: {
            spec: {
              containers: [],
              restartPolicy: 'OnFailure',
            },
          },
        },
      };
      expect(extractBackupImageUrl(job as V1Job)).toBeUndefined();
    });

    it('should return undefined when containers is undefined', () => {
      const job: Partial<V1Job> = {
        spec: {
          template: {},
        },
      };
      expect(extractBackupImageUrl(job as V1Job)).toBeUndefined();
    });

    it('should return undefined when spec is undefined', () => {
      const job: Partial<V1Job> = {};
      expect(extractBackupImageUrl(job as V1Job)).toBeUndefined();
    });

    it('should return undefined when BACKUP_IMAGE_URL env var not found', () => {
      const job: Partial<V1Job> = {
        spec: {
          template: {
            spec: {
              containers: [
                {
                  name: 'backup',
                  image: 'backup-image:latest',
                  env: [
                    { name: 'WORKSPACE_NAME', value: 'my-workspace' },
                    { name: 'NAMESPACE', value: 'user-che' },
                  ],
                },
              ],
              restartPolicy: 'OnFailure',
            },
          },
        },
      };
      expect(extractBackupImageUrl(job as V1Job)).toBeUndefined();
    });

    it('should return undefined when container has no env vars', () => {
      const job: Partial<V1Job> = {
        spec: {
          template: {
            spec: {
              containers: [
                {
                  name: 'backup',
                  image: 'backup-image:latest',
                },
              ],
              restartPolicy: 'OnFailure',
            },
          },
        },
      };
      expect(extractBackupImageUrl(job as V1Job)).toBeUndefined();
    });
  });

  describe('backupJobWebSocketHandler', () => {
    const namespace = 'user-che';
    const jobName = 'backup-my-workspace-12345';

    let mockWs: ReturnType<typeof createMockWs>;

    beforeEach(() => {
      jest.clearAllMocks();
      mockAbortController.abort.mockClear();
      mockWs = createMockWs();
    });

    it('should register close and error event handlers', () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      expect(mockWs.on).toHaveBeenCalledWith('close', expect.any(Function));
      expect(mockWs.on).toHaveBeenCalledWith('error', expect.any(Function));
    });

    it('should start watching with correct path and field selector', async () => {
      const { prepareCustomObjectWatch } = jest.requireMock(
        '@/devworkspaceClient/services/helpers/prepareCustomObjectWatch',
      );

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const mockWatch = prepareCustomObjectWatch().watch;
      expect(mockWatch).toHaveBeenCalledWith(
        `/apis/batch/v1/namespaces/${namespace}/jobs`,
        { watch: true, fieldSelector: `metadata.name=${jobName}` },
        expect.any(Function),
        expect.any(Function),
      );
    });

    it('should send status-update event on phase change to Running', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const runningJob: Partial<V1Job> = {
        status: {
          active: 1,
          startTime: new Date('2026-02-12T10:00:00Z'),
        },
      };

      watchCallback('MODIFIED', runningJob);

      expect(mockWs.send).toHaveBeenCalledTimes(1);
      const event: StatusUpdateEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(event).toEqual({
        type: 'status-update',
        phase: 'Running',
        startTime: '2026-02-12T10:00:00.000Z',
        completionTime: undefined,
      });
    });

    it('should send status-update on ADDED event', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('ADDED', { status: {} });

      expect(mockWs.send).toHaveBeenCalledTimes(1);
      const event: StatusUpdateEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(event.type).toBe('status-update');
      expect(event.phase).toBe('Pending');
    });

    it('should debounce duplicate phase updates', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const runningJob: Partial<V1Job> = {
        status: { active: 1, startTime: new Date('2026-02-12T10:00:00Z') },
      };

      watchCallback('MODIFIED', runningJob);
      watchCallback('MODIFIED', runningJob);
      watchCallback('MODIFIED', runningJob);

      expect(mockWs.send).toHaveBeenCalledTimes(1);
    });

    it('should send events for each distinct phase change', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      // Pending
      watchCallback('ADDED', { status: {} });

      // Running
      watchCallback('MODIFIED', {
        status: { active: 1, startTime: new Date('2026-02-12T10:00:00Z') },
      });

      // Succeeded
      watchCallback('MODIFIED', {
        status: {
          succeeded: 1,
          startTime: new Date('2026-02-12T10:00:00Z'),
          completionTime: new Date('2026-02-12T10:05:00Z'),
        },
        spec: {
          template: {
            spec: {
              containers: [
                {
                  name: 'backup',
                  image: 'img',
                  env: [{ name: 'BACKUP_IMAGE_URL', value: 'registry.example.com/ns/ws:123' }],
                },
              ],
              restartPolicy: 'OnFailure',
            },
          },
        },
      });

      // Pending(1) + Running(1) + Succeeded status-update(1) + completed(1) = 4
      expect(mockWs.send).toHaveBeenCalledTimes(4);

      const events = mockWs.send.mock.calls.map(
        (call: [string]) => JSON.parse(call[0]) as StatusUpdateEvent | CompletedEvent,
      );

      expect(events[0]).toMatchObject({ type: 'status-update', phase: 'Pending' });
      expect(events[1]).toMatchObject({ type: 'status-update', phase: 'Running' });
      expect(events[2]).toMatchObject({ type: 'status-update', phase: 'Succeeded' });
      expect(events[3]).toMatchObject({
        type: 'completed',
        status: 'success',
        backupImageUrl: 'registry.example.com/ns/ws:123',
      });
    });

    it('should send completed event with success status on Succeeded', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const succeededJob: Partial<V1Job> = {
        status: {
          succeeded: 1,
          startTime: new Date('2026-02-12T10:00:00Z'),
          completionTime: new Date('2026-02-12T10:05:00Z'),
        },
        spec: {
          template: {
            spec: {
              containers: [
                {
                  name: 'backup',
                  image: 'backup-img',
                  env: [{ name: 'BACKUP_IMAGE_URL', value: 'registry/ns/ws:tag' }],
                },
              ],
              restartPolicy: 'OnFailure',
            },
          },
        },
      };

      watchCallback('MODIFIED', succeededJob);

      // status-update + completed
      expect(mockWs.send).toHaveBeenCalledTimes(2);

      const completedEvent: CompletedEvent = JSON.parse(mockWs.send.mock.calls[1][0]);
      expect(completedEvent).toEqual({
        type: 'completed',
        status: 'success',
        backupImageUrl: 'registry/ns/ws:tag',
      });
    });

    it('should send completed event with failed status and error message', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const failedJob: Partial<V1Job> = {
        status: {
          failed: 3,
          startTime: new Date('2026-02-12T10:00:00Z'),
          conditions: [
            {
              type: 'Failed',
              status: 'True',
              reason: 'BackoffLimitExceeded',
              message: 'Job has reached the specified backoff limit',
              lastTransitionTime: new Date('2026-02-12T10:03:00Z'),
              lastProbeTime: new Date('2026-02-12T10:03:00Z'),
            },
          ],
        },
      };

      watchCallback('MODIFIED', failedJob);

      expect(mockWs.send).toHaveBeenCalledTimes(2);

      const completedEvent: CompletedEvent = JSON.parse(mockWs.send.mock.calls[1][0]);
      expect(completedEvent).toEqual({
        type: 'completed',
        status: 'failed',
        error: 'Job has reached the specified backoff limit',
      });
    });

    it('should use default error message when failed condition has no message', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const failedJob: Partial<V1Job> = {
        status: {
          failed: 1,
          conditions: [
            {
              type: 'Failed',
              status: 'True',
              lastTransitionTime: new Date('2026-02-12T10:03:00Z'),
              lastProbeTime: new Date('2026-02-12T10:03:00Z'),
            },
          ],
        },
      };

      watchCallback('MODIFIED', failedJob);

      const completedEvent: CompletedEvent = JSON.parse(mockWs.send.mock.calls[1][0]);
      expect(completedEvent.error).toBe('Backup job failed');
    });

    it('should use default error when no Failed condition exists', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const failedJob: Partial<V1Job> = {
        status: {
          failed: 1,
          conditions: [],
        },
      };

      watchCallback('MODIFIED', failedJob);

      const completedEvent: CompletedEvent = JSON.parse(mockWs.send.mock.calls[1][0]);
      expect(completedEvent.error).toBe('Backup job failed');
    });

    it('should close WebSocket with code 1000 on successful completion', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('MODIFIED', { status: { succeeded: 1 } });

      expect(mockWs.close).toHaveBeenCalledWith(1000, 'Job completed');
    });

    it('should close WebSocket with code 1000 on failed completion', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('MODIFIED', { status: { failed: 1 } });

      expect(mockWs.close).toHaveBeenCalledWith(1000, 'Job completed');
    });

    it('should abort watch on completion', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('MODIFIED', { status: { succeeded: 1 } });

      expect(mockAbortController.abort).toHaveBeenCalled();
    });

    it('should handle watch error by sending completed/failed and closing', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchErrorCallback(new Error('Connection lost'));

      expect(mockWs.send).toHaveBeenCalledTimes(1);
      const event: CompletedEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(event).toEqual({
        type: 'completed',
        status: 'failed',
        error: 'Lost connection to job watcher',
      });
      expect(mockWs.close).toHaveBeenCalledWith(1011, 'Watch error');
      expect(mockAbortController.abort).toHaveBeenCalled();
    });

    it('should handle ERROR event phase from watch', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('ERROR', {
        kind: 'Status',
        apiVersion: 'v1',
        status: 'Failure',
        message: 'gone: resource version too old',
      });

      expect(mockWs.send).toHaveBeenCalledTimes(1);
      const event: CompletedEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(event.type).toBe('completed');
      expect(event.status).toBe('failed');
      expect(event.error).toBe('Lost connection to job watcher');
      expect(mockAbortController.abort).toHaveBeenCalled();
    });

    it('should not send events when WebSocket is not open', async () => {
      mockWs.readyState = WebSocket.CLOSED;

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('MODIFIED', { status: { active: 1 } });

      expect(mockWs.send).not.toHaveBeenCalled();
    });

    it('should cleanup on WebSocket close event', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      // Trigger close handler
      mockWs._handlers['close']();

      expect(mockAbortController.abort).toHaveBeenCalled();
    });

    it('should cleanup on WebSocket error event', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      // Trigger error handler
      mockWs._handlers['error'](new Error('connection error'));

      expect(mockAbortController.abort).toHaveBeenCalled();
    });

    it('should not send status-update when phase has not changed from Pending', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      // First Pending event
      watchCallback('ADDED', { status: {} });
      expect(mockWs.send).toHaveBeenCalledTimes(1);

      // Another Pending event - should be debounced
      watchCallback('MODIFIED', { status: {} });
      expect(mockWs.send).toHaveBeenCalledTimes(1);
    });

    it('should handle succeeded job without backup image URL env var', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const succeededJob: Partial<V1Job> = {
        status: {
          succeeded: 1,
          startTime: new Date('2026-02-12T10:00:00Z'),
          completionTime: new Date('2026-02-12T10:05:00Z'),
        },
      };

      watchCallback('MODIFIED', succeededJob);

      const completedEvent: CompletedEvent = JSON.parse(mockWs.send.mock.calls[1][0]);
      expect(completedEvent.backupImageUrl).toBeUndefined();
    });

    it('should include startTime and completionTime in status-update', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('MODIFIED', {
        status: {
          succeeded: 1,
          startTime: new Date('2026-02-12T10:00:00Z'),
          completionTime: new Date('2026-02-12T10:05:00Z'),
        },
      });

      const statusEvent: StatusUpdateEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(statusEvent.startTime).toBe('2026-02-12T10:00:00.000Z');
      expect(statusEvent.completionTime).toBe('2026-02-12T10:05:00.000Z');
    });

    it('should handle status-update without startTime', async () => {
      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('ADDED', { status: {} });

      const statusEvent: StatusUpdateEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(statusEvent.startTime).toBeUndefined();
      expect(statusEvent.completionTime).toBeUndefined();
    });

    it('should handle watch.watch throwing an error', async () => {
      const { prepareCustomObjectWatch } = jest.requireMock(
        '@/devworkspaceClient/services/helpers/prepareCustomObjectWatch',
      );
      prepareCustomObjectWatch.mockReturnValueOnce({
        config: {},
        watch: jest.fn().mockRejectedValueOnce(new Error('Watch init failed')),
      });

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      // Wait for async startWatching to run and catch the error
      await new Promise(resolve => setTimeout(resolve, 10));

      expect(mockWs.send).toHaveBeenCalledTimes(1);
      const event: CompletedEvent = JSON.parse(mockWs.send.mock.calls[0][0]);
      expect(event).toEqual({
        type: 'completed',
        status: 'failed',
        error: 'Failed to start job watcher',
      });
      expect(mockWs.close).toHaveBeenCalledWith(1011, 'Failed to start watcher');
    });

    it('should log when WebSocket close event fires', async () => {
      const { logger } = jest.requireMock('@/utils/logger');

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      mockWs._handlers['close']();

      expect(logger.info).toHaveBeenCalledWith(
        `Backup job WebSocket closed for ${namespace}/${jobName}`,
      );
    });

    it('should log when WebSocket error event fires', async () => {
      const { logger } = jest.requireMock('@/utils/logger');

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const error = new Error('ws error');
      mockWs._handlers['error'](error);

      expect(logger.error).toHaveBeenCalledWith(
        error,
        `Backup job WebSocket error for ${namespace}/${jobName}`,
      );
    });

    it('should log when watch error event fires', async () => {
      const { logger } = jest.requireMock('@/utils/logger');

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      const error = new Error('watch failed');
      watchErrorCallback(error);

      expect(logger.error).toHaveBeenCalledWith(
        error,
        `Backup job watch error for ${namespace}/${jobName}`,
      );
    });

    it('should log ERROR event phase details', async () => {
      const { logger } = jest.requireMock('@/utils/logger');

      backupJobWebSocketHandler(
        mockWs as unknown as WebSocket,
        createMockRequest(namespace, jobName),
      );

      await Promise.resolve();

      watchCallback('ERROR', {
        message: 'resource version too old',
      });

      expect(logger.error).toHaveBeenCalledWith(
        `Watch error for backup job ${namespace}/${jobName}: resource version too old`,
      );
    });
  });
});
