/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import * as k8s from '@kubernetes/client-node';
import { V1Job, V1JobCondition } from '@kubernetes/client-node';
import { FastifyInstance } from 'fastify';

import { baseApiPath } from '@/constants/config';
import { setup, teardown } from '@/utils/appBuilder';

// Mock retryableExec to avoid timeout issues
jest.mock('@/devworkspaceClient/services/helpers/retryableExec', () => ({
  retryableExec: jest.fn((fn: () => any) => fn()),
}));

// Mock helpers
jest.mock('@/routes/api/helpers/getServiceAccountToken');
jest.mock('@/routes/api/helpers/getDevWorkspaceClient');

const mockBatchV1API = {
  readNamespacedJobStatus: jest.fn(),
  listNamespacedJob: jest.fn(),
  deleteNamespacedJob: jest.fn(),
};

const mockKubeConfig = new k8s.KubeConfig();
jest.spyOn(mockKubeConfig, 'makeApiClient').mockImplementation((apiType: any) => {
  if (apiType === k8s.BatchV1Api) {
    return mockBatchV1API;
  }
  return {};
});

// Mock KubeConfigProvider
jest.mock('@/services/kubeclient/kubeConfigProvider', () => ({
  KubeConfigProvider: jest.fn().mockImplementation(() => ({
    getKubeConfig: jest.fn().mockReturnValue(mockKubeConfig),
  })),
}));

describe('Jobs Routes', () => {
  let app: FastifyInstance;
  const namespace = 'user-che';
  const jobName = 'backup-my-workspace-12345';

  beforeAll(async () => {
    app = await setup();
  });

  afterAll(() => {
    teardown(app);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('GET /api/namespace/:namespace/jobs/:jobName/status', () => {
    it('should return job status for succeeded job', async () => {
      const mockJob: Partial<V1Job> = {
        status: {
          succeeded: 1,
          startTime: new Date('2026-02-10T10:00:00Z'),
          completionTime: new Date('2026-02-10T10:05:00Z'),
          conditions: [
            {
              type: 'Complete',
              status: 'True',
              reason: 'JobComplete',
              message: 'Job completed successfully',
            } as V1JobCondition,
          ],
        },
      };

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toEqual({
        phase: 'Succeeded',
        startTime: '2026-02-10T10:00:00.000Z',
        completionTime: '2026-02-10T10:05:00.000Z',
        conditions: [
          {
            type: 'Complete',
            status: 'True',
            reason: 'JobComplete',
            message: 'Job completed successfully',
          },
        ],
      });

      expect(mockBatchV1API.readNamespacedJobStatus).toHaveBeenCalledWith({
        name: jobName,
        namespace,
      });
    });

    it('should return job status for failed job', async () => {
      const mockJob: Partial<V1Job> = {
        status: {
          failed: 1,
          startTime: new Date('2026-02-10T10:00:00Z'),
          completionTime: new Date('2026-02-10T10:03:00Z'),
          conditions: [
            {
              type: 'Failed',
              status: 'True',
              reason: 'BackoffLimitExceeded',
              message: 'Job has reached the specified backoff limit',
            } as V1JobCondition,
          ],
        },
      };

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.phase).toEqual('Failed');
      expect(response.conditions).toHaveLength(1);
      expect(response.conditions[0].type).toEqual('Failed');
    });

    it('should return job status for running job', async () => {
      const mockJob: Partial<V1Job> = {
        status: {
          active: 1,
          startTime: new Date('2026-02-10T10:00:00Z'),
          conditions: [],
        },
      };

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.phase).toEqual('Running');
      expect(response.startTime).toEqual('2026-02-10T10:00:00.000Z');
      expect(response.completionTime).toBeUndefined();
    });

    it('should return job status for pending job', async () => {
      const mockJob: Partial<V1Job> = {
        status: {
          conditions: [],
        },
      };

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.phase).toEqual('Pending');
      expect(response.startTime).toBeUndefined();
      expect(response.completionTime).toBeUndefined();
    });

    it('should handle job with no status field', async () => {
      const mockJob: Partial<V1Job> = {};

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.phase).toEqual('Pending');
      expect(response.conditions).toBeUndefined();
    });

    it('should handle job not found (404)', async () => {
      const notFoundError = new Error('Not found');
      (notFoundError as any).response = {
        statusCode: 404,
      };

      mockBatchV1API.readNamespacedJobStatus.mockRejectedValue(notFoundError);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('not found');
    });

    it('should handle API errors', async () => {
      const apiError = new Error('API Error');

      mockBatchV1API.readNamespacedJobStatus.mockRejectedValue(apiError);

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('Unable to get job status');
    });

    it('should handle job with multiple conditions', async () => {
      const mockJob: Partial<V1Job> = {
        status: {
          succeeded: 1,
          startTime: new Date('2026-02-10T10:00:00Z'),
          completionTime: new Date('2026-02-10T10:05:00Z'),
          conditions: [
            {
              type: 'Suspended',
              status: 'False',
            } as V1JobCondition,
            {
              type: 'Complete',
              status: 'True',
              reason: 'JobComplete',
            } as V1JobCondition,
          ],
        },
      };

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.conditions).toHaveLength(2);
      expect(response.conditions[0].type).toEqual('Suspended');
      expect(response.conditions[1].type).toEqual('Complete');
    });

    it('should handle job with conditions but no reason/message', async () => {
      const mockJob: Partial<V1Job> = {
        status: {
          active: 1,
          startTime: new Date('2026-02-10T10:00:00Z'),
          conditions: [
            {
              type: 'Active',
              status: 'True',
            } as V1JobCondition,
          ],
        },
      };

      mockBatchV1API.readNamespacedJobStatus.mockResolvedValue({
        body: mockJob,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}/status`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.conditions[0].reason).toBeUndefined();
      expect(response.conditions[0].message).toBeUndefined();
    });
  });

  describe('GET /api/namespace/:namespace/jobs', () => {
    it('should list all jobs in namespace', async () => {
      const mockJobs = {
        items: [
          {
            metadata: {
              name: 'backup-workspace1-12345',
              namespace,
            },
            status: {
              succeeded: 1,
              startTime: new Date('2026-02-10T10:00:00Z'),
              completionTime: new Date('2026-02-10T10:05:00Z'),
            },
          },
          {
            metadata: {
              name: 'backup-workspace2-67890',
              namespace,
            },
            status: {
              active: 1,
              startTime: new Date('2026-02-10T11:00:00Z'),
            },
          },
        ],
      };

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        body: mockJobs,
      });

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toHaveLength(2);
      expect(response[0]).toEqual({
        name: 'backup-workspace1-12345',
        namespace,
        status: 'Succeeded',
        startTime: '2026-02-10T10:00:00.000Z',
        completionTime: '2026-02-10T10:05:00.000Z',
        succeeded: 1,
        failed: 0,
      });
      expect(response[1]).toEqual({
        name: 'backup-workspace2-67890',
        namespace,
        status: 'Running',
        startTime: '2026-02-10T11:00:00.000Z',
        completionTime: undefined,
        succeeded: 0,
        failed: 0,
      });

      expect(mockBatchV1API.listNamespacedJob).toHaveBeenCalledWith({
        namespace,
        labelSelector: undefined,
      });
    });

    it('should list jobs with label selector', async () => {
      const labelSelector = 'controller.devfile.io/devworkspace_name=my-workspace';
      const mockJobs = {
        items: [
          {
            metadata: {
              name: 'backup-my-workspace-12345',
              namespace,
            },
            status: {
              succeeded: 1,
              startTime: new Date('2026-02-10T10:00:00Z'),
              completionTime: new Date('2026-02-10T10:05:00Z'),
            },
          },
        ],
      };

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        body: mockJobs,
      });

      const res = await app
        .inject()
        .get(`${baseApiPath}/namespace/${namespace}/jobs?labelSelector=${labelSelector}`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toHaveLength(1);
      expect(response[0].name).toEqual('backup-my-workspace-12345');

      expect(mockBatchV1API.listNamespacedJob).toHaveBeenCalledWith({
        namespace,
        labelSelector,
      });
    });

    it('should return empty list when no jobs exist', async () => {
      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        body: { items: [] },
      });

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response).toHaveLength(0);
    });

    it('should handle failed jobs', async () => {
      const mockJobs = {
        items: [
          {
            metadata: {
              name: 'backup-workspace-failed',
              namespace,
            },
            status: {
              failed: 3,
              startTime: new Date('2026-02-10T10:00:00Z'),
              completionTime: new Date('2026-02-10T10:02:00Z'),
            },
          },
        ],
      };

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        body: mockJobs,
      });

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response[0].status).toEqual('Failed');
      expect(response[0].failed).toEqual(3);
    });

    it('should handle pending jobs', async () => {
      const mockJobs = {
        items: [
          {
            metadata: {
              name: 'backup-workspace-pending',
              namespace,
            },
            status: {},
          },
        ],
      };

      mockBatchV1API.listNamespacedJob.mockResolvedValue({
        body: mockJobs,
      });

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response[0].status).toEqual('Pending');
      expect(response[0].succeeded).toEqual(0);
      expect(response[0].failed).toEqual(0);
    });

    it('should handle API errors', async () => {
      const apiError = new Error('API Error');

      mockBatchV1API.listNamespacedJob.mockRejectedValue(apiError);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('Unable to list jobs');
    });

    it('should handle RBAC errors (403)', async () => {
      const rbacError = new Error('Forbidden');
      (rbacError as any).response = {
        statusCode: 403,
      };

      mockBatchV1API.listNamespacedJob.mockRejectedValue(rbacError);

      const res = await app.inject().get(`${baseApiPath}/namespace/${namespace}/jobs`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toBeDefined();
    });
  });

  describe('DELETE /api/namespace/:namespace/jobs/:jobName', () => {
    it('should delete job successfully', async () => {
      mockBatchV1API.deleteNamespacedJob.mockResolvedValue({});

      const res = await app
        .inject()
        .delete(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}`);

      expect(res.statusCode).toEqual(200);
      const response = res.json();

      expect(response.message).toContain('deleted successfully');
      expect(mockBatchV1API.deleteNamespacedJob).toHaveBeenCalledWith({
        name: jobName,
        namespace,
        propagationPolicy: 'Background',
      });
    });

    it('should handle job not found (404)', async () => {
      const notFoundError = new Error('Not found');
      (notFoundError as any).response = {
        statusCode: 404,
      };

      mockBatchV1API.deleteNamespacedJob.mockRejectedValue(notFoundError);

      const res = await app
        .inject()
        .delete(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('not found');
    });

    it('should handle API errors', async () => {
      const apiError = new Error('API Error');

      mockBatchV1API.deleteNamespacedJob.mockRejectedValue(apiError);

      const res = await app
        .inject()
        .delete(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toContain('Unable to delete job');
    });

    it('should handle RBAC errors (403)', async () => {
      const rbacError = new Error('Forbidden');
      (rbacError as any).response = {
        statusCode: 403,
      };

      mockBatchV1API.deleteNamespacedJob.mockRejectedValue(rbacError);

      const res = await app
        .inject()
        .delete(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}`);

      expect(res.statusCode).toEqual(500);
      const response = res.json();

      expect(response.message).toBeDefined();
    });

    it('should propagate delete to pods (Background propagation)', async () => {
      mockBatchV1API.deleteNamespacedJob.mockResolvedValue({});

      await app.inject().delete(`${baseApiPath}/namespace/${namespace}/jobs/${jobName}`);

      expect(mockBatchV1API.deleteNamespacedJob).toHaveBeenCalledWith(
        expect.objectContaining({
          propagationPolicy: 'Background',
        }),
      );
    });
  });
});
