/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

/**
 * Backup-related constants shared between frontend and backend
 */

/**
 * Backup cache TTL in seconds
 * Default: 300 seconds (5 minutes)
 */
export const BACKUP_CACHE_TTL_SECONDS = 300;

/**
 * Default page size for backup list pagination
 * Default: 50 items per page
 */
export const BACKUP_LIST_DEFAULT_PAGE_SIZE = 50;

/**
 * Maximum page size for backup list pagination
 * Max: 100 items per page
 */
export const BACKUP_LIST_MAX_PAGE_SIZE = 100;

/**
 * Minimum page size for backup list pagination
 * Min: 1 item per page
 */
export const BACKUP_LIST_MIN_PAGE_SIZE = 1;

/**
 * Default page number for pagination (1-indexed)
 */
export const BACKUP_LIST_DEFAULT_PAGE = 1;

/**
 * Registry query timeout in seconds
 * Default: 10 seconds
 */
export const REGISTRY_QUERY_TIMEOUT_SECONDS = 10;

/**
 * Backup image URL pattern
 * Format: {registry}/{namespace}/{workspaceName}:latest
 * Example: image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:latest
 */
export const BACKUP_IMAGE_URL_PATTERN =
  /^([a-z0-9.-]+(?::[0-9]+)?)\/([a-z0-9-]+)\/([a-z0-9-]+):([a-z0-9._-]+)$/i;

/**
 * OpenShift internal registry default hostname
 */
export const OPENSHIFT_INTERNAL_REGISTRY_HOSTNAME =
  'image-registry.openshift-image-registry.svc';

/**
 * OpenShift internal registry default port
 */
export const OPENSHIFT_INTERNAL_REGISTRY_PORT = 5000;

/**
 * Default backup image tag
 * Always :latest for MVP
 */
export const BACKUP_IMAGE_DEFAULT_TAG = 'latest';

/**
 * Backup status display labels
 * Used for UI display text
 */
export const BACKUP_STATUS_LABELS = {
  success: 'Success',
  failed: 'Failed',
  'in-progress': 'In Progress',
  never: 'Never',
} as const;

/**
 * Backup status color mappings for PatternFly Label component
 * - success: green (backup completed successfully)
 * - failed: orange (warning - backup failed but workspace still usable)
 * - in-progress: blue (backup job is running)
 * - never: grey (workspace has never been backed up)
 */
export const BACKUP_STATUS_COLORS = {
  success: 'green',
  failed: 'orange',
  'in-progress': 'blue',
  never: 'grey',
} as const;

/**
 * Backup status icon names for PatternFly icons
 */
export const BACKUP_STATUS_ICONS = {
  success: 'CheckCircleIcon',
  failed: 'ExclamationTriangleIcon',
  'in-progress': 'InProgressIcon',
  never: 'InfoCircleIcon',
} as const;

/**
 * DevWorkspace annotation keys for backup/restore
 */
export const DEVWORKSPACE_BACKUP_ANNOTATIONS = {
  /** Whether the last backup succeeded ("true" or "false"), set by DWO BackupCronJob controller */
  LAST_BACKUP_SUCCESSFUL: 'controller.devfile.io/last-backup-successful',
  /** ISO timestamp of when the last backup finished, set by DWO BackupCronJob controller */
  LAST_BACKUP_FINISHED_AT: 'controller.devfile.io/last-backup-finished-at',
  /** Error message from last backup failure, set by DWO BackupCronJob controller */
  LAST_BACKUP_ERROR: 'controller.devfile.io/last-backup-error',
  /** Indicates workspace should be restored from backup */
  RESTORE_WORKSPACE: 'controller.devfile.io/restore-workspace',
  /** Specifies the backup image URL to restore from */
  RESTORE_SOURCE_IMAGE: 'controller.devfile.io/restore-source-image',
} as const;

/**
 * DevWorkspace label keys for backup jobs.
 * These must match the labels set by DWO BackupCronJob controller
 * (see pkg/constants/metadata.go in devworkspace-operator).
 */
export const DEVWORKSPACE_BACKUP_LABELS = {
  /** Label on backup Job indicating the workspace name (DWO: DevWorkspaceNameLabel) */
  WORKSPACE_NAME: 'controller.devfile.io/devworkspace_name',
  /** Label on backup Job/ImageStream indicating the workspace ID (DWO: DevWorkspaceIDLabel) */
  WORKSPACE_ID: 'controller.devfile.io/devworkspace_id',
  /** Label on backup Job indicating it is a DWO-managed backup (DWO: DevWorkspaceBackupJobLabel) */
  DEVWORKSPACE_BACKUP: 'controller.devfile.io/backup-job',
} as const;

/**
 * Polling interval for backup job status (fallback when WebSocket unavailable)
 * Default: 5000ms (5 seconds)
 */
export const BACKUP_JOB_POLLING_INTERVAL_MS = 5000;

/**
 * HTTP status codes for backup-specific errors
 */
export const BACKUP_ERROR_CODES = {
  BACKUP_NOT_CONFIGURED: 'BACKUP_NOT_CONFIGURED',
  BACKUP_IMAGE_NOT_FOUND: 'BACKUP_IMAGE_NOT_FOUND',
  REGISTRY_AUTH_FAILED: 'REGISTRY_AUTH_FAILED',
  INVALID_IMAGE_URL: 'INVALID_IMAGE_URL',
  INVALID_NAMESPACE: 'INVALID_NAMESPACE',
  INVALID_PAGE_NUMBER: 'INVALID_PAGE_NUMBER',
  INVALID_PAGE_SIZE: 'INVALID_PAGE_SIZE',
  DEVWORKSPACE_NOT_FOUND: 'DEVWORKSPACE_NOT_FOUND',
  JOB_API_ERROR: 'JOB_API_ERROR',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  REGISTRY_API_ERROR: 'REGISTRY_API_ERROR',
  TIMEOUT: 'TIMEOUT',
} as const;
