/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import { BACKUP_CACHE_TTL_SECONDS, BACKUP_ERROR_CODES } from '@eclipse-che/common';

import {
  IBackupImage,
  IImageMetadata,
} from '@/devworkspaceClient/services/helpers/registryAdapters/IRegistryAdapter';
import { RegistryApiService } from '@/devworkspaceClient/services/registryApi';

const mockAdapter = {
  listBackupImages: jest.fn(),
  validateImageAccessibility: jest.fn(),
  getImageMetadata: jest.fn(),
};

const mockCustomObjectsApi = {
  getNamespacedCustomObject: jest.fn(),
  listNamespacedCustomObject: jest.fn(),
};

const mockKubeConfig = {
  makeApiClient: jest.fn(() => mockCustomObjectsApi),
};

describe('RegistryApiService', () => {
  let service: RegistryApiService;

  const namespace = 'user-che';
  const workspaceName = 'my-workspace';
  const imageUrl =
    'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:backup-20260210-120000';

  beforeEach(() => {
    service = new RegistryApiService(mockKubeConfig as any, mockAdapter as any);
    jest.clearAllMocks();
    // Default: workspace exists (for doesWorkspaceExist checks)
    // and DWOC config returns a valid registry path (for getBackupRegistryPath)
    mockCustomObjectsApi.getNamespacedCustomObject.mockResolvedValue({
      config: {
        workspace: {
          backupCronJob: {
            registry: {
              path: 'image-registry.openshift-image-registry.svc:5000',
            },
          },
        },
      },
    });
    // Default: no DevWorkspaces with backup annotations
    mockCustomObjectsApi.listNamespacedCustomObject.mockResolvedValue({ items: [] });
  });

  describe('K8s DNS-1123 Validation', () => {
    it('should reject empty namespace', async () => {
      await expect(service.listBackupImages('')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
        message: expect.stringContaining('cannot be empty'),
      });
    });

    it('should reject namespace with uppercase letters', async () => {
      await expect(service.listBackupImages('User-Che')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
        message: expect.stringContaining('DNS-1123'),
      });
    });

    it('should reject namespace exceeding 63 characters', async () => {
      const longNamespace = 'a'.repeat(64);
      await expect(service.listBackupImages(longNamespace)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
        message: expect.stringContaining('maximum length'),
      });
    });

    it('should accept valid namespace', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([]);
      await expect(service.listBackupImages('user-che')).resolves.toBeDefined();
    });
  });

  describe('listBackupImages', () => {
    const mockIBackupImages: IBackupImage[] = [
      {
        workspaceName: 'my-workspace',
        imageUrl: `${imageUrl}-1`,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
      {
        workspaceName: 'my-workspace-2',
        imageUrl: `${imageUrl}-2`,
        timestamp: '2026-02-09T12:00:00.000Z',
        sizeBytes: 2048000,
        labels: {},
      },
    ];

    it('should list backup images', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      const result = await service.listBackupImages(namespace);

      expect(result.backups).toHaveLength(2);
      expect(result.total).toBe(2);
      expect(result.page).toBe(1);
      expect(result.perPage).toBe(2);
      expect(mockAdapter.listBackupImages).toHaveBeenCalledWith(namespace);
    });

    it('should filter by workspace name when provided', async () => {
      const mixedWorkspaces: IBackupImage[] = [
        ...mockIBackupImages,
        {
          workspaceName: 'other-workspace',
          imageUrl: `${imageUrl}-other`,
          timestamp: '2026-02-08T12:00:00.000Z',
          sizeBytes: 1024000,
          labels: {},
        },
      ];
      mockAdapter.listBackupImages.mockResolvedValue(mixedWorkspaces);

      const result = await service.listBackupImages(namespace, 'my-workspace');

      expect(result.backups).toHaveLength(1);
      expect(result.backups.every(b => b.workspaceName === 'my-workspace')).toBe(true);
    });

    it('should enrich results with workspaceExists field', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      const result = await service.listBackupImages(namespace);

      expect(result.backups[0].workspaceExists).toBe(true);
      expect(result.backups[1].workspaceExists).toBe(true);
    });

    it('should detect when workspace does not exist', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([mockIBackupImages[0]]);
      const notFoundError: any = new Error('Not found');
      notFoundError.response = { statusCode: 404 };
      // DWOC config call succeeds, workspace existence call returns 404
      mockCustomObjectsApi.getNamespacedCustomObject.mockImplementation((params: any) => {
        if (params.plural === 'devworkspaceoperatorconfigs') {
          return Promise.resolve({
            config: {
              workspace: {
                backupCronJob: { registry: { path: 'image-registry.openshift-image-registry.svc:5000' } },
              },
            },
          });
        }
        return Promise.reject(notFoundError);
      });

      const result = await service.listBackupImages(namespace);

      expect(result.backups[0].workspaceExists).toBe(false);
    });

    it('should return cached results on second call', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // First call
      await service.listBackupImages(namespace);

      // Second call - should use cache
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(1);
    });

  });

  describe('validateBackupImage', () => {
    const mockMetadata: IImageMetadata = {
      workspaceName: 'my-workspace',
      namespace: 'user-che',
      timestamp: '2026-02-10T12:00:00.000Z',
      sizeBytes: 1024000,
      labels: {},
    };

    it('should validate accessible image successfully', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(true);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(true);
      expect(result.accessible).toBe(true);
      expect(result.metadata).toBeDefined();
    });

    it('should handle inaccessible image', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(false);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(true);
      expect(result.accessible).toBe(false);
      expect(result.metadata).toBeUndefined();
    });

    it('should cache successful validations', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(true);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.validateBackupImage(imageUrl);

      // Second call - should use cache
      await service.validateBackupImage(imageUrl);

      expect(mockAdapter.validateImageAccessibility).toHaveBeenCalledTimes(1);
    });

    it('should NOT cache failed validations', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(false);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.validateBackupImage(imageUrl);

      // Second call - should NOT use cache
      await service.validateBackupImage(imageUrl);

      expect(mockAdapter.validateImageAccessibility).toHaveBeenCalledTimes(2);
    });

    it('should reject empty image URL', async () => {
      await expect(service.validateBackupImage('')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
      });
    });

    it('should handle timeout gracefully', async () => {
      mockAdapter.validateImageAccessibility.mockImplementation(
        () =>
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Registry query timeout')), 100),
          ),
      );

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(false);
      expect(result.accessible).toBe(false);
      expect(result.error).toContain('timed out');
    }, 30000);
  });

  describe('getImageMetadata', () => {
    const mockMetadata: IImageMetadata = {
      workspaceName: 'my-workspace',
      namespace: 'user-che',
      timestamp: '2026-02-10T12:00:00.000Z',
      sizeBytes: 1024000,
      labels: { 'backup.timestamp': '2026-02-10T12:00:00.000Z' },
    };

    it('should retrieve metadata successfully', async () => {
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      const result = await service.getImageMetadata(imageUrl);

      expect(result.workspaceName).toBe('my-workspace');
      expect(result.imageUrl).toBe(imageUrl);
      expect(result.workspaceExists).toBe(true);
    });

    it('should cache metadata', async () => {
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.getImageMetadata(imageUrl);

      // Second call - should use cache
      await service.getImageMetadata(imageUrl);

      expect(mockAdapter.getImageMetadata).toHaveBeenCalledTimes(1);
    });

    it('should reject empty image URL', async () => {
      await expect(service.getImageMetadata('')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
      });
    });
  });

  describe('Cache Management', () => {
    const mockIBackupImages: IBackupImage[] = [
      {
        workspaceName: 'my-workspace',
        imageUrl,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
    ];

    it('should clear all cached data', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // Populate cache
      await service.listBackupImages(namespace);

      // Clear cache
      service.clearCache();

      // Should fetch again
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);
    });

    it('should clear namespace-scoped cache only', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // Populate cache for namespace1
      await service.listBackupImages('namespace1');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(1);

      // Populate cache for namespace2
      await service.listBackupImages('namespace2');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);

      // Clear only namespace1
      service.clearNamespaceCache('namespace1');

      // namespace1 should fetch again (cache cleared)
      await service.listBackupImages('namespace1');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(3);

      // namespace2 should use cache (not cleared)
      await service.listBackupImages('namespace2');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(3); // Still 3, used cache
    });
  });

  describe('Cache Expiration', () => {
    const mockIBackupImages: IBackupImage[] = [
      {
        workspaceName: 'my-workspace',
        imageUrl,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
    ];

    it('should expire cache after TTL', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // First call
      await service.listBackupImages(namespace);

      // Mock time advancement
      const originalDateNow = Date.now;
      Date.now = jest.fn(() => originalDateNow() + (BACKUP_CACHE_TTL_SECONDS + 1) * 1000);

      // Second call should fetch (cache expired)
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);

      // Restore
      Date.now = originalDateNow;
    });

    it('should use cache within TTL', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // First call
      await service.listBackupImages(namespace);

      // Mock time advancement (within TTL)
      const originalDateNow = Date.now;
      Date.now = jest.fn(() => originalDateNow() + (BACKUP_CACHE_TTL_SECONDS - 10) * 1000);

      // Second call should use cache (still within TTL)
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(1);

      // Restore
      Date.now = originalDateNow;
    });

    it('should expire metadata cache after TTL', async () => {
      const mockMetadata: IImageMetadata = {
        workspaceName: 'my-workspace',
        namespace: 'user-che',
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      };

      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.getImageMetadata(imageUrl);

      // Mock time advancement past TTL
      const originalDateNow = Date.now;
      Date.now = jest.fn(() => originalDateNow() + (BACKUP_CACHE_TTL_SECONDS + 1) * 1000);

      // Second call should fetch again
      await service.getImageMetadata(imageUrl);

      expect(mockAdapter.getImageMetadata).toHaveBeenCalledTimes(2);

      // Restore
      Date.now = originalDateNow;
    });
  });

  describe('Security Validations', () => {
    it('should reject namespace starting with hyphen', async () => {
      await expect(service.listBackupImages('-invalid')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      });
    });

    it('should reject namespace ending with hyphen', async () => {
      await expect(service.listBackupImages('invalid-')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      });
    });

    it('should reject namespace with dots', async () => {
      await expect(service.listBackupImages('user.che')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      });
    });

    it('should reject namespace with underscores', async () => {
      await expect(service.listBackupImages('user_che')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      });
    });

    it('should reject namespace with spaces', async () => {
      await expect(service.listBackupImages('user che')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      });
    });

    it('should reject workspace name with special characters', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([]);
      await expect(service.listBackupImages(namespace, 'ws@injection')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
      });
    });

    it('should accept single character namespace', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([]);
      await expect(service.listBackupImages('a')).resolves.toBeDefined();
    });

    it('should accept exactly 63 character namespace', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([]);
      const maxNamespace = 'a'.repeat(63);
      await expect(service.listBackupImages(maxNamespace)).resolves.toBeDefined();
    });

    it('should reject clearNamespaceCache with invalid namespace', async () => {
      expect(() => service.clearNamespaceCache('Invalid!')).toThrow();
    });
  });

  describe('Timeout Handling', () => {
    it('should propagate timeout error when no cache exists for list', async () => {
      mockAdapter.listBackupImages.mockImplementation(
        () =>
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Registry query timeout')), 50),
          ),
      );

      await expect(service.listBackupImages(namespace)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
      });
    }, 30000);

    it('should handle adapter error (non-timeout) for getImageMetadata', async () => {
      mockAdapter.getImageMetadata.mockRejectedValue(new Error('Image not found in registry'));

      await expect(service.getImageMetadata(imageUrl)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
      });
    });

    it('should reject whitespace-only image URL for validateBackupImage', async () => {
      await expect(service.validateBackupImage('   ')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
      });
    });

    it('should reject whitespace-only image URL for getImageMetadata', async () => {
      await expect(service.getImageMetadata('   ')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
      });
    });

    it('should handle generic adapter error for validateBackupImage', async () => {
      mockAdapter.validateImageAccessibility.mockRejectedValue(new Error('Connection reset'));
      mockAdapter.getImageMetadata.mockRejectedValue(new Error('Connection reset'));

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(false);
      expect(result.accessible).toBe(false);
      expect(result.error).toContain('Connection reset');
    });
  });

  describe('Cross-Namespace Cache Isolation', () => {
    const images1: IBackupImage[] = [
      {
        workspaceName: 'ws-in-ns1',
        imageUrl: `${imageUrl}-ns1`,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
    ];

    const images2: IBackupImage[] = [
      {
        workspaceName: 'ws-in-ns2',
        imageUrl: `${imageUrl}-ns2`,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 2048000,
        labels: {},
      },
    ];

    it('should maintain separate caches per namespace', async () => {
      mockAdapter.listBackupImages.mockResolvedValueOnce(images1).mockResolvedValueOnce(images2);

      // Populate cache for namespace1
      const result1 = await service.listBackupImages('namespace1');
      expect(result1.backups[0].workspaceName).toBe('ws-in-ns1');

      // Populate cache for namespace2
      const result2 = await service.listBackupImages('namespace2');
      expect(result2.backups[0].workspaceName).toBe('ws-in-ns2');

      // Verify namespace1 cache still returns namespace1 data
      const cached1 = await service.listBackupImages('namespace1');
      expect(cached1.backups[0].workspaceName).toBe('ws-in-ns1');

      // Verify namespace2 cache still returns namespace2 data
      const cached2 = await service.listBackupImages('namespace2');
      expect(cached2.backups[0].workspaceName).toBe('ws-in-ns2');

      // Only 2 adapter calls (one per namespace, rest from cache)
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);
    });

    it('should not leak data between namespaces after clearing one', async () => {
      mockAdapter.listBackupImages
        .mockResolvedValueOnce(images1)
        .mockResolvedValueOnce(images2)
        .mockResolvedValueOnce([]); // Third call returns empty (after cache clear)

      // Populate both caches
      await service.listBackupImages('namespace1');
      await service.listBackupImages('namespace2');

      // Clear namespace1 cache
      service.clearNamespaceCache('namespace1');

      // namespace1 should refetch (returns empty now)
      const result1 = await service.listBackupImages('namespace1');
      expect(result1.backups).toHaveLength(0);

      // namespace2 should still have cached data
      const result2 = await service.listBackupImages('namespace2');
      expect(result2.backups[0].workspaceName).toBe('ws-in-ns2');
    });
  });

  describe('Data Validation', () => {
    it('should reject non-array response from adapter in listBackupImages', async () => {
      mockAdapter.listBackupImages.mockResolvedValue('not-an-array');

      await expect(service.listBackupImages(namespace)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        message: expect.stringContaining('Expected array'),
      });
    });

    it('should reject null response from adapter in getImageMetadata', async () => {
      mockAdapter.getImageMetadata.mockResolvedValue(null);

      await expect(service.getImageMetadata(imageUrl)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.REGISTRY_API_ERROR,
        message: expect.stringContaining('Expected image metadata'),
      });
    });

    it('should handle workspace existence API error gracefully (fail-safe)', async () => {
      const mockImages: IBackupImage[] = [
        {
          workspaceName: 'my-workspace',
          imageUrl,
          timestamp: '2026-02-10T12:00:00.000Z',
          sizeBytes: 1024000,
          labels: {},
        },
      ];

      mockAdapter.listBackupImages.mockResolvedValue(mockImages);
      // DWOC config call succeeds, workspace existence call fails with non-404 error
      mockCustomObjectsApi.getNamespacedCustomObject.mockImplementation((params: any) => {
        if (params.plural === 'devworkspaceoperatorconfigs') {
          return Promise.resolve({
            config: {
              workspace: {
                backupCronJob: { registry: { path: 'image-registry.openshift-image-registry.svc:5000' } },
              },
            },
          });
        }
        return Promise.reject(new Error('API server timeout'));
      });

      const result = await service.listBackupImages(namespace);

      // Fail-safe: assume workspace exists on non-404 errors
      expect(result.backups[0].workspaceExists).toBe(true);
    });
  });
});
