/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import {
  BACKUP_CACHE_TTL_SECONDS,
  BACKUP_ERROR_CODES,
  BACKUP_LIST_DEFAULT_PAGE_SIZE,
  BACKUP_LIST_MAX_PAGE_SIZE,
} from '@eclipse-che/common';

import {
  IBackupImage,
  IImageMetadata,
} from '@/devworkspaceClient/services/helpers/registryAdapters/IRegistryAdapter';
import { RegistryApiService } from '@/devworkspaceClient/services/registryApi';

const mockAdapter = {
  listBackupImages: jest.fn(),
  validateImageAccessibility: jest.fn(),
  getImageMetadata: jest.fn(),
};

const mockCustomObjectsApi = {
  getNamespacedCustomObject: jest.fn(),
};

const mockKubeConfig = {
  makeApiClient: jest.fn(() => mockCustomObjectsApi),
};

describe('RegistryApiService', () => {
  let service: RegistryApiService;

  const namespace = 'user-che';
  const workspaceName = 'my-workspace';
  const imageUrl =
    'image-registry.openshift-image-registry.svc:5000/user-che/my-workspace:backup-20260210-120000';

  beforeEach(() => {
    service = new RegistryApiService(mockKubeConfig as any, mockAdapter as any);
    jest.clearAllMocks();
    // Default: workspace exists
    mockCustomObjectsApi.getNamespacedCustomObject.mockResolvedValue({});
  });

  describe('K8s DNS-1123 Validation', () => {
    it('should reject empty namespace', async () => {
      await expect(service.listBackupImages('')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
        message: expect.stringContaining('cannot be empty'),
      });
    });

    it('should reject namespace with uppercase letters', async () => {
      await expect(service.listBackupImages('User-Che')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
        message: expect.stringContaining('DNS-1123'),
      });
    });

    it('should reject namespace exceeding 63 characters', async () => {
      const longNamespace = 'a'.repeat(64);
      await expect(service.listBackupImages(longNamespace)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_NAMESPACE,
        message: expect.stringContaining('maximum length'),
      });
    });

    it('should accept valid namespace', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([]);
      await expect(service.listBackupImages('user-che')).resolves.toBeDefined();
    });
  });

  describe('listBackupImages', () => {
    const mockIBackupImages: IBackupImage[] = [
      {
        workspaceName: 'my-workspace',
        imageUrl: `${imageUrl}-1`,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
      {
        workspaceName: 'my-workspace',
        imageUrl: `${imageUrl}-2`,
        timestamp: '2026-02-09T12:00:00.000Z',
        sizeBytes: 2048000,
        labels: {},
      },
    ];

    it('should list backup images with default pagination', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      const result = await service.listBackupImages(namespace);

      expect(result.backups).toHaveLength(2);
      expect(result.total).toBe(2);
      expect(result.page).toBe(1);
      expect(result.perPage).toBe(BACKUP_LIST_DEFAULT_PAGE_SIZE);
      expect(mockAdapter.listBackupImages).toHaveBeenCalledWith(namespace);
    });

    it('should filter by workspace name when provided', async () => {
      const mixedWorkspaces: IBackupImage[] = [
        ...mockIBackupImages,
        {
          workspaceName: 'other-workspace',
          imageUrl: `${imageUrl}-other`,
          timestamp: '2026-02-08T12:00:00.000Z',
          sizeBytes: 1024000,
          labels: {},
        },
      ];
      mockAdapter.listBackupImages.mockResolvedValue(mixedWorkspaces);

      const result = await service.listBackupImages(namespace, 'my-workspace');

      expect(result.backups).toHaveLength(2);
      expect(result.backups.every(b => b.workspaceName === 'my-workspace')).toBe(true);
    });

    it('should enrich results with workspaceExists field', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      const result = await service.listBackupImages(namespace);

      expect(result.backups[0].workspaceExists).toBe(true);
      expect(result.backups[1].workspaceExists).toBe(true);
    });

    it('should detect when workspace does not exist', async () => {
      mockAdapter.listBackupImages.mockResolvedValue([mockIBackupImages[0]]);
      const notFoundError: any = new Error('Not found');
      notFoundError.response = { statusCode: 404 };
      mockCustomObjectsApi.getNamespacedCustomObject.mockRejectedValue(notFoundError);

      const result = await service.listBackupImages(namespace);

      expect(result.backups[0].workspaceExists).toBe(false);
    });

    it('should return cached results on second call', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // First call
      await service.listBackupImages(namespace);

      // Second call - should use cache
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(1);
    });

    it('should reject invalid page number', async () => {
      await expect(service.listBackupImages(namespace, undefined, 0)).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_PAGE_NUMBER,
      });
    });

    it('should reject invalid page size', async () => {
      await expect(
        service.listBackupImages(namespace, undefined, 1, BACKUP_LIST_MAX_PAGE_SIZE + 1),
      ).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_PAGE_SIZE,
      });
    });

    it('should handle pagination correctly', async () => {
      const manyImages: IBackupImage[] = Array.from({ length: 10 }, (_, i) => ({
        workspaceName: 'my-workspace',
        imageUrl: `${imageUrl}-${i}`,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      }));
      mockAdapter.listBackupImages.mockResolvedValue(manyImages);

      const result = await service.listBackupImages(namespace, undefined, 2, 3);

      expect(result.backups).toHaveLength(3);
      expect(result.page).toBe(2);
      expect(result.total).toBe(10);
    });
  });

  describe('validateBackupImage', () => {
    const mockMetadata: IImageMetadata = {
      workspaceName: 'my-workspace',
      namespace: 'user-che',
      timestamp: '2026-02-10T12:00:00.000Z',
      sizeBytes: 1024000,
      labels: {},
    };

    it('should validate accessible image successfully', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(true);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(true);
      expect(result.accessible).toBe(true);
      expect(result.metadata).toBeDefined();
    });

    it('should handle inaccessible image', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(false);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(true);
      expect(result.accessible).toBe(false);
      expect(result.metadata).toBeUndefined();
    });

    it('should cache successful validations', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(true);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.validateBackupImage(imageUrl);

      // Second call - should use cache
      await service.validateBackupImage(imageUrl);

      expect(mockAdapter.validateImageAccessibility).toHaveBeenCalledTimes(1);
    });

    it('should NOT cache failed validations', async () => {
      mockAdapter.validateImageAccessibility.mockResolvedValue(false);
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.validateBackupImage(imageUrl);

      // Second call - should NOT use cache
      await service.validateBackupImage(imageUrl);

      expect(mockAdapter.validateImageAccessibility).toHaveBeenCalledTimes(2);
    });

    it('should reject empty image URL', async () => {
      await expect(service.validateBackupImage('')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
      });
    });

    it('should handle timeout gracefully', async () => {
      mockAdapter.validateImageAccessibility.mockImplementation(
        () =>
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error('Registry query timeout')), 100),
          ),
      );

      const result = await service.validateBackupImage(imageUrl);

      expect(result.valid).toBe(false);
      expect(result.accessible).toBe(false);
      expect(result.error).toContain('timed out');
    }, 30000);
  });

  describe('getImageMetadata', () => {
    const mockMetadata: IImageMetadata = {
      workspaceName: 'my-workspace',
      namespace: 'user-che',
      timestamp: '2026-02-10T12:00:00.000Z',
      sizeBytes: 1024000,
      labels: { 'backup.timestamp': '2026-02-10T12:00:00.000Z' },
    };

    it('should retrieve metadata successfully', async () => {
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      const result = await service.getImageMetadata(imageUrl);

      expect(result.workspaceName).toBe('my-workspace');
      expect(result.imageUrl).toBe(imageUrl);
      expect(result.workspaceExists).toBe(true);
    });

    it('should cache metadata', async () => {
      mockAdapter.getImageMetadata.mockResolvedValue(mockMetadata);

      // First call
      await service.getImageMetadata(imageUrl);

      // Second call - should use cache
      await service.getImageMetadata(imageUrl);

      expect(mockAdapter.getImageMetadata).toHaveBeenCalledTimes(1);
    });

    it('should reject empty image URL', async () => {
      await expect(service.getImageMetadata('')).rejects.toMatchObject({
        name: BACKUP_ERROR_CODES.INVALID_IMAGE_URL,
      });
    });
  });

  describe('Cache Management', () => {
    const mockIBackupImages: IBackupImage[] = [
      {
        workspaceName: 'my-workspace',
        imageUrl,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
    ];

    it('should clear all cached data', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // Populate cache
      await service.listBackupImages(namespace);

      // Clear cache
      service.clearCache();

      // Should fetch again
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);
    });

    it('should clear namespace-scoped cache only', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // Populate cache for namespace1
      await service.listBackupImages('namespace1');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(1);

      // Populate cache for namespace2
      await service.listBackupImages('namespace2');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);

      // Clear only namespace1
      service.clearNamespaceCache('namespace1');

      // namespace1 should fetch again (cache cleared)
      await service.listBackupImages('namespace1');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(3);

      // namespace2 should use cache (not cleared)
      await service.listBackupImages('namespace2');
      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(3); // Still 3, used cache
    });
  });

  describe('Cache Expiration', () => {
    const mockIBackupImages: IBackupImage[] = [
      {
        workspaceName: 'my-workspace',
        imageUrl,
        timestamp: '2026-02-10T12:00:00.000Z',
        sizeBytes: 1024000,
        labels: {},
      },
    ];

    it('should expire cache after TTL', async () => {
      mockAdapter.listBackupImages.mockResolvedValue(mockIBackupImages);

      // First call
      await service.listBackupImages(namespace);

      // Mock time advancement
      const originalDateNow = Date.now;
      Date.now = jest.fn(() => originalDateNow() + (BACKUP_CACHE_TTL_SECONDS + 1) * 1000);

      // Second call should fetch (cache expired)
      await service.listBackupImages(namespace);

      expect(mockAdapter.listBackupImages).toHaveBeenCalledTimes(2);

      // Restore
      Date.now = originalDateNow;
    });
  });
});
