/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.5

import React, { useEffect } from 'react';
import { useSelector } from 'react-redux';

import AgentActivityPage from '@/pages/AgentActivity';
import { useAppDispatch } from '@/store/hooks';
import { workspacesActionCreators } from '@/store/Workspaces';
import { selectWorkspacesWithAgents } from '@/store/Workspaces/devWorkspaces/selectors';

export default function AgentActivityContainer(): React.ReactElement {
  const dispatch = useAppDispatch();
  const agentWorkspaces = useSelector(selectWorkspacesWithAgents);

  useEffect(() => {
    // Initial fetch
    dispatch(workspacesActionCreators.requestWorkspaces());

    // Poll every 30 seconds
    const interval = setInterval(() => {
      dispatch(workspacesActionCreators.requestWorkspaces());
    }, 30_000);

    return () => clearInterval(interval);
  }, [dispatch]);

  return <AgentActivityPage workspaces={agentWorkspaces} />;
}
