/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupValidationResult } from '@eclipse-che/common';
import {
  FormGroup,
  HelperText,
  HelperTextItem,
  Panel,
  PanelHeader,
  PanelMain,
  PanelMainBody,
  Radio,
  Spinner,
  TextInput,
  Title,
  ValidatedOptions,
} from '@patternfly/react-core';
import { CheckCircleIcon, ExclamationCircleIcon } from '@patternfly/react-icons';
import React from 'react';
import { connect, ConnectedProps } from 'react-redux';

import styles from '@/pages/GetStarted/RestoreFromBackup/index.module.css';
import { Debounce } from '@/services/helpers/debounce';
import { AppDispatch, RootState } from '@/store';
import { validateBackupImage } from '@/store/Backups/actions';
import { selectDefaultNamespace } from '@/store/InfrastructureNamespaces/selectors';

export type RestoreMode = 'same-cluster' | 'cross-cluster';

export type ValidationState = 'idle' | 'validating' | 'valid' | 'invalid';

const WORKSPACE_NAME_PATTERN = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
const IMAGE_URL_PATTERN =
  /^[a-zA-Z0-9][a-zA-Z0-9._-]*(?::[0-9]+)?\/[a-zA-Z0-9._/-]+(?::[a-zA-Z0-9._-]+)?$/;

export type OwnProps = {
  registryUrl?: string;
};

export type Props = OwnProps & MappedProps;

export type State = {
  restoreMode: RestoreMode;
  workspaceName: string;
  workspaceNameValidated: ValidatedOptions;
  workspaceNameError: string;
  imageUrl: string;
  imageUrlValidated: ValidatedOptions;
  imageUrlError: string;
  validationState: ValidationState;
  validationResult: BackupValidationResult | undefined;
};

export class RestoreFromBackup extends React.PureComponent<Props, State> {
  private debounce: Debounce;
  private debounceHandler: () => void;

  constructor(props: Props) {
    super(props);

    this.debounce = new Debounce();
    this.debounceHandler = () => {
      this.performValidation();
    };
    this.debounce.subscribe(this.debounceHandler);

    this.state = {
      restoreMode: 'same-cluster',
      workspaceName: '',
      workspaceNameValidated: ValidatedOptions.default,
      workspaceNameError: '',
      imageUrl: '',
      imageUrlValidated: ValidatedOptions.default,
      imageUrlError: '',
      validationState: 'idle',
      validationResult: undefined,
    };
  }

  public componentWillUnmount(): void {
    this.debounceHandler && this.debounce.unsubscribe(this.debounceHandler);
  }

  private getRegistryUrl(): string {
    const { defaultNamespace, registryUrl } = this.props;
    const namespace = defaultNamespace.name || 'default';
    if (registryUrl) {
      return `${registryUrl}/${namespace}`;
    }
    return `image-registry.openshift-image-registry.svc:5000/${namespace}`;
  }

  private buildImagePreview(): string {
    const { workspaceName } = this.state;
    if (!workspaceName) {
      return '';
    }
    return `${this.getRegistryUrl()}/${workspaceName}:latest`;
  }

  private sanitizeWorkspaceName(value: string): string {
    return value.toLowerCase().replace(/[^a-z0-9-]/g, '');
  }

  private sanitizeImageUrl(value: string): string {
    return value.replace(/[<>"'`;|&$]/g, '');
  }

  private validateWorkspaceName(name: string): { validated: ValidatedOptions; error: string } {
    if (!name) {
      return { validated: ValidatedOptions.default, error: '' };
    }
    if (name.length > 63) {
      return {
        validated: ValidatedOptions.error,
        error: 'Workspace name must be 63 characters or less.',
      };
    }
    if (!WORKSPACE_NAME_PATTERN.test(name)) {
      return {
        validated: ValidatedOptions.error,
        error:
          'Must contain only lowercase letters, numbers, and hyphens. Must start and end with a letter or number.',
      };
    }
    return { validated: ValidatedOptions.success, error: '' };
  }

  private validateImageUrlFormat(url: string): { validated: ValidatedOptions; error: string } {
    if (!url) {
      return { validated: ValidatedOptions.default, error: '' };
    }
    if (!IMAGE_URL_PATTERN.test(url)) {
      return {
        validated: ValidatedOptions.error,
        error: 'Invalid image URL format. Expected: registry/repository:tag',
      };
    }
    return { validated: ValidatedOptions.default, error: '' };
  }

  private handleModeChange(mode: RestoreMode): void {
    this.setState({
      restoreMode: mode,
      workspaceName: '',
      workspaceNameValidated: ValidatedOptions.default,
      workspaceNameError: '',
      imageUrl: '',
      imageUrlValidated: ValidatedOptions.default,
      imageUrlError: '',
      validationState: 'idle',
      validationResult: undefined,
    });
  }

  private handleWorkspaceNameChange(value: string): void {
    const sanitized = this.sanitizeWorkspaceName(value);
    const { validated, error } = this.validateWorkspaceName(sanitized);
    this.setState({
      workspaceName: sanitized,
      workspaceNameValidated: validated,
      workspaceNameError: error,
    });
  }

  private handleImageUrlChange(value: string): void {
    const sanitized = this.sanitizeImageUrl(value);
    const { validated, error } = this.validateImageUrlFormat(sanitized);

    this.setState({
      imageUrl: sanitized,
      imageUrlValidated: validated,
      imageUrlError: error,
      validationState: 'idle',
      validationResult: undefined,
    });

    if (validated !== ValidatedOptions.error && sanitized) {
      this.setState({ validationState: 'validating' });
      this.debounce.execute();
    }
  }

  private async performValidation(): Promise<void> {
    const { imageUrl } = this.state;
    const { defaultNamespace } = this.props;
    const namespace = defaultNamespace.name || 'default';

    if (!imageUrl) {
      this.setState({ validationState: 'idle' });
      return;
    }

    try {
      const result = await this.props.validateBackupImage({ namespace, imageUrl });
      const payload = result.payload as BackupValidationResult;

      if (payload.valid && payload.accessible) {
        this.setState({
          validationState: 'valid',
          validationResult: payload,
          imageUrlValidated: ValidatedOptions.success,
          imageUrlError: '',
        });
      } else {
        this.setState({
          validationState: 'invalid',
          validationResult: payload,
          imageUrlValidated: ValidatedOptions.error,
          imageUrlError: payload.error || 'Backup image is not accessible.',
        });
      }
    } catch {
      this.setState({
        validationState: 'invalid',
        validationResult: undefined,
        imageUrlValidated: ValidatedOptions.error,
        imageUrlError: 'Failed to validate backup image.',
      });
    }
  }

  private renderValidationStatus(): React.ReactElement | null {
    const { validationState, validationResult } = this.state;

    switch (validationState) {
      case 'validating':
        return (
          <HelperText>
            <HelperTextItem variant="indeterminate" hasIcon>
              <span className={styles.validationIcon}>
                <Spinner size="sm" aria-label="Validating backup image" />
                Validating backup image...
              </span>
            </HelperTextItem>
          </HelperText>
        );
      case 'valid':
        return (
          <HelperText>
            <HelperTextItem variant="success" hasIcon icon={<CheckCircleIcon />}>
              Backup image is valid and accessible
              {validationResult?.metadata && (
                <> &mdash; {validationResult.metadata.workspaceName}</>
              )}
            </HelperTextItem>
          </HelperText>
        );
      case 'invalid':
        return null;
      default:
        return null;
    }
  }

  private renderSameClusterFields(): React.ReactElement {
    const { workspaceName, workspaceNameValidated, workspaceNameError } = this.state;
    const imagePreview = this.buildImagePreview();

    return (
      <div className={styles.formFields}>
        <FormGroup
          fieldId="restore-workspace-name"
          label="Workspace name"
          isRequired
          helperText="Enter the name of the workspace to restore."
          helperTextInvalid={workspaceNameError}
          helperTextInvalidIcon={<ExclamationCircleIcon />}
          validated={workspaceNameValidated}
        >
          <TextInput
            id="restore-workspace-name"
            aria-label="Workspace name"
            placeholder="my-workspace"
            value={workspaceName}
            validated={workspaceNameValidated}
            onChange={value => this.handleWorkspaceNameChange(value)}
          />
        </FormGroup>

        {imagePreview && (
          <FormGroup fieldId="restore-image-preview" label="Backup image URL">
            <div className={styles.imagePreview} data-testid="image-preview">
              {imagePreview}
            </div>
            <HelperText>
              <HelperTextItem>
                This URL will be used to locate the backup image in the cluster registry.
              </HelperTextItem>
            </HelperText>
          </FormGroup>
        )}
      </div>
    );
  }

  private renderCrossClusterFields(): React.ReactElement {
    const { imageUrl, imageUrlValidated, imageUrlError } = this.state;

    return (
      <div className={styles.formFields}>
        <FormGroup
          fieldId="restore-image-url"
          label="Backup image URL"
          isRequired
          helperText="Enter the full URL of the backup image from the source cluster."
          helperTextInvalid={imageUrlError}
          helperTextInvalidIcon={<ExclamationCircleIcon />}
          validated={imageUrlValidated}
        >
          <TextInput
            id="restore-image-url"
            aria-label="Backup image URL"
            placeholder="registry.example.com/namespace/workspace:latest"
            value={imageUrl}
            validated={imageUrlValidated}
            onChange={value => this.handleImageUrlChange(value)}
          />
        </FormGroup>

        {this.renderValidationStatus()}

        <HelperText>
          <HelperTextItem>Format: registry-host/namespace/workspace-name:tag</HelperTextItem>
        </HelperText>
      </div>
    );
  }

  public render(): React.ReactElement {
    const { restoreMode } = this.state;

    return (
      <Panel>
        <PanelHeader>
          <Title headingLevel="h3">Restore from Backup</Title>
        </PanelHeader>
        <PanelMain>
          <PanelMainBody>
            <div className={styles.radioGroup}>
              <div className={styles.radioItem}>
                <Radio
                  id="restore-mode-same-cluster"
                  name="restore-mode"
                  label="Same cluster"
                  description="Restore a workspace from a backup on this cluster."
                  isChecked={restoreMode === 'same-cluster'}
                  onChange={() => this.handleModeChange('same-cluster')}
                />
              </div>
              <div className={styles.radioItem}>
                <Radio
                  id="restore-mode-cross-cluster"
                  name="restore-mode"
                  label="Cross cluster"
                  description="Restore from a backup image on a different cluster or registry."
                  isChecked={restoreMode === 'cross-cluster'}
                  onChange={() => this.handleModeChange('cross-cluster')}
                />
              </div>
            </div>

            {restoreMode === 'same-cluster'
              ? this.renderSameClusterFields()
              : this.renderCrossClusterFields()}
          </PanelMainBody>
        </PanelMain>
      </Panel>
    );
  }
}

const mapStateToProps = (state: RootState) => ({
  defaultNamespace: selectDefaultNamespace(state),
});

const mapDispatchToProps = (dispatch: AppDispatch) => ({
  validateBackupImage: (params: { namespace: string; imageUrl: string }) =>
    dispatch(validateBackupImage(params)),
});

const connector = connect(mapStateToProps, mapDispatchToProps);

type MappedProps = ConnectedProps<typeof connector>;
export default connector(RestoreFromBackup);
