/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { BackupItem, BackupValidationResult } from '@eclipse-che/common';
import userEvent from '@testing-library/user-event';
import React from 'react';
import { Provider } from 'react-redux';

import getComponentRenderer, { screen, waitFor } from '@/services/__mocks__/getComponentRenderer';
import { che } from '@/services/models';
import { MockStoreBuilder } from '@/store/__mocks__/mockStore';

import { RestoreFromBackupPage } from '..';

const mockNavigate = jest.fn();
const mockValidateBackupImage = jest.fn();
const mockFetchBackupList = jest.fn();
const mockRestoreFromBackup = jest.fn();

const defaultNamespace: che.KubernetesNamespace = {
  name: 'user-namespace',
  attributes: {
    default: 'true',
    phase: 'Active',
  },
};

const mockBackups: BackupItem[] = [
  {
    workspaceName: 'my-workspace',
    imageUrl: 'image-registry.openshift-image-registry.svc:5000/user-namespace/my-workspace:latest',
    timestamp: '2026-02-11T12:00:00Z',
    sizeBytes: 1024,
    workspaceExists: true,
    labels: {},
  },
  {
    workspaceName: 'old-workspace',
    imageUrl:
      'image-registry.openshift-image-registry.svc:5000/user-namespace/old-workspace:latest',
    timestamp: '2026-02-10T12:00:00Z',
    sizeBytes: 2048,
    workspaceExists: false,
    labels: {},
  },
];

const { createSnapshot, renderComponent } = getComponentRenderer(getComponent);

describe('RestoreFromBackupPage', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('initial rendering', () => {
    test('should render page with title', () => {
      renderComponent();

      expect(screen.getByText('Restore from Backup')).toBeInTheDocument();
    });

    test('should render radio group with both modes', () => {
      renderComponent();

      expect(screen.getByLabelText('Same cluster')).toBeInTheDocument();
      expect(screen.getByLabelText('Cross cluster')).toBeInTheDocument();
    });

    test('should have same-cluster selected by default', () => {
      renderComponent();

      const sameClusterRadio = screen.getByLabelText('Same cluster');
      expect(sameClusterRadio).toBeChecked();
    });

    test('should render restore and cancel buttons', () => {
      renderComponent();

      expect(screen.getByTestId('restore-submit-button')).toBeInTheDocument();
      expect(screen.getByTestId('restore-cancel-button')).toBeInTheDocument();
    });

    test('should have restore button disabled initially', () => {
      renderComponent();

      expect(screen.getByTestId('restore-submit-button')).toBeDisabled();
    });

    test('should fetch backup list on mount', () => {
      renderComponent();

      expect(mockFetchBackupList).toHaveBeenCalledWith({ namespace: 'user-namespace' });
    });

    test('snapshot - initial state', () => {
      const snapshot = createSnapshot();
      expect(snapshot.toJSON()).toMatchSnapshot();
    });
  });

  describe('same-cluster mode', () => {
    test('should display workspace name input', () => {
      renderComponent();

      expect(screen.getByLabelText('Workspace name')).toBeInTheDocument();
    });

    test('should enable restore button when valid workspace name is entered', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'my-workspace');

      expect(screen.getByTestId('restore-submit-button')).not.toBeDisabled();
    });

    test('should display image preview when workspace name is entered', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'my-workspace');

      expect(screen.getByTestId('image-preview')).toHaveTextContent(
        'image-registry.openshift-image-registry.svc:5000/user-namespace/my-workspace:latest',
      );
    });

    test('should show backup dropdown when backups exist', () => {
      renderComponent({ backups: mockBackups });

      expect(screen.getByText('Select a backup to restore')).toBeInTheDocument();
    });

    test('should sanitize workspace name input', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'My_Workspace');

      expect(input).toHaveValue('myworkspace');
    });

    test('should show error for invalid workspace name', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, '-invalid');

      expect(
        screen.getByText(
          'Must contain only lowercase letters, numbers, and hyphens. Must start and end with a letter or number.',
        ),
      ).toBeInTheDocument();
    });
  });

  describe('cross-cluster mode', () => {
    test('should display image URL input when cross-cluster selected', async () => {
      renderComponent();

      const crossClusterRadio = screen.getByLabelText('Cross cluster');
      await userEvent.click(crossClusterRadio);

      expect(screen.getByLabelText('Backup image URL')).toBeInTheDocument();
    });

    test('should trigger validation for valid format URL', async () => {
      mockValidateBackupImage.mockResolvedValue({
        payload: {
          valid: true,
          accessible: true,
          metadata: {
            workspaceName: 'test-ws',
            namespace: 'test-ns',
            timestamp: '2026-02-11T12:00:00Z',
            sizeBytes: 1024,
          },
        } as BackupValidationResult,
      });

      renderComponent();

      const crossClusterRadio = screen.getByLabelText('Cross cluster');
      await userEvent.click(crossClusterRadio);

      const input = screen.getByLabelText('Backup image URL');
      await userEvent.click(input);
      await userEvent.type(input, 'registry.example.com/ns/workspace:latest');

      await waitFor(
        () => {
          expect(mockValidateBackupImage).toHaveBeenCalledWith({
            namespace: 'user-namespace',
            imageUrl: 'registry.example.com/ns/workspace:latest',
          });
        },
        { timeout: 2000 },
      );
    });

    test('should enable restore button when validation succeeds', async () => {
      mockValidateBackupImage.mockResolvedValue({
        payload: {
          valid: true,
          accessible: true,
          metadata: {
            workspaceName: 'test-ws',
            namespace: 'test-ns',
            timestamp: '2026-02-11T12:00:00Z',
            sizeBytes: 1024,
          },
        } as BackupValidationResult,
      });

      renderComponent();

      const crossClusterRadio = screen.getByLabelText('Cross cluster');
      await userEvent.click(crossClusterRadio);

      const input = screen.getByLabelText('Backup image URL');
      await userEvent.click(input);
      await userEvent.type(input, 'registry.example.com/ns/workspace:latest');

      await waitFor(
        () => {
          expect(screen.getByTestId('restore-submit-button')).not.toBeDisabled();
        },
        { timeout: 2000 },
      );
    });
  });

  describe('initial backup image URL', () => {
    test('should pre-fill cross-cluster mode with initial URL', () => {
      renderComponent({ initialBackupImageUrl: 'registry.example.com/ns/ws:latest' });

      const crossClusterRadio = screen.getByLabelText('Cross cluster');
      expect(crossClusterRadio).toBeChecked();

      const input = screen.getByLabelText('Backup image URL');
      expect(input).toHaveValue('registry.example.com/ns/ws:latest');
    });
  });

  describe('cancel button', () => {
    test('should navigate to workspaces list when cancel is clicked', async () => {
      renderComponent();

      const cancelButton = screen.getByTestId('restore-cancel-button');
      await userEvent.click(cancelButton);

      expect(mockNavigate).toHaveBeenCalled();
    });
  });

  describe('confirmation modal', () => {
    test('should open confirmation modal when restore is clicked', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'my-workspace');

      const restoreButton = screen.getByTestId('restore-submit-button');
      await userEvent.click(restoreButton);

      expect(screen.getByTestId('restore-confirmation-modal')).toBeInTheDocument();
      expect(screen.getByText('Confirm Restore from Backup')).toBeInTheDocument();
    });

    test('should show workspace name in confirmation modal', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'my-workspace');

      const restoreButton = screen.getByTestId('restore-submit-button');
      await userEvent.click(restoreButton);

      expect(screen.getByTestId('confirm-workspace-name')).toHaveTextContent('my-workspace');
    });

    test('should close confirmation modal when cancel is clicked', async () => {
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'my-workspace');

      const restoreButton = screen.getByTestId('restore-submit-button');
      await userEvent.click(restoreButton);

      const cancelButton = screen.getByTestId('restore-confirm-cancel-button');
      await userEvent.click(cancelButton);

      expect(screen.queryByTestId('restore-confirmation-modal')).not.toBeInTheDocument();
    });

    test('should call restoreFromBackup and navigate to workspaces on confirm', async () => {
      mockRestoreFromBackup.mockResolvedValue(undefined);
      renderComponent();

      const input = screen.getByLabelText('Workspace name');
      await userEvent.click(input);
      await userEvent.type(input, 'my-workspace');

      const restoreButton = screen.getByTestId('restore-submit-button');
      await userEvent.click(restoreButton);

      const confirmButton = screen.getByTestId('restore-confirm-button');
      await userEvent.click(confirmButton);

      await waitFor(() => {
        expect(mockRestoreFromBackup).toHaveBeenCalledWith(
          'user-namespace',
          'my-workspace',
          'image-registry.openshift-image-registry.svc:5000/user-namespace/my-workspace:latest',
        );
      });

      await waitFor(() => {
        expect(mockNavigate).toHaveBeenCalled();
      });
    });
  });

  describe('mode switching', () => {
    test('should clear workspace name when switching to cross-cluster', async () => {
      renderComponent();

      const nameInput = screen.getByLabelText('Workspace name');
      await userEvent.click(nameInput);
      await userEvent.type(nameInput, 'my-workspace');

      const crossClusterRadio = screen.getByLabelText('Cross cluster');
      await userEvent.click(crossClusterRadio);

      expect(screen.queryByLabelText('Workspace name')).not.toBeInTheDocument();
    });

    test('should clear image URL when switching to same-cluster', async () => {
      renderComponent();

      const crossClusterRadio = screen.getByLabelText('Cross cluster');
      await userEvent.click(crossClusterRadio);

      const urlInput = screen.getByLabelText('Backup image URL');
      await userEvent.click(urlInput);
      await userEvent.type(urlInput, 'registry.example.com/ns/ws:tag');

      const sameClusterRadio = screen.getByLabelText('Same cluster');
      await userEvent.click(sameClusterRadio);

      expect(screen.queryByLabelText('Backup image URL')).not.toBeInTheDocument();
    });
  });
});

function getComponent(
  options: {
    backups?: BackupItem[];
    initialBackupImageUrl?: string;
  } = {},
) {
  const store = new MockStoreBuilder().build();

  return (
    <Provider store={store}>
      <RestoreFromBackupPage
        defaultNamespace={defaultNamespace}
        backups={options.backups || []}
        validateBackupImage={mockValidateBackupImage}
        fetchBackupList={mockFetchBackupList}
        restoreFromBackup={mockRestoreFromBackup}
        navigate={mockNavigate}
        initialBackupImageUrl={options.initialBackupImageUrl}
      />
    </Provider>
  );
}
