#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: CI:multiarch-manifest

on:
  workflow_dispatch:
    inputs: {}
  pull_request:
    branches:
      - master

jobs:

  docker-build:
    runs-on: ubuntu-18.04
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64,arm64,ppc64le,s390x]
    env:
      IMAGE: docker.io/okurinnyi/che-dashboard
      CACHE_IMAGE_FULL: docker.io/okurinnyi/che-dashboard:cache
    outputs:
      amd64: ${{ steps.result.outputs.amd64 }}
      arm64: ${{ steps.result.outputs.arm64 }}
      ppc64le: ${{ steps.result.outputs.ppc64le }}
      s390x: ${{ steps.result.outputs.s390x }}
    steps:
      -
        name: "Checkout Che Dashboard source code"
        uses: actions/checkout@v2
      -
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      -
        name: "Set up Docker Buildx ${{ matrix.arch }}"
        uses: docker/setup-buildx-action@v1
      -
        name: "Docker docker.io Login"
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: "Build and push ${{ matrix.arch }}"
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE_FULL }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE_FULL }},mode=max
          context: .
          file: ./apache.Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ${{ env.IMAGE }}:${{ matrix.arch }}-next
      -
        id: result
        name: "Build result outputs version"
        if: ${{ success() }}
        run: echo "::set-output name=${{ matrix.arch }}::${{ matrix.arch }}-next"

  manifest:
    if: always()
    needs: docker-build
    runs-on: ubuntu-18.04
    env:
      IMAGE: docker.io/okurinnyi/che-dashboard
    steps:
      -
        name: "Docker docker.io Login"
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: "Create and push manifest"
        run: |
          AMEND=""
          AMD64_VERSION="${{ needs['docker-build'].outputs.amd64 }}"
          if [ -n "$AMD64_VERSION" ]; then
            AMEND+=" --amend ${{ env.IMAGE }}:$AMD64_VERSION";
          fi
          ARM64_VERSION="${{ needs['docker-build'].outputs.arm64 }}"
          if [ -n "$ARM64_VERSION" ]; then
            AMEND+=" --amend ${{ env.IMAGE }}:$ARM64_VERSION";
          fi
          PPC64LE_VERSION="${{ needs['docker-build'].outputs.ppc64le }}"
          if [ -n "$PPC64LE_VERSION" ]; then
            AMEND+=" --amend ${{ env.IMAGE }}:$PPC64LE_VERSION";
          fi
          S390X_VERSION="${{ needs['docker-build'].outputs.s390x }}"
          if [ -n "$S390X_VERSION" ]; then
            AMEND+=" --amend ${{ env.IMAGE }}:$S390X_VERSION";
          fi
          if [ -z "$AMEND" ]; then
            echo "[!] Provide at least one image to create manifest list"
            exit 1;
          fi
          docker manifest create ${{ env.IMAGE }}:manifest-next $AMEND
          docker manifest push ${{ env.IMAGE }}:manifest-next
