#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: PR

on:
  pull_request:
    branches: [master]

env:
  DIR_DASHBOARD: che-dashboard
  DIR_CHE: che
  IMAGE_VERSION: che-dashboard-pull-${{ github.event.pull_request.number }}
  ORGANIZATION: docker.io/maxura

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      -
        name: "Checkout Che Dashboard source code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: "Install dependencies"
        run: yarn
      -
        name: "Build"
        run: yarn compile
      -
        name: "Run unit tests"
        run: yarn test --runInBand
      -
        name: "Build Codecov report"
        uses: codecov/codecov-action@v1
